### ISSUE TITLE
apply default filter set as prefix filters

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#1002]
**Is your feature request related to a problem? Please describe.**

We want to be able to set a default filter to enable access logs only for errors, but want to be able that users can override based on their needs this global decision.

**Describe the solution you would like**

A solution would be to read default filters from some input, for example CLI flags and patch in our default filters to all routes in the routing package which call `LoadUpdate()` and `LoadAll()`.

**Describe alternatives you've considered (optional)**

I thought about putting it into dataclients, which would be not really maintainable.

**Would you like to work on it?**

Yes

**Comment by aryszka** [comment]
At first read, this sounds good to me. Could be a preprocessor in the routing, similar to the postprocessors, but not on *routing.Routes but on *eskip.Routes.

**Comment by topicus** [comment]
Is it possible to use a config file instead of CLI flags (not just for this but for all the options)? Once skipper is running I didn't find a simple way to capture the current configuration and a config file may mitigate this issue.

**Comment by szuecs** [comment]
@topicus why not file an issue for that?

**Comment by topicus** [comment]
Yes, I wanted to get your feedback first.
