### ISSUE TITLE
Question: Does a single Skipper instance can handle requests form multiple domains with different certificates for each domain?

### ISSUE THREAD

**Issue by avishaiNB** [zalando/skipper#1004]
Q: Does a single Skipper instance can handle requests form multiple domain with different certificates for each domain?

**for example:**

https://www.site1.com --> skipper (use Certificate_Site1) --> NodeJS/Express1
https://www.site2.com --> skipper (use Certificate_Site2) --> NodeJS/Express2

Thank you in advance.

**Comment by szuecs** [comment]
No, right now it is not possible to set multiple certificates/keys. You would need to have a multi domain certificate or use some other tool. If this blocks you from using skipper we might be able to support this without much work.

**Comment by avishaiNB** [comment]
Hi @szuecs ,

First thank you for the quick reply.

That means that skipper knows how to map the client's https request to the matching domains certificate?

Regards,
Avishai.

**Comment by szuecs** [comment]
Yes, and the protocol that makes it possible is called SNI.

**Comment by szuecs** [comment]
Please reopen if you have any question related to this

**Comment by avishaiNB** [comment]
Perfect!.
10x, it worked.

Regards,
Avishai.
