### ISSUE TITLE
Document default filters

### ISSUE THREAD

**Issue by avishaiNB** [zalando/skipper#1012]
Question: Is it possible to have a filter which will always run and we don't need to set it up per route?

**Comment by szuecs** [comment]
https://github.com/zalando/skipper/releases/tag/v0.10.195 introduced add default filters to all routes.
You can append or prepend the filters in the chain:
```
-default-filters-append='setResponseHeader("X-Bar", "BAR") -> modPath("/api/", "/")'
-default-filters-prepend='enableAccessLog(4,5)'
```

**Comment by szuecs** [comment]
https://opensource.zalando.com/skipper/operation/operation/#default-filters
