### ISSUE TITLE
Question: Can i define a Fallback route ?

### ISSUE THREAD

**Issue by avishaiNB** [zalando/skipper#1013]
Hi,

Lets say i try to access a route that does not exists in route file, is it possible to define a "not found" route with custom behavior? (or using a custom filter).

Regards,
Avishai.

**Comment by szuecs** [comment]
A fallback route can always be a wildcard route (r0 in this case):

```
r0: * -> inlineContent("<html><body>DEFAULT</body></html>") -> status(404) -> <shunt>;
r1: Host(foo) -> ... -> https://foo.example.org;
r2: ..
..
rN ..
```

**Comment by AlexanderYastrebov** [comment]
In the https://github.com/zalando/skipper/issues/1013#issuecomment-477168269 `status` filter should be before `inlineContent`, see https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#inlinecontent

**Comment by AlexanderYastrebov** [comment]
Closing as https://github.com/zalando/skipper/issues/1013#issuecomment-477168269 answers the question, please reopen if I've missed something.
