### ISSUE TITLE
Question: HW setup for linux machine

### ISSUE THREAD

**Issue by orenkup** [zalando/skipper#1014]
Hi,
What is the recommended spec for skipper on linux machine?
RAM, CPU, HDD?

**Comment by szuecs** [comment]
@orenkup it depends on how much traffic per instance you want to serve.
The workload is CPU bound and memory depends on which features you enable and use.
HDD is not used, besides loading the binary. 
Additionally if you have slow backends with high traffic you need memory to have the goroutines serving the connections. In our Kubernetes setup we run with max 1 CPU core and 2 GB memory.

For hardware https://github.com/zalando/skipper/issues/1010 was a similar question which should be valid also for Linux.

**Comment by szuecs** [comment]
closing because of too few data provided for requirements
