### ISSUE TITLE
per backend ratelimit

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#1033]
In some cases you want to protect backends by instances with a ratelimit.
For example to protect stateful applications, which you have a clear understanding of how much load it can serve per instance.

This was requested by 2 different Zalando users and seems to be a valid use case in general.

Unclear: how to deal with load balancing, should an already overloaded backend be counted in the load balancer or already dropped from the backend list for the time frame?

## Implementation idea

One idea is to not send ctx.Route to the Loadbalancer, only the LBEndpoints, and filter them before sending them to the loadbalancer.

Semantic:
- If an endpoint had already enough request for the duration -> drop the endpoint from the list
- If the EndpointList is empty -> 429. This requires to have online stats with requests per duration from the endpointRatelimit. We could have a filter endpointRatelimit that only counts requests for the give time.Duration window. This information we have to store in the stateBag, and redis in case of clusterEndpointRatelimit, and use the stateBag (or redis lookup) in proxy#setRequestURLForLoadBalancedBackend (we would need to pass the FilterContext to this function or at least the content of the stateBag).

**Comment by AlexanderYastrebov** [comment]
See https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#backendratelimit
