### ISSUE TITLE
closed Body error on repeated makeBackendRequest()

### ISSUE THREAD

**Issue by olevchyk** [zalando/skipper#1034]
**Describe the bug**
Noticed the following errors on test cluster where nodes can go down more frequently: 
```
{"log":"[APP]time=\"2019-04-15T11:30:42Z\" level=error msg=\"Failed to do retry backend request: dialing failed false: http: invalid Read on closed Body\"
","stream":"stderr","time":"2019-04-15T11:30:42.637245921Z"}
```
That probably comes from https://github.com/zalando/skipper/blob/master/proxy/proxy.go#L992 

**To Reproduce**
1. forcefully shutdown a node where your pod is located, to get DialError that leads to 2nd makeBackendRequest call.  

**Expected behavior**
We create a buffer copy of request.Body 
**Observed behavior**
Body is gone after initial request, skipper generates errors.

**Comment by szuecs** [comment]
@olevchyk Thanks for providing the issue.
Just to clarify:
- You run x number of replicas where `x > 1`?
- The call to podX was in progress when you killed/terminated the underlying node of podX?
- The result of the retry to podY was getting the error message instead of the content provided by podY?

**Comment by jruhland** [comment]
Also experiencing this on fully healthy pod targets

**Comment by szuecs** [comment]
@jruhland thanks for the provided logs. It shows clearly the bug in skipper.

**Comment by szuecs** [comment]
I looked into the code path and I don't see where this could happen. We do the retry before we close the body in all cases. I will follow up and write a test case that should show my expectation that it should be correct.

I did not need too much time to find similar logs.
I found a couple of similar requests that show the same error. For one skipper container and one (?) request I see this:

```
"POST /some/path/ HTTP/1.1" 500 22 "-" "AHC/2.1" 60001 example.org - -
"Failed to do backend roundtrip to : dialing failed true: dial tcp 10.2.206.169:8080: i/o timeout"'
"Failed to do retry backend request: dialing failed false: http: invalid Read on closed Body"'
"error while proxying, route kube_...example_org with backend , status code 500: dialing failed false: http: invalid Read on closed Body"'
```

Do you also see this in POST requests that responded with 500 like this above?

**Comment by jruhland** [comment]
Can confirm, we are seeing retries, the log is funny, but not problematic.

**Comment by szuecs** [comment]
Logs:
```
log='[APP]time="2019-06-24T12:24:02Z" level=error msg="Failed to do backend roundtrip to : dialing failed true: dial tcp 10.2.39.22:8080: connect: connection refused"'
log='[APP]time="2019-06-24T12:24:02Z" level=error msg="Failed to do retry backend request: dialing failed false: http: invalid Read on closed Body"'
```

**Comment by szuecs** [comment]
We don't retry requests with body since ba9801db5289019424845b34ad3e149201cd5448 07/2019
