### ISSUE TITLE
random 502 errors on test environment. 

### ISSUE THREAD

**Issue by olevchyk** [zalando/skipper#1036]
**Describe the bug**
We have 2 replicas application deployment,  deployed using stackset controller,  continuously checked by zmon over https.  During working hours, when everything is up and running on test cluster, we notice random 502 errors reported by both: skipper metrics and logs  & zmon global http checks. There are no errors on application logs but there are some roundtrip errors in skipper logs. 
Please see logs below to understand better what's going on: 
pod is being investigated: name: app-pod-aa, ip:10.xx.xx.xx 
*route settings, update, route* , records when ip was added and removed from routing: 
```
{"log":"[APP]time=\"2019-04-15T10:47:39Z\" level=info msg=\"route settings, update, route: kube_ns_host: Host(/^HOSTRULE$/) -> <roundRobin, \\\"http://10.yy.yy.yy:9000\\\", \\\"http://10.xx.xx.xx:9000\\\">\"
","stream":"stderr","time":"2019-04-15T10:47:39.622328565Z"}

{"log":"[APP]time=\"2019-04-15T11:29:47Z\" level=info msg=\"route settings, update, route: kubeew_ns_host: Host(/^HOSTRULE$/) -> \\\"http://10.yy.yy.yy:9000\\\"\"
","stream":"stderr","time":"2019-04-15T11:29:47.966329942Z"}
```
where http://10.yy.yy.yy:9000 is the ip of another healthy replica. 

Node/Pod removal messages: 
```
{"log":"I0415 10:33:47.079619       1 cluster.go:95] Fast evaluation: node ip-zz-zz-zz-zz.eu-central-1.compute.internal cannot be removed: no enough pod disruption budget to move ns/app-pod-aa
","stream":"stderr","time":"2019-04-15T10:33:47.079667961Z"}
{"log":"I0415 10:38:51.486798       1 cluster.go:95] Fast evaluation: node ip-zz-zz-zz-zz.eu-central-1.compute.internal cannot be removed: no enough pod disruption budget to move ns/app-pod-aa
","stream":"stderr","time":"2019-04-15T10:38:51.486904274Z"}
{"log":"I0415 10:43:56.339257       1 cluster.go:95] Fast evaluation: node ip-zz-zz-zz-zz.eu-central-1.compute.internal cannot be removed: no enough pod disruption budget to move ns/app-pod-aa
","stream":"stderr","time":"2019-04-15T10:43:56.339310223Z"}

{"log":"I0415 11:30:02.658882       1 gc_controller.go:62] PodGC is force deleting Pod: ns/app-pod-aa
","stream":"stderr","time":"2019-04-15T11:30:02.658940763Z"}
```

Skipper round-trip errors: 
```
 13:30:23.000  {"log":"[APP]time=\"2019-04-15T11:30:23Z\" level=error msg=\"Failed to do backend roundtrip to : dialing failed true: dial tcp 10.xx.xx.xx:9000: i/o timeout\"
","stream":"stderr","time":"2019-04-15T11:30:23.657542139Z"}
 13:30:42.000  {"log":"[APP]time=\"2019-04-15T11:30:42Z\" level=error msg=\"Failed to do backend roundtrip to : dialing failed true: dial tcp 10.xx.xx.xx:9000: i/o timeout\"
","stream":"stderr","time":"2019-04-15T11:30:42.636352317Z"}
 13:30:44.000  {"log":"[APP]time=\"2019-04-15T11:30:44Z\" level=error msg=\"Failed to do backend roundtrip to : dialing failed true: dial tcp 10.xx.xx.xx:9000: i/o timeout\"
","stream":"stderr","time":"2019-04-15T11:30:44.029879409Z"}
 13:31:44.000  {"log":"[APP]time=\"2019-04-15T11:31:44Z\" level=error msg=\"Failed to do backend roundtrip to : dialing failed true: dial tcp 10.xx.xx.xx:9000: i/o timeout\"
","stream":"stderr","time":"2019-04-15T11:31:44.030364665Z"}
 13:31:44.000  {"log":"[APP]time=\"2019-04-15T11:31:44Z\" level=error msg=\"Failed to do retry backend request: dialing failed true: dial tcp 10.xx.xx.xx:9000: i/o timeout\"
","stream":"stderr","time":"2019-04-15T11:31:44.030400031Z"}
 13:31:44.000  {"log":"[APP]time=\"2019-04-15T11:31:44Z\" level=error msg=\"error while proxying, route kube_ns__host with backend , status code 502: dialing failed true: dial tcp 10.xx.xx.xx:9000: i/o timeout\"
","stream":"stderr","time":"2019-04-15T11:31:44.03040569Z"}
``` 
As you can see from the logs, 10.xx.xx.xx  was removed from routing table just before RoundTrip io timeout errors on skipper. 
I'm not sure whether this is bug, it seems to be quite obvious scenario when your node forcefully goes down, however I wanted to ask if it is possible to improve this, as it took almost 2 minutes between route update and last error message, 11:29:47 <> 11:31:44

**Comment by szuecs** [comment]
@olevchyk normally this is caused by backends not having a good enough readinessProbe and not a proper tear down strategy. https://opensource.zalando.com/skipper/kubernetes/ingress-backends/#teardown-strategies might help.
The reason is the Kubernetes race condition of skipper not knowing that your pod is terminating.
Basically you need to switch your health check to report unhealthy if you get a SIGTERM, but handle for let's say 10 seconds longer all incoming requests.

**Comment by olevchyk** [comment]
Thanks for your answer. 
let me check  these settings and test everything one more time.
