### ISSUE TITLE
Add option to pull cli args/switches from configfile

### ISSUE THREAD

**Issue by southwel** [zalando/skipper#1039]
**Is your feature request related to a problem? Please describe.**
There are numerous command line args for skipper, if you have a complex deployment the command line arg gets very long.

**Describe the solution you would like**
Add an option(yes I get the irony) like `-configfile=/path/to/skipper.yaml`.  Doesn't have to be yaml, just an example.  In this file you can define all the switches and arg values.

**Describe alternatives you've considered (optional)**
Right now I just put all the switches and args on a single line in my systemd service definition file.

**Additional context (optional)**
None.

**Would you like to work on it?**
No.  I don't know the language well enough yet to be of any use in this regard.

**Comment by szuecs** [comment]
@southwel thanks for the feature request.
