### ISSUE TITLE
oauthToken* filters can not check same key with different values

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#1044]
**Describe the bug**
Same keys can not be used in `oauthToken*` filters

**To Reproduce**

1. add a route with the same key to different value in tokeninfoKV filters: `oauthTokeninfoAnyKV("foo", "A", "foo", "B") `
2. check with a token that have one of these values `A` or `B` in key `"foo"`

**Expected behavior**

It should allow

**Observed behavior**

It does not allow

**Comment by szuecs** [comment]
We use `type kv map[string]string` as storage for all KV filters.
We can either:
1. change it to `type kv map[string][]string`
2. create a new set of filters

I would vote for 1., @aryszka what do you think?

**Comment by drummerwolli** [comment]
for sprint planning estimation meetings: can you estimate if this will be fixed and released in registry.opensource.zalan.do/pathfinder/skipper in the next two weeks?

**Comment by szuecs** [comment]
It was already released in v0.10.222 and for Zalando we already rolled this out to production clusters.
