### ISSUE TITLE
Improve metrics

### ISSUE THREAD

**Issue by lmineiro** [zalando/skipper#105]
We need a global request metric and also a routing failure metric

**Comment by aryszka** [comment]
what did happen to #105?


On Tue, Mar 8, 2016, at 08:54 PM, Luis wrote:
> Closed #105[1].


> — Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://github.com/zalando/skipper/issues/105
  2. https://github.com/zalando/skipper/issues/105#event-582259418

**Comment by lmineiro** [comment]
Should've added some comments before closing.
I came to realize that this can easily be solved in the collector (zmon + grafana) and it wouldn't make sense to add the aggregates to the current metrics setup.
