### ISSUE TITLE
Access log filters don't chain correctly

### ISSUE THREAD

**Issue by aermakov-zalando** [zalando/skipper#1053]
**Describe the bug**

It looks like `disableAccessLog()` filter doesn't work correctly if it follows `enableAccessLog()` with some parameters, because I still see the logs.

**To Reproduce**

1. Have `enableAccessLog(4, 5)` filter injected as a default into all routes.
2. Add `disableAccessLog()` to a specific route.

**Expected behavior**

Skipper doesn't log any requests for this route.

**Observed behavior**

4xx and 5xx requests are still logged.

**Comment by szuecs** [comment]
I can't observe the same behavior with the inlineroutes:

This does not log, so disable is enforced:
```
% ./bin/skipper -default-filters-prepend="enableAccessLog(4, 5)" -inline-routes='foo: * -> disableAccessLog() -> status(400) -> <shunt>'
[APP]INFO[0000] Expose metrics in codahale format
[APP]INFO[0000] route settings, reset, route: foo: * -> disableAccessLog() -> status(400) -> <shunt>
[APP]INFO[0000] route settings received
[APP]INFO[0000] support listener on :9911
[APP]INFO[0000] route settings applied
[APP]INFO[0000] proxy listener on :9090
[APP]INFO[0000] TLS settings not found, defaulting to HTTP
^C
```
This logs
```
% ./bin/skipper -default-filters-prepend="enableAccessLog(4, 5)" -inline-routes='foo: * -> status(400) -> <shunt>'
[APP]INFO[0000] Expose metrics in codahale format
[APP]INFO[0000] support listener on :9911
[APP]INFO[0000] proxy listener on :9090
[APP]INFO[0000] TLS settings not found, defaulting to HTTP
[APP]INFO[0000] route settings, reset, route: foo: * -> status(400) -> <shunt>
[APP]INFO[0000] route settings received
[APP]INFO[0000] route settings applied
::1 - - [16/May/2019:18:12:06 +0200] "GET / HTTP/1.1" 400 0 "-" "curl/7.49.0" 0 localhost:9090 - -
```

**Comment by szuecs** [comment]
I also can't observe the same behavior in Kubernetes with custom routes nor with skipper-filter annotation.
I bet there was something wrongly defined in the route, such that it had no effect.

@aermakov-zalando feel free to reopen the issue and provide more information. Thanks
