### ISSUE TITLE
cron style predicate for time based route match

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#1082]
**Is your feature request related to a problem? Please describe.**

In case of scheduled maintenance window, you want to be able to schedule daily, weekly, monthly a fixed maintenance window and show a "come back later" message.

**Describe alternatives you've considered (optional)**

You can workaround the problem with a cronjob that changes the routes-file or the routes in etcd, for example

**Comment by aryszka** [comment]
See also: https://opensource.zalando.com/skipper/reference/predicates/#interval

**Comment by szuecs** [comment]
@aryszka from what I understand interval predicates can’t do something like everyday from 10-18 for example.

**Comment by aryszka** [comment]
no, they cannot. They're just a closely related feature.

**Comment by sarslanhan** [comment]
As discussed with both of you, I created a small library for doing this: https://github.com/sarslanhan/cronmask

@szuecs @aryszka let me know what you think about it. In the meantime, I can work on adding a predicate that makes use of this in Skipper.

**Comment by szuecs** [comment]
Thanks @sarslanhan for providing the merged PR and the library.
