### ISSUE TITLE
Secure flag not set for cookies stored by oauthOidc -filters

### ISSUE THREAD

**Issue by josafat** [zalando/skipper#1085]
**Describe the bug**
oauthOidc* -filters store cookies on the client. These cookies are missing the Secure -flag regardless if HTTPS is used or not.

**To Reproduce**
Any route with oauthOidc* -filter, which passes OIDC auth.

**Expected behavior**
The cookies have Secure -flag set over HTTPS connections

**Observed behavior**
Secure -flag is not set on the oidc cookies

**Comment by szuecs** [comment]
@arjunrn do you remember if this was only used for testing?

**Comment by arjunrn** [comment]
@szuecs I might have overlooked this one. Fix for this should be easy. I will assign this issue to me for now.
