### ISSUE TITLE
unverifiedAuditLog should have fall back keys

### ISSUE THREAD

**Issue by drummerwolli** [zalando/skipper#1090]
We're trying to log audit requests. we try to use `unverifiedAuditLog()` (docs: [here](https://opensource.zalando.com/skipper/reference/filters/#unverifiedauditlog)) filter for this. included in this log line should be some information on the entity issuing this requests (so either username or application id or something similar). This information is in the token in either the `sub` key or in other keys. good thing is able to extract this from the token, but only for one key only. its not possible to set up multiple possibilities for different types of tokens. I tried also to use multiple `unverifiedAuditLog()`, and the good thing is that `unverifiedAuditLog()` logs only one time, but consider this routes file:

```
health: Path("/")
  -> unverifiedAuditLog("foo")
  -> unverifiedAuditLog("bar")
  -> <shunt>;
```

Skipper uses only the last key (`bar` in this case), and completely ignores the first one.

my proposal would be that the filter accepts multiple values (or an array of values), where the first value will be the first one to get checked. if that key is not in the JWT token, then the next one is used:

```
health: Path("/")
  -> unverifiedAuditLog("foo", "bar")
  -> <shunt>;

########## OR

health: Path("/")
  -> unverifiedAuditLog(["foo", "bar"])
  -> <shunt>;
```

**Comment by szuecs** [comment]
Varargs style seems to be the best fit for user interface, consistency and backwards compatibility. So my clear vote for `unverifiedAuditLog(“a”, “b”)`.
