### ISSUE TITLE
apiusagemonitoring is using modified path from response chain

### ISSUE THREAD

**Issue by tkrop** [zalando/skipper#1094]
**Describe the bug**
When monitoring APIs using the API usage monitoring filter, the filter is using the modified path from the response chain instead of the original path from the begin of the request chain - assuming that the API usage monitoring filter is the first installed in the filter chain.

**To Reproduce**
Add context, for example:
1. create an `apiUsageMonitoring` filter followed by a `modPath` filter changing the path.
2. execute a request on the original path
3. look for the metrics collected by the monitoring filter, which will match against the modified path.

**Expected behavior**
Collect a monitoring event for the original path before filter modification.

**Observed behavior**
Collected a monitoring event for the modified path after filter modification.

**Comment by lmineiro** [comment]
I'd personally consider the current behavior as desirable. There's the flexibility to change the order of the filters allowing the users to decide which path to use instead.
I can think of use cases where the modified path is intended. That is also the path that the backend will effectively handle, which might be closer to the user that opts-in for the apiusagemonitoring, matching his expectation.

**Comment by tkrop** [comment]
Unfortunately, our current customers see this different, because the API monitoring is not consistent with their external API specification. As we want support out-of-the-box API usage monitoring this consistency is essential.

**Comment by aryszka** [comment]
If I see it right, then this PR allows the right level of flexibility of which path is monitored: #1095

if the path is modified before the usage monitoring filter, then the modified path is used. If the monitoring filter is after a path changing filter then the changed path is monitored.
