### ISSUE TITLE
Installation instructions are not working

### ISSUE THREAD

**Issue by max-neverov** [zalando/skipper#1133]
**Describe the bug**
Can't install skipper following instructions in README.

**To Reproduce**
➜  ~ GO111MODULE=on go get -t github.com/zalando/skipper/...

**Expected behavior**
skipper is installed

**Observed behavior**
go get: -t flag is a no-op when using modules
go: finding github.com/zalando/skipper/... latest
go get github.com/zalando/skipper/...: no matching versions for query "latest"

**Workaround**
Run the same command without `/...`
➜  ~ GO111MODULE=on go get -t github.com/zalando/skipper

According to the [bug](https://github.com/golang/go/issues/27215) this is bug in `go get` and it will be fixed in 1.13. Until then can the readme be updated to remove `/...` from the installation instruction?

**System details**
➜  ~ go version
go version go1.12.7 darwin/amd64

➜  ~ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/max/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/max/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z8/4_7gbsx94f974xylc34953ym0000gn/T/go-build467927618=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by szuecs** [comment]
Thanks for the report. 
If you like to send a PR, if not we wait for Go 1.13, which should be soon there.

**Comment by xavivars** [comment]
1.13 has been released. I guess this issue is not reproducible anymore

**Comment by max-neverov** [comment]
Can confirm.
```$ go version
go version go1.13.1 linux/amd64```
The command works as expected. Should I close this?

**Comment by szuecs** [comment]
Yes, thanks
