### ISSUE TITLE
Redirect to location by using values captured from the original path

### ISSUE THREAD

**Issue by diego-ojeda-binbash** [zalando/skipper#1137]
**Describe the bug**
Hi. This is probably not a bug but I have been looking through the documentation and Github issues and have not been able to find a solution to my issue.
I am using Skipper on our Kubernetes clusters and I would like to achieve the following redirection behavior:

Given the following example paths:
> example.com/na/{zone id}
> example.com/latam/{zone id}

I would like to redirect those to this:
> another-example.com/regions/na/{zone id}
> another-example.com/regions/latam/{zone id}

Keep in mind that {zone id} is a variable identifier that I would like to capture in order to pass it to the redirect locations. I am not sure if this is possible though. Thanks for your help in advance!

**To Reproduce**
1. Set the route (on Kubernetes I set this in a zalando.org/skipper-routes annotation, but locally I use a simple config file):
```
redirRegionZone: Path("/na/:zoneid")
    -> redirectTo(301, "https://another-example.com/regions/na/:zoneid")
    -> <shunt>;
```
I also tried this using PathRegexp:
```
redirRegionZoneRegex: PathRegexp("^/na/(?:.*)$")
    -> redirectTo(301, "https://another-example.com/regions/na/$1")
    -> <shunt>;
```
2. Run skipper (I am running it locally via docker image)
3. Test: `curl -I localhost:8080/na/1`

**Expected behavior**
I expect a Location header set to this: `https://another-example.com/regions/na/1`

**Observed behavior**
I am getting this instead: `https://another-example.com/regions/na/:zoneid`

**Comment by diego-ojeda-binbash** [comment]
Never mind, I just found out that I could achieve what I needed as follows:
```
redirRegionZone: PathSubtree("/na/:zoneid")
    -> modPath("/na", "/regions/na")
    -> redirectTo(301, "https://another-example.com")
    -> <shunt>;
```
I also found in the code (path.go, line 35) that setPath filter provides a templating feature that can take placeholder that would be replaced by the wildcard values with the same name. I couldn't get it to work for me but I'm mentioning that in case it's useful for someone.

**Comment by szuecs** [comment]
For the records: https://opensource.zalando.com/skipper/tutorials/common-use-cases/#change-base-path documents how to do the redirect with `modPath`.

**Comment by szuecs** [comment]
For the records: https://opensource.zalando.com/skipper/tutorials/common-use-cases/#change-base-path documents how to do the redirect with `modPath`.
