### ISSUE TITLE
Support custom Metrics implementations

### ISSUE THREAD

**Issue by mtrovo** [zalando/skipper#1151]
**Is your feature request related to a problem? Please describe.**
I'm currently using skipper and I have a use case to export the metrics to NewRelic as custom events, I managed to make it work by polling the Codahale registry and sending these events to NewRelic but is just a quick hack that is not very reliable as the data is polled and also for some metric types the aggregation already took place.

**Describe the solution you would like**
Skipper should support a way to give users the ability to provide their own implementation of Metrics. This way there's no need to support any new metric kind out of the box and give the users real time flexibility to extend how their metrics are being stored.

**Describe alternatives you've considered (optional)**
Polling the registry is the way I'm doing it right now.
For this specific problem you could also provide a new relic custom events metrics provider and one would configure it in a similar way to how this is done for prometheus.

**Would you like to work on it?**
Yes

**Comment by lmineiro** [comment]
[OpenTelemetry](https://opentelemetry.io/) is the merge of 2 other great projects - OpenTracing and OpenCensus. What are your thoughts on that @mtrovo? 

I think the project is still young but its roots are solid. Having a standard way of collecting all things observability sounds interesting to me.
