### ISSUE TITLE
[Kubernetes] ExternalName Service is served for wrong Ingress

### ISSUE THREAD

**Issue by linki** [zalando/skipper#1157]
**Describe the bug**
Normally, when an Ingress references a wrong or missing Service then `skipper-ingress` serves 404 as the fallback. However, if there is at least one Ingress in the cluster that points to an ExternalName Service then `skipper-ingress` serves that ExternalName instead of 404.

**To Reproduce**
1. create an Ingress `foo` with a rule for `foo.playground.zalan.do` that points to a non-existing Service
2. curl `foo.playground.zalan.do` and see that it returns a 404
3. create another Ingress `bar` with a rule for `bar.playground.zalan.do` that points to Service `bar`
4. create Service `bar` to be an ExternalName for `google.com`
5. curl `bar.playground.zalan.do` and see that it serves google's search page
6. also curl again `foo.playground.zalan.do` and see that it now *also* serves google's search page

**Expected behavior**

Step 6 should not happen and `foo.playground.zalan.do` should still be a 404.

**Observed behavior**

`foo.playground.zalan.do` displays google's search page.

**Comment by szuecs** [comment]
should be fixed in https://github.com/zalando/skipper/releases/tag/v0.11.166
