### ISSUE TITLE
Add tags to jaeger tracing spans

### ISSUE THREAD

**Issue by wndhydrnt** [zalando/skipper#1162]
**Is your feature request related to a problem? Please describe.**
I'd like to add tags to tracing spans created by jaeger to be able to later filter by these tags.

**Describe the solution you would like**
Either a new option for the `-opentracing` flag that is then [parsed](https://github.com/zalando/skipper/blob/master/tracing/tracers/jaeger/jaeger.go#L32-L89) by the jaeger implementation or reading configuration from env vars as [supported](https://github.com/jaegertracing/jaeger-client-go/blob/master/config/config_env.go#L53) by jaeger client.

**Describe alternatives you've considered (optional)**
/

**Additional context (optional)**
/

**Would you like to work on it?**
Yes

**Comment by wndhydrnt** [comment]
I need a decision on whether to add/parse tags through the `-opentracing` flag or implement reading jaeger configuration from env vars.

`-opentracing` is the way Skipper does it while env vars provide more flexibility. I have no preference for any of the two solutions.

**Comment by szuecs** [comment]
@wndhydrnt sounds good. I would do it similar to the lightstep tracer, that we use. Parse the flag similar to https://github.com/zalando/skipper/blob/master/tracing/tracers/lightstep/lightstep.go#L66-L72 and set the values that you need to pass to Jaeger.

**Comment by wndhydrnt** [comment]
Thanks for the quick reply @szuecs. I'll look into the code you referenced and create a PR.
