### ISSUE TITLE
Content-Length not set by setRequestHeader

### ISSUE THREAD

**Issue by zak905** [zalando/skipper#1167]
**Describe the bug**

I am trying to test a Content-Length header "spoofing" scenario for my API where the Content-Length value would mismatch the actual body length. 

**To Reproduce**

1. skipper can be run with a simple route defintion like 
```
hello: * -> setRequestHeader("Content-Length", "1000") -> "http://localhost:8180";
```
2. check the request received by "http://localhost:8180", the header is the actual one sent with the request, and not 1000

**Expected behavior**

setRequestHeader("Content-Length", "1000") should set the header value to 1000

**Observed behavior**

The value is somehow the same or reset by skipper to match the body length

**Comment by szuecs** [comment]
The Content-Length header is computed by the Go runtime and we would need to create a workaround in the proxy.

Content-Length header "spoofing" is not supported and probably won't be in the future.
We discussed it internally and we don't see much value and it could be unsafe in case for example compress filter is being used.

I am sorry for you, that the issue will be closed and changed to wontfix.
