### ISSUE TITLE
Question - How to identify 504 errors

### ISSUE THREAD

**Issue by jmirc** [zalando/skipper#1206]
We are running skipper in production and we are getting 504 error. Here are the logs

```
{"log":"[APP]time=\"2019-10-03T10:19:36Z\" level=error msg=\"net.Error during backend roundtrip to : timeout=true temporary=true: net/http: timeout awaiting response headers\"\n","stream":"stderr","time":"2019-10-03T10:19:36.169130569Z"}
{"log":"[APP]time=\"2019-10-03T10:19:36Z\" level=error msg=\"error while proxying, route kube_content_hub_prod__cs_media_gateway_v1__cs_media_service_us_west_2_eglocal_exp_prod_net_____cs_media_gateway_v1 with backend , status code 504: dialing failed false: net/http: timeout awaiting response headers\"\n","stream":"stderr","time":"2019-10-03T10:19:36.169137069Z"}
```

We are not able to see these issues on our service (response time is fine). It is like connections are created between skipper and the service but the service doesn't response in the expected time. 

Do you have any tips?

Thanks

**Comment by szuecs** [comment]
@jmirc yes the service does not respond within expected time. 

`net/http: timeout awaiting response headers` means that the http headers from the backend response timed out. Increasing `-response-header-timeout-backend` can help, if you expect that the backend will often have higher response times than the default. You might want to check all the timeout settings if you increase this, because it could be that you reach some other limit, after this one.

**Comment by tomekit** [comment]
Facing similar issue:
```
[APP]time="2021-03-29T16:44:23Z" level=error msg="net.Error during backend roundtrip to http://100.103.181.103:80: timeout=true temporary=true: net/http: timeout awaiting response headers"
[APP]time="2021-03-29T16:44:23Z" level=error msg="error while proxying after 1m0.021587566s, route kube_default__bomcheck_ingress__demo_bomcheck_net_____bomcheck_web with backend network http://100.103.181.103:80, status code 504: dialing failed false: net/http: timeout awaiting response headers, remote host: 54.171.56.232, request: \"POST /action HTTP/1.1\", user agent: \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0\""
```
when visited the documentation: https://opensource.zalando.com/skipper/operation/operation/#connection-options I could no longer find the: `-response-header-timeout-backend` however I've found the: `-timeout-backend` which I've set to `5s` to check if it affects the timeout, unfortunately it doesn't have any affect, my config is:
```
- "skipper"
- "-kubernetes"
- "-kubernetes-in-cluster"
- "-address=:9999"
- "-proxy-preserve-host"
- "-serve-host-metrics"
- "-enable-ratelimits"
- "-experimental-upgrade"
- "-metrics-exp-decay-sample"
- "-lb-healthcheck-interval=3s"
- "-metrics-flavour=codahale,prometheus"
- "-enable-connection-metrics"
- "-timeout-backend=5s"
```

using the: `registry.opensource.zalan.do/pathfinder/skipper:latest` image.

Any idea what config shall I tweak to change the back-end timeout?

**Comment by tomekit** [comment]
Facing similar issue:
```
[APP]time="2021-03-29T16:44:23Z" level=error msg="net.Error during backend roundtrip to http://100.103.181.103:80: timeout=true temporary=true: net/http: timeout awaiting response headers"
[APP]time="2021-03-29T16:44:23Z" level=error msg="error while proxying after 1m0.021587566s, route kube_default__app_ingress__demo_app_net_____app_web with backend network http://100.103.181.103:80, status code 504: dialing failed false: net/http: timeout awaiting response headers, remote host: 54.171.56.232, request: \"POST /action HTTP/1.1\", user agent: \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0\""
```
when visited the documentation: https://opensource.zalando.com/skipper/operation/operation/#connection-options I could no longer find the: `-response-header-timeout-backend` however I've found the: `-timeout-backend` which I've set to `5s` to check if it affects the timeout, unfortunately it doesn't have any affect, my config is:
```
- "skipper"
- "-kubernetes"
- "-kubernetes-in-cluster"
- "-address=:9999"
- "-proxy-preserve-host"
- "-serve-host-metrics"
- "-enable-ratelimits"
- "-experimental-upgrade"
- "-metrics-exp-decay-sample"
- "-lb-healthcheck-interval=3s"
- "-metrics-flavour=codahale,prometheus"
- "-enable-connection-metrics"
- "-timeout-backend=5s"
```

using the: `registry.opensource.zalan.do/pathfinder/skipper:latest` image.

Any idea what config shall I tweak to change the back-end timeout?

**Comment by AlexanderYastrebov** [comment]
> Any idea what config shall I tweak to change the back-end timeout?

Try also looking at all available options via `skipper -h`
