### ISSUE TITLE
Vulnerability - [tech-security@zalando.de ] report

### ISSUE THREAD

**Issue by unl1k3ly** [zalando/skipper#1208]
I can't report a security vulnerability using `tech-security@zalando.de`  as per policy. Email is bouncing back. How can I email this about ?

**Comment by szuecs** [comment]
Sorry to see, that this e-mail is bouncing. Thanks for letting us know! 
Let me figure out which e-mail we can use.

**Comment by szuecs** [comment]
Please share your findings via this form: https://corporate.zalando.com/en/services-and-contact#security-form

**Comment by szuecs** [comment]
We fixed also the https://github.com/zalando/skipper/blob/master/SECURITY.md

**Comment by unl1k3ly** [comment]
Done!  Just sent the information I wanted. It could be a false positive, hence I'm checking directly to you. 

Thank you so much.

We can close this one for now.

Cheers

**Comment by aryszka** [comment]
Thanks a lot for reporting it!
