### ISSUE TITLE
clientRatelimit filter could be avoided by supplying X-Forwarded-For header value

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/skipper#1226]
`clientRatelimit` filter works by counting requests per first `X-Forwarded-For` header value:

https://github.com/zalando/skipper/blob/0c034b77029a9258a447ff070798190c55bc9abc/ratelimit/registry.go#L117-L122

https://github.com/zalando/skipper/blob/0c034b77029a9258a447ff070798190c55bc9abc/net/net.go#L34-L37

therefore if `X-Forwarded-For` header is present on incoming request its value would be used which allows client to bypass rate limit filter by providing random value.

Related to https://github.com/zalando/skipper/issues/629

**Comment by AlexanderYastrebov** [comment]
The complimentary attack would be malicious client supplying `X-Forwarded-For` IP of legitimate client thus causing Denial Of Service.

**Comment by szuecs** [comment]
These are of course not news, because it's the only way of doing clientratelimit by client IPs, if you maybe have a reverse proxy in front. 
You can also use Tuple matches to filter out malicious traffic. There is no need to use X-Forwarded-For header based clientRatelimit, it's just the default.
