### ISSUE TITLE
Move config code of Skipper into its own package

### ISSUE THREAD

**Issue by wndhydrnt** [zalando/skipper#1230]
**Is your feature request related to a problem? Please describe.**
We are adding some custom filters to Skipper. To be able to do this, we are using Skipper as a library. We copy the files in [cmd/skipper](https://github.com/zalando/skipper/tree/master/cmd/skipper) into our project each time we update the version of Skipper. This is done to have all flags available and set their proper default values.
Copying the files requires manual work and is prone to errors.

**Describe the solution you would like**
With the refactoring released in v0.11.1, all options/flags are hidden behind a nice API (`NewConfig()`, `Config.Parse()` and `Config.ToOptions()`). However, when using Skipper as a library we cannot make use of that API because it is defined in package `main` and that is not importable:
```
import "github.com/zalando/skipper/cmd/skipper" is a program, not an importable package
```
It would be perfect for us if all config-related code would be moved into its own package that can be imported.

**Describe alternatives you've considered (optional)**
Can't think of any suitable alternative right now.

**Additional context (optional)**
/

**Would you like to work on it?**
Yes

**Comment by szuecs** [comment]
Sounds good, happy to read the PR.
