### ISSUE TITLE
Skipper Helm Chart

### ISSUE THREAD

**Issue by kolbis** [zalando/skipper#1233]
Is there anyone which already created a production ready helm chart for skipper?
If so, can you please share it?

**Comment by szuecs** [comment]
We don’t like helm and probably all of them in the internet are outdated.

https://github.com/zalando-incubator/kubernetes-on-aws/tree/dev/cluster/manifests/skipper has all manifests that you need to build a production setup. It’s used in >140 clusters.

**Comment by kolbis** [comment]
I appreciate the answer.
Just out of curiosity, why dont you like helm?

**Comment by szuecs** [comment]
Tiller is known to be unsafe.
I don’t like, if I have a templated mess that I can’t easily understand.
Plain manifests with a little template to replace numbers of CPUs or memory is much easier.
I understand that helm is good for, just trying something, but you could also provide a directory that has some yaml files which you can deploy with `kubectl create -f dir`. Maybe something that can help. What do you think?

**Comment by kolbis** [comment]
I understand your point. That said, I think it has many benefits which overcome the downfalls such as "hard to read templating engine".
For us, microservice may have dependency in redis, elastic, mssql and etc.
Coordinating such a deployment is easier with helm as you are reusing charts. 

I think supporting helm for skipper would be a nice add-on.

**Comment by szuecs** [comment]
@kolbis I wrote documentation. Would you mind checking if this helps you in order to get faster started?

**Comment by szuecs** [comment]
It's now available at https://opensource.zalando.com/skipper/kubernetes/ingress-controller/#install-skipper-as-ingress-controller

**Comment by kolbis** [comment]
Thanks!
I will have a look.
If we will decide to create a chart, we will open source it.
I Will update

**Comment by szuecs** [comment]
If you like create a doc PR, maybe someone find it useful, too

**Comment by szuecs** [comment]
I had a discussion about helm v3 an @shaunzie (?) convinced me that it makes sense to create an official helm chart to simplify testing the ingress stack.
We can have some knobs to change to make sure you can easily test a simple setup and one with all batteries included.
