### ISSUE TITLE
Response caching

### ISSUE THREAD

**Issue by manson** [zalando/skipper#1258]
Some services generates rarely changing data (RSS feeds) sometimes static assets (images). The last one the front caching service may process (nginx for example). But the first one is a bit complicated situation as it can provide Cache headers and we can lay on it, but some may not provide such info but we might be knowing that we can bravely cache responses for a couple of seconds for such an endpoints. I didn't find the control of this on skipper. Trying more dumb  proxy-services for a such endpoints I had rises responsiveness up to 10x times on high loads. Just because of quite slow endpoins data generation, slow data change but caching it on proxy side. Is it possible to do like this in skipper or I have missed something?

**Comment by szuecs** [comment]
We have https://github.com/zalando/skipper/issues/628 and https://github.com/zalando/skipper/issues/956 as issues, but did not touched it yet. So, right now not possible.
Do you want to keep it open?
Do you want to work on it?

Right now I do not have an internal use case requested for this and I have no personal need for it, too. I would happy to review contributed PRs and guide you through the code if you have questions.
Check also our [development tutorial](https://opensource.zalando.com/skipper/tutorials/development/#filters), it shows a [PR for a non trivial filter](https://opensource.zalando.com/skipper/reference/development/)

**Comment by manson** [comment]
Thanks for reply. I'm in process of investigating the field of reverse-proxies, searching for a balance between speed, configuration and usage simplicity, amount of features it has. This project is almost ideal for me in a specified conditions except of caching. I have some more proxies not touched yet so after them I'll make a decision if it worth spending time to implement missing features in this project. Anyway thanks a lot for your attention and for a given issues you mentioned - I've missed'em.

**Comment by szuecs** [comment]
@manson thanks for considering skipper, let us know what you miss and why you choose something else. This would be really great feedback!
