### ISSUE TITLE
skipper ingress pod failed request error

### ISSUE THREAD

**Issue by jessi3mae20** [zalando/skipper#1264]
Having installed skipper and the aws-controller via helm, my skipper ingress pod fails to be ready with the following error:

"GET /kube-system/healthz HTTP/1.1" 404 10 "-" "kube-probe/1.14+" 0 10.95.109.110:9999 - -
[APP]time="2020-01-07T10:54:42Z" level=error msg="failed to load all: request failed, status: 403, 403 Forbidden"
[APP]time="2020-01-07T10:54:42Z" level=error msg="error while receiveing initial data;request failed, status: 403, 403 Forbidden"

I have tried to find some more detailed error messages/api calls to look at but haven't been able to. I am fairly new the Kubernetes so could be missing something obvious. Any guidance appreciated!

**Comment by szuecs** [comment]
@jessi3mae20 can you point me to the helm chart you used?
We are not maintaining any helm charts and I think it's more easy to just use the deployment.yaml or daemonset.yaml, instead of helm.
Maybe you can post your skipper-ingress deployment, such that we can check what's wrong.

**Comment by MarcusNoble** [comment]
Hey @szuecs, it's a Helm chart built internally that bundles kube-ingress-aws and external-dns together which we've been using on a few other clusters without issue. 

It looks like we've been using an old version of skipper previously (`v0.10.126`) and our chart has since been updated to `v0.11.1`. I'm going to go look at what changes were made between 0.10 and 0.11 that we haven't accounted for (unless you know off the top of your head?).

**Comment by szuecs** [comment]
@MarcusNoble I think we wrote the changes you have to do in the v0.11.1 release note or the last v0.10 release

**Comment by MarcusNoble** [comment]
Looking at some older 0.10 versions it looks like the same issue also exists (confirmed by changing the version in one of our working clusters using v0.10.126).

I've just been looking at https://github.com/zalando-incubator/kubernetes-on-aws/blob/stable/cluster/manifests/skipper/deployment.yaml to see what we might be missing (there's a lot of arguments I'm going to need to work through and see if we need) but I did spot the `securityContext` specified which we don't have. Do you know if that is a requirement that was brought in during 0.10 at some point?

**Comment by szuecs** [comment]
securityContext only disallows things, so it would not break if you do not specify them.
https://github.com/zalando-incubator/kubernetes-on-aws/blob/stable/cluster/manifests/skipper/deployment.yaml#L128-L131

**Comment by szuecs** [comment]
The most important flags for Kubernetes are:
```
  "containers": [
    {
      "args": [
        "skipper",
        "-kubernetes",
        "-kubernetes-in-cluster",
        "-kubernetes-path-mode=path-prefix",
        "-address=:9999",
        "-wait-first-route-load",
```

You need to understand why you get the health check with 404.
I think you should check the support-listener, default to 9911 and check `/routes`: https://opensource.zalando.com/skipper/operation/operation/#routing-table-information

**Comment by MarcusNoble** [comment]
Figured it out. Turns out I'd missed this change: https://github.com/zalando/skipper/releases/tag/v0.10.177 🤦‍♂

**Comment by MarcusNoble** [comment]
@jessi3mae20 I'll get out chart updated now. Do you want to close this issue? 😄 

Thanks for your help @szuecs

**Comment by jessi3mae20** [comment]
Thanks @szuecs and @MarcusNoble !
