### ISSUE TITLE
TCP lifo accept rate can be reported as negative in metrics

### ISSUE THREAD

**Issue by mikkeloscar** [zalando/skipper#1269]
**Describe the bug**
TCP lifo accepted connection metric becomes negative after connections were en queued.

While investigating an incident I found this metric:

Rate of queued connections

![image](https://user-images.githubusercontent.com/128566/72169511-89b7ea80-33cf-11ea-85c0-ea2c4db9a666.png)

And when looking at accepted connections for the same time frame I see that it start to be negative after the spike of queuing happened:

![image](https://user-images.githubusercontent.com/128566/72169585-b3711180-33cf-11ea-9bed-f2c1ae678605.png)

(The red graph)

It seems like there is some calculation error in the metric.

**Comment by szuecs** [comment]
Clarified internally. Because we use gauge for the queue metrics, you can not use `rate()`.

**Comment by mikkeloscar** [comment]
What confused me was the naming "accepted connections" which made me think it was a counter.
