### ISSUE TITLE
Customisable Rate Limiter

### ISSUE THREAD

**Issue by dlmiddlecote** [zalando/skipper#1270]
**Is your feature request related to a problem? Please describe.**
I’d like to have different rate limits for different users on the same route, where a user would be identified by a header, and the user defines the rate limit count and period, which themselves could be headers.

**Describe the solution you would like**
Something along the lines of the `clusterClientRatelimit` filter, but without the static rate. 
Instead of `clusterClientRatelimit("group", 2000, "1h", "X-ID")` maybe something like `filter("group", 2000, "1h", "X-Ratelimit-Count", "X-Ratelimit-Period", "X-ID")`, where you'd be able to define headers to check what the ratelimit count and period is for the given request, and defaults otherwise.

**Describe alternatives you've considered (optional)**
Creating multiple routes, such as:
```
auth: Path("/foo")
      -> webhook("url", "X-ID,X-Ratelimit-Count,X-Ratelimit-Period")
      -> <loopback>;
user2000: Path("/foo")
          && HeaderRegexp("X-ID", "^.*$")
          && Header("X-Ratelimit-Count", "2000")
          && Header("X-Ratelimit-Period", "1h")
          -> dropResonseHeader("X-ID")
          -> dropResonseHeader("X-Ratelimit-Count")
          -> dropResonseHeader("X-Ratelimit-Period")
          -> clusterClientRatelimit("group", 2000, "1h", "X-ID")
          -> "backend";
user1000: Path("/foo")
          && HeaderRegexp("X-ID", "^.*$")
          && Header("X-Ratelimit-Count", "1000")
          && Header("X-Ratelimit-Period", "1h")
          -> dropResonseHeader("X-ID")
          -> dropResonseHeader("X-Ratelimit-Count")
          -> dropResonseHeader("X-Ratelimit-Period")
          -> clusterClientRatelimit("group", 1000, "1h", "X-ID")
          -> "backend";
default: Path("/foo")
         && HeaderRegexp("X-ID", "^.*$")
         && HeaderRegexp("X-Ratelimit-Count", "^.*$")
         && HeaderRegexp("X-Ratelimit-Period", "^.*$")
         -> dropResonseHeader("X-ID")
         -> dropResonseHeader("X-Ratelimit-Count")
         -> dropResonseHeader("X-Ratelimit-Period")
         -> clusterClientRatelimit("group", 500, "1h", "X-ID")
         -> "backend";
```

**Additional context (optional)**

I want to make sure that you couldn't get to `/foo`, as described above, without passing through `webhook` successfully, and due to the above workaround, this could, possibly, be bypassed. This is also a lot of predicates/filters due to the requirement of `<loopback>`, which could become unmaintainable for lots of routes.

**Would you like to work on it?**
Yes, but would like some direction first. There could also be a solution to write a customer filter if this is not something that is wanted in the main codebase.

**Comment by szuecs** [comment]
Thanks for creating the issue!
For my understanding, `filter("group", 2000, "1h", "X-Ratelimit-Count", "X-Ratelimit-Period", "X-ID")` would allow 2000/h, if none of the headers `X-Ratelimit-Count` or `X-Ratelimit-Period` are provided. Each header can override the specific setting.

Do I understand the idea correctly?

**Comment by dlmiddlecote** [comment]
Hey! Yeah, that’s correct ☺️

**Comment by dlmiddlecote** [comment]
I also wonder whether adding the above routes will work in the `zalando.org/skipper-routes` Kubernetes Ingress annotations.

**Comment by szuecs** [comment]
@dlmiddlecote yes it should work, but of course test in a test cluster, to understand the outcome of `zalando.org/skipper-routes`. The custom routes specified like that will get all predicates and filters from the "main" ingress definition, such that you can not create arbitrary overlapping routes and catch requests from other ingresses.
A better way to specify complex routes via kubernetes, will be routegroup crd https://github.com/zalando/skipper/pull/1180. We hope to get it soon.

**Comment by szuecs** [comment]
This can be done since a while with routegroups see also https://opensource.zalando.com/skipper/kubernetes/routegroup-crd/ and https://opensource.zalando.com/skipper/kubernetes/routegroups/
