### ISSUE TITLE
Help Requested with Inconsistent Filter Behavior

### ISSUE THREAD

**Issue by justinrcs** [zalando/skipper#1273]
Running Skipper as the Ingress Controller in eight separate Kubernetes clusters. In one of the clusters, deployed in AWS us-west-2 region, seeing inconsistent behavior with ingress filters. Requesting some help how to troubleshoot what could be the issue:

- Currently running Skipper v0.11.23 as a Daemonset.
- Pod has 2 separate Ingresses:
 Ingress 1 Uses host: app.dev2.domain and filter: secureOauthTokenintrospectionAnyKV filter to validate Oauth Token
Ingress 2 Uses host: api-app.dev2.domain and filter: webhook to validate a client certificate that is passed in via header

Ingress 1 is used by users who authenticate against an identity provider
Ingress 2 is used by applications that are issued a client certificate.

Both Ingresses route to the same application and work as expected in 7 out of the 8 clusters.

In the problem cluster, the same request with the same headers will randomly return a 401 unauthorized or a 200. Both ingress routes exhibit the behavior. Approximately 3/4 requests return the 401. 

When the 401 is returned, a Www-Authenticate header is returned. This looks like it's coming from the Oauth provider.

**Comment by szuecs** [comment]
Do I understand correctly, that you think applications with client cert auth are routed to the identity provider?

This sounds like you have routes that interfere with each other. 
In your issue you wrote that you 2 different host definitions, which will make it impossible to interfere.
I would start to dump the routes and look at them: https://opensource.zalando.com/skipper/operation/operation/#routing-table-information

If you need more help, please add information like ingress configuration, route table entries and output of a `curl -v` showing the error and access logs for the requests would be helpful.

**Comment by justinrcs** [comment]
That's what the behavior seemed to demonstrate. However, today I am unable to reproduce the error. I did dump the routes to see if they were somehow interfering with one another but they looked properly configured. 

Thanks for the response, I'll close the ticket and keep an eye on things. If it comes up again I'll gather more diagnostic info.
