### ISSUE TITLE
Remove the experimental status of `setPath` template operations

### ISSUE THREAD

**Issue by oporkka** [zalando/skipper#1275]
**Is your feature request related to a problem? Please describe.**
The documentation of setPath states that applying template operations in the value
is experimental. The feature has been there  for 3 years now (https://github.com/zalando/skipper/blame/fadf7fe361a05d5c4823b948360c176737cf8f87/filters/builtin/path.go#L33),
and probably tested enough in production to be non-experimental.

**Describe the solution you would like**
Remove the mention of experimental status from the comments.

**Would you like to work on it?**
Yes

**Comment by AlexanderYastrebov** [comment]
Fixed within #1528
