### ISSUE TITLE
[Kubernetes] Refresh Service Account token before it expires

### ISSUE THREAD

**Issue by linki** [zalando/skipper#1277]
**Is your feature request related to a problem? Please describe.**

We would like to transition to issuing ServiceAccount tokens that expire, aka [BoundServiceAccountTokenVolumes](https://github.com/kubernetes/kubernetes/issues/70679).

Skipper's Kubernetes data client is currently not aware that ServiceAccount tokens can expire and therefore only reads the token once when the client is initialized. (e.g. [here](https://github.com/zalando/skipper/blob/v0.11.26/dataclients/kubernetes/kube.go#L250) and [here](https://github.com/zalando/skipper/blob/v0.11.26/swarm/kubernetes.go#L108))

We would like for skipper to refresh the token from the mounted volume so that it always has a valid token.

**Describe the solution you would like**

The token should be re-read from the mounted volume while skipper is running. The path to the token within the container doesn't change. This can either be done in fixed intervals or by taking the expiry time within the token into account.

Looking at Kubernetes' TokenManager itself [it refreshes tokens](https://github.com/kubernetes/kubernetes/blob/v1.18.0-alpha.1/pkg/kubelet/token/token_manager.go#L167-L184) once they are past 80% of their lifetime or at least once per day. The default validity of ServiceAccount tokens is 1h so in practice they will be rotated once per hour.

**Describe alternatives you've considered (optional)**

We could use [client-go](https://github.com/kubernetes/client-go) for talking to the Kubernetes API (or a suitable subpackage). Token refresh is handled within the client automatically and it might have other benefits (or drawbacks).

**Would you like to work on it?**

Yes

**Comment by szuecs** [comment]
Sounds good, but we don’t like client-go.
We have already a [secrets module](https://godoc.org/github.com/zalando/skipper/secrets) which you can use to read and update secrets.
I also work on providing an http client in a branch https://github.com/zalando/skipper/blob/feature/skipper-http-client/net/httpclient.go that should also use the secrets module and you can use this client to replace the current kubernetes dataclient http client.

**Comment by linki** [comment]
Thanks, I'll take a look.

**Comment by linki** [comment]
Duplicate https://github.com/zalando/skipper/issues/1283
