### ISSUE TITLE
Error while checking known resource types: resource not found

### ISSUE THREAD

**Issue by universam1** [zalando/skipper#1297]
**Describe the bug**
Errors flooding the logs:
```
[APP]time="2020-02-07T12:18:35Z" level=error msg="Error while checking known resource types: resource not found."                                                                                                     │
[APP]time="2020-02-07T12:18:38Z" level=error msg="Error while checking known resource types: resource not found."
...
```

Possibly related to #1180

**To Reproduce**
Looking into sources, probably happening at cluster where no `RouteGroups` are used or defined

**Expected behavior**
No errors logged

**Observed behavior**
logs flooded

**Comment by universam1** [comment]
FYI @szuecs

**Comment by szuecs** [comment]
@universam1 sorry for the inconvenience we fixed it in https://github.com/zalando/skipper/pull/1300 and released the fix in >= https://github.com/zalando/skipper/releases/tag/v0.11.40
