### ISSUE TITLE
Routes using tee() combined with <shunt> cause an increase in goroutines

### ISSUE THREAD

**Issue by topicus** [zalando/skipper#1310]
**Describe the bug**
Bodies of tee'd requests are not cleaned up when shunting responses. This causes the following goroutine to being executed indefinitely https://github.com/zalando/skipper/blob/master/filters/tee/tee.go#L155-L169

**To Reproduce**
1. route or ingress definition:
```
example_route: *
   -> tee("http://localhost:8080")
   -> <shunt>;
```
2. request with a body
```
curl -d "{}" http://localhost:9990/
```
3. response with headers 
Depending on how strict is the backend configuration the request may fail or succeed. However, this does not affect the leaking behavior.

**Expected behavior**
Body of tee'd requests should be closed. This will avoid the increase in the goroutines.

**Observed behavior**
The body of the tee'd request is never closed causing a memory leak and depending on the traffic to the route, this can lead to goroutines' spike. This could lead to skipper crashing.

**Comment by szuecs** [comment]
@topicus thanks for the issue, we could reproduce it. Problem is that `<shunt>` does not read the body and `tee()` filter use a Pipe to read the body when the the backend processes the request body.

**Comment by aryszka** [comment]
Fixed in: https://github.com/zalando/skipper/pull/1314
