### ISSUE TITLE
version output for the skipper and eskip commands

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#132]

**Comment by LappleApple** [comment]
Can you provide some quick details about what this is going to do? A sentence = fine.

**Comment by lmineiro** [comment]
Both binaries should be versioned and we should keep a proper changelog to inform users of the changes.

I suggest something as simple as [SemVer](http://semver.org) for both but this forces us to establish a well defined release process

**Comment by szuecs** [comment]
We use GH releases: https://github.com/zalando/skipper/releases

Binary version output
```
% make skipper
mkdir -p bin
GO111MODULE=on go build -ldflags "-X main.version=v0.10.202 -X main.commit=875e439" -o bin/skipper ./cmd/skipper/*.go
% make eskip
mkdir -p bin
GO111MODULE=on go build -ldflags "-X main.version=v0.10.202 -X main.commit=875e439" -o bin/eskip ./cmd/eskip/*.go
% ./bin/skipper -version
Skipper version v0.10.202 (commit: 875e439)
% ./bin/eskip version
eskip version v0.10.202 (commit: 875e439)
```
