### ISSUE TITLE
Using regex delimiter fails in character list in eskip

### ISSUE THREAD

**Issue by grassator** [zalando/skipper#134]
This should work

``` js
PathRegexp(/[/]/)
```

but it fails in eskip

**Comment by LappleApple** [comment]
@mo-gr @grassator @aryszka Should I add a "Help Wanted" label to this, or were one of you guys going to do this at some point?

**Comment by MALPI** [comment]
Can this one be closed?

**Comment by szuecs** [comment]
yes
