### ISSUE TITLE
Custom response body for auth reject response

### ISSUE THREAD

**Issue by grassator** [zalando/skipper#1355]
**Is your feature request related to a problem? Please describe.**
Currently if you use [auth](https://github.com/zalando/skipper/blob/cce10ed4a000ee627df5d7988b658745505d41a9/filters/auth/auth.go) filters, you end up with a 401 response and an empty page. This ok in most situation, but in a user facing scenario, or when protecting an endpoint whose clients expect a JSON response this can cause issues.

**Describe the solution you would like**
The most simple implementation would allow to specify a string (template?) for the response in [filter options](https://github.com/zalando/skipper/blob/cce10ed4a000ee627df5d7988b658745505d41a9/filters/auth/tokeninfo.go#L21-L26). Potentially might be great to have another filter like `oauthOnRejectedResponseBody('{"error": "Not Allowed"}')` so that the response can be set per-route.

**Describe alternatives you've considered (optional)**
Can not think of any.

**Would you like to work on it?**
Maybe, but no time

**Comment by szuecs** [comment]
@grassator I don't understand what the benefit is.
401 is `not allowed` so why does a json body help?
Clients should be able to react and show meaningful errors to users with a 401 response.

**Comment by aryszka** [comment]
i can rather imagine a filter similar to the inlineContent() but one that is conditional. E.g, a route could look like:

```
* -> contentIfStatus(401, "{\"error\": \"Not Allowed\"}") -> oauthXX() -> "https://www.example.org"
```

where the error object would be returned as the response only if the status is 401.

One advantage of this is that this way we don't overload too much the auth functionality, and the other advantage is that it can be used in a more generic way, e.g. for a common 404 page:

```
* -> contentIfStatus(404, "<p class\"error\">Not found, that's all we know.</p>") -> oauthXX() -> "https://www.example.org"
```

A third advantage is that this filter would also allow to explicitly set the content type explicitly, while having that argument  in the oauth filters would start to become really too much:

```
 contentIfStatus(401, "{\"error\": \"Not Allowed\"}", "application/json")
```

@szuecs , @grassator WDYT?

**Comment by grassator** [comment]
@aryszka I really like your suggestion! It is way more general and fits the use case properly.

@szuecs To provide more context on the main setup I'm considering:

1. Browser contacts an edge server for an HTML / JSON payload with explicit `Accept: text/html` / `Accept: application/json` respectively
1. Edge server transforms user session into an auth token for internal requests and routes it to a service protected by Skipper with auth filter
1. If the filter fails for HTML page the user is presented with unbranded ugly "Not allowed" text instead of a website. If the filter fails for JSON request, then the server did not fulfill the contract of `Accept` header and returned a non-JSON response.

Suggestion from Arpad fixes both use cases beautifully.

**Comment by szuecs** [comment]
@aryszka sounds good!
@grassator good to have the context, thanks!
