### ISSUE TITLE
skipper ingress controller vs kube ingress aws controller

### ISSUE THREAD

**Issue by samuelthan** [zalando/skipper#1381]
In reference to https://opensource.zalando.com/skipper/kubernetes/ingress-controller/, there seems to be no mention of the comparison between skipper ingress controller vs [kube ingress aws controller](https://github.com/zalando-incubator/kube-ingress-aws-controller)

When should i choose to use skipper ingress controller vs kube ingress aws controller ? 

thanks

**Comment by aryszka** [comment]
Thanks for your question!

We may need to clarify this better in our documentation. Skipper and kube-ingress-aws-controller are not alternatives but they complement each other.

Skipper is only a proxy and basically just executes the routing described by the ingress specifications. (It can be used outside of Kubernetes, as well.) It listens on the configured address on the nodes and forwards the requests to the pod endpoints in the cluster's internal network.

Kube-ingress-aws-controller controls the load balancers in front of the nodes of a cluster. To distribute the incoming traffic to the Skipper proxies listening on the nodes, you can use the AWS load balancers. It is also a good idea to do the TLS termination on the load balancer level. Kube-ingress-aws-controller can keep the configuration of the LB up to date, based on the ingress specifications.

So you can use the two together at the same time.

I also recommend to check [External DNS](https://github.com/kubernetes-sigs/external-dns) which automates the DNS configuration.

The three can work really nice together ;)

**Comment by szuecs** [comment]
Closing to cleanup our issues
