### ISSUE TITLE
Support ingress without http path to prevent "invalid ingress item: rule missing http definitions" warning

### ISSUE THREAD

**Issue by ruudk** [zalando/skipper#1417]
I want to serve some `inlineContent` based on predicate `Header("Trigger", "true")` for some domains. 

I do this with:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    annotations:
        zalando.org/skipper-routes: |
            Header("Trigger", "true")
            -> inlineContent("Hello, World!")
            -> status(200)
            -> <shunt>
    name: my-ingress
    namespace: my-namespace
spec:
    rules:
        -   host: www.domain.com
        -   host: www.domain.nl
```

Kubernetes accepts this input and `kube-ingress-aws-controller` will provide a loadbalancer for it.

But Skipper ignores it and gives a warning:
```
level=warning msg="invalid ingress item: rule missing http definitions" ingress=my-namespace/my-ingress
```

In order to let Skipper accept it, I need to write it like this:
```diff
  apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
     annotations:
         zalando.org/skipper-routes: |
             Header("Trigger", "true")
             -> inlineContent("Hello, World!")
             -> status(200)
             -> <shunt>
     name: my-ingress
     namespace: my-namespace
 spec:
     rules:
         -   host: www.domain.com
+            http:
+                paths:
+                    -   backend:
+                            serviceName: my-service
+                            servicePort: 1234
         -   host: www.domain.nl
+            http:
+                paths:
+                    -   backend:
+                            serviceName: my-service
+                            servicePort: 1234
```

Skipper will accept it, but it will create the following routes:
```
kube_my_namespace__my_ingress__0__www_domain_com____: Host(/^www[.]domain[.]com$/) && Header("Trigger", "true")
  -> inlineContent("Hello, World!")
  -> status(200)
  -> <shunt>;
kube_my_namespace__my_ingress__0__www_domain_nl____: Host(/^www[.]domain[.]nl$/) && Header("Trigger", "true")
  -> inlineContent("Hello, World!")
  -> status(200)
  -> <shunt>;
kube_my_namespace__my_ingress__www_domain_com____my_service: Host(/^www[.]domain[.]com$/)
  -> <roundRobin, "http://xxx:80">;
kube_my_namespace__my_ingress__www_domain_nl____my_service: Host(/^www[.]domain[.]nl$/)
  -> <roundRobin, "http://xxx:80">;
```

I get that it does this, but it's not what I want. I don't want it to generate any routes except my static routes.

So I could add a `zalando.org/skipper-predicate: Header("SomeHeaderThatNeverIsUsed")` to make sure that those routes are never invoked, but that's super ugly.

## Solution

Skipper should not fail on `invalid ingress item: rule missing http definitions` and just ignore it. In that case, the Ingress doesn't do much, and you can still use the `zalando.org/skipper-routes` annotation to set-up routes.

**Comment by szuecs** [comment]
Please use RouteGroup for this case.

**Comment by ruudk** [comment]
Not sure if that's possible, because:
https://github.com/zalando/skipper/blob/a192a7dec3fa08e73f60a921d5bf27b2b61abcab/dataclients/kubernetes/deploy/apply/routegroups_crd.yaml#L34-L36
https://github.com/zalando/skipper/blob/a192a7dec3fa08e73f60a921d5bf27b2b61abcab/dataclients/kubernetes/deploy/apply/routegroups_crd.yaml#L42-L44

So that means that you need to specify backends always?

**Comment by szuecs** [comment]
You can use shunt as backend which is what you want or I completely miss understood your goal.

**Comment by ruudk** [comment]
@szuecs You're right. 

```yaml
apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
    name: ruud-test
spec:
    backends:
        -   name: shunt
            type: shunt
    routes:
        -   host: ruud.domain.tld
            pathSubtree: /hello
            filters:
                - inlineContent("Hello, World!")
            backends:
                - backendName: shunt
```

creates the following routes:
```eskip
kube_rg__frontend__ruud_test__all__0_0: PathSubtree("/hello")
  -> inlineContent("Hello, World!")
  -> <shunt>;

kube_rg__frontend__ruud_test__all__0_0_https_redirect: Header("X-Forwarded-Proto", "http") && PathSubtree("/hello")
  -> inlineContent("Hello, World!")
  -> redirectTo(308, "https:")
  -> <shunt>;
```

But when I change it to
```yaml
apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
    name: ruud-test
spec:
    hosts:
        - ruud.domain.tld
    backends:
        -   name: shunt
            type: shunt
    routes:
        -   pathSubtree: /hello
            filters:
                - inlineContent("Hello, World!")
            backends:
                - backendName: shunt
```

I somehow get this dangerous catch-all:
```eskip
kube_rg____ruud_domain_tld__catchall__0_0: Host(/^(ruud[.]domain[.]tld)$/)
  -> <shunt>;

kube_rg__frontend__ruud_test__all__0_0: Host(/^(ruud[.]domain[.]tld)$/) && PathSubtree("/hello")
  -> inlineContent("Hello, World!")
  -> <shunt>;

kube_rg__frontend__ruud_test__all__0_0_https_redirect: Host(/^(ruud[.]domain[.]tld)$/) && Header("X-Forwarded-Proto", "http") && PathSubtree("/hello")
  -> inlineContent("Hello, World!")
  -> redirectTo(308, "https:")
  -> <shunt>;
```

Why does it insist on creating this catch-all?

**Comment by szuecs** [comment]
I think it’s ported how ingress behaves in skipper. It was a safety reason. You can specify all routes for the given host in this RouteGroup if it’s possible in your case. You could even use status(404) -> <shunt> to reply similar to route not found.

The https redirect has also the filter applied, not sure if this should be done.
Wdyt @aryszka?

**Comment by ruudk** [comment]
> I think it’s ported how ingress behaves in skipper. It was a safety reason. You can specify all routes for the given host in this RouteGroup if it’s possible in your case. You could even use status(404) -> to reply similar to route not found.

That doesn't work for me. I want to mix Ingress and RouteGroups. That means that my Ingress-es already have the hosts defined. I just want to introduce some new special routes via RouteGroups. But that catch-all scares me because I think it can conflict with the routes that are set-up via Ingress. 

What is the `safety reason`?

**Comment by szuecs** [comment]
Good question, I don’t remember (I also didn’t find the issue that could explain it. 
I think with RouteGroup all of this changed again and we have to consider ingress and RouteGroup can be mixed.
Maybe we can create a flag to disable the Catchall route creation. We might be able to drop the flag on the v1 branch.
Wdyt?

**Comment by aryszka** [comment]
The "safety" is not actually a safety. The reason is that skipper by default, when no route is found returns 404. It was decided that this is not the best in the role as Kubernetes ingress, I don't remember why. So when no route is found, then skipper ingress returns the a configured default status code, 5xx something. But then if there is a valid ingress that handles only requests with a specific path, or some other predicates, and a request comes with a host name defined by this ingress, but doesn't match the other predicates, skipper ingress should return 404, and therefore a catch-all route is generated.

I think the main problem with this approach is that it was designed with a too specific "microservices" model in mind, and I see how it can cause problems in some use cases or when used together with route groups. Note that even the route groups are designed such that the hostnames "belong" to a route group, and if other route groups use the same host name, then there can be conflicts between them.

I would recommend now to port those routes that you have in ingress to the same route group, if that works for you.

Another workaround for this problem can be to explicitly handle that case that is currently the catchall route by defining something that yields: `Host("foo") && PathSubtree("/") -> <shunt>`
