### ISSUE TITLE
Skipper Gitops K8s Operator

### ISSUE THREAD

**Issue by kolbis** [zalando/skipper#1419]
I would like to store all skipper routes in a git repo and implement a GitOps process for managing skipper routes.
Once the routes are pushed into the repo, a k8s operator pull the changes and apply them to the cluster.

**Comment by aryszka** [comment]
Hi @kolbis ,

I think this should be possible. You need to implement the operator, that would generate ingress objects or [route groups](https://opensource.zalando.com/skipper/kubernetes/routegroups/), and would keep them up-to-date. Things to consider are: which details of the desired routes you'd like to store in a git repo, and which part should depend on the current state of the cluster, e.g. the available services/endpoints.

---

On aside: a somewhat similar feature can be of skipper to pull the routes directly from a git repo. In a generic, non-kubernetes, scenario, one would only need to implement a [routing.DataClient](https://godoc.org/github.com/zalando/skipper/routing#DataClient), using the desired format and parser, e.g. [eskip](https://godoc.org/github.com/zalando/skipper/eskip#Parse), and add the client to a custom build of skipper in CustomDataClients in [skipper.Options](https://godoc.org/github.com/zalando/skipper#Options). The disadvantage of this approach is, though, that it would not be aware of the state of a Kubernetes cluster.

**Comment by szuecs** [comment]
You can also use the etcd dataclient to store the routes and gitops script push’s to etcd.

**Comment by szuecs** [comment]
@kolbis If you think your suggestion is different please reopen and explain in more detail what the dataclient should provide.
Thanks
