### ISSUE TITLE
The flag -ratelimits doesn't accept cluster-based strategies

### ISSUE THREAD

**Issue by rafaellima** [zalando/skipper#1428]
**Is your feature request related to a problem? Please describe.**
I want to enable global rate-limiting (using Redis ring shards) by using the command line `-ratelimits` flag. Although cluster-based options are available in the implementation[1] and documentation[2], they can't be set via command line because there is a validation that accepts only one of the following options: (client/service/disabled)[3]. 

**Describe the solution you would like**
Add the missing implementations (`ClusterClientRatelimit` and `ClusterServiceRatelimit`) as valid options.

**Would you like to work on it?**
Yes.

1. https://github.com/zalando/skipper/blob/master/ratelimit/ratelimit.go#L121
2. https://godoc.org/github.com/zalando/skipper/ratelimit#hdr-Settings___Type
3. https://github.com/zalando/skipper/blob/master/config/ratelimiterflags.go#L47

**Comment by szuecs** [comment]
Sounds great!
