### ISSUE TITLE
Oauth2 OIDC return ID token as JWT

### ISSUE THREAD

**Issue by anchalkhandelwal** [zalando/skipper#1448]
I am using 'oauthOidcAllClaims' filter which return access_token as JWT and userinfo and claims. I also want it to return ID_token as JWT. Is this possible in the current set of filters?

**Comment by szuecs** [comment]
@anchalkhandelwal I am not sure.

Do you use https://opensource.zalando.com/skipper/reference/filters/#oidcclaimsquery to do authorization?

Did you check `Skipper-Oidc-Info` header in your backend?

**Comment by anchalkhandelwal** [comment]
Hello @szuecs 

I am using skipper filter ‘**oauthOidcUserInfo**’ to get the token and the claims. 
oauthOidcUserInfo("https://oidc-provider.example.com", "client_id", "client_secret",
    "http://target.example.com/subpath/callback", "email profile", 
    "name email picture") -> "https://internal.example.org";

This sets the cookie in my browser and Skipper sends to the backend the access token and claims in the header. Here the header parameter ‘Skipper-Oidc-Info’ looks like:
{
    "oauth2token": "xxx",
    "userInfo": {
        "sub": "sub",
        "profile": "prof",
        "email": "abc@example.com",
        "email_verified": "abc@example.com"
    },
    "subject": "subj"
}

Here the “oauth2token” contains: access_token, token_type and expiry. In the entire header in my backend I cannot get the encoded JWT ID Token. I need to send this token to my various microservices and clients, where they can decode and validate the token locally. If I try to validate access_token, that can only be done remotely by talking to my authorization server which adds network cost.
I am thinking of getting something like below in the header parameter ‘Skipper-Oidc-Info’:
{
    "oauth2token": "xxx",
    **"oidcidtoken": "xxx",**
    "userInfo": {
        "sub": "sub",
        "profile": "prof",
        "email": "abc@example.com",
        "email_verified": "abc@example.com"
    },
    "subject": "subj"
}

**I would prefer to make this enhancement directly in the filter.  Is this acceptable?  If not, what route would be acceptable to pass the encoded ID token to backends?**

**Comment by szuecs** [comment]
Sounds good to me.
Maybe @universam1 has some interest, too.

**Comment by universam1** [comment]
:+1: see a use case to support a logout from the application initiated. It the `tokenContainer struct` would be extended, that data would be also accessible for `setHeaders` automatically

**Comment by szuecs** [comment]
Cool thanks for your input @universam1 !
@anchalkhandelwal I think feel free to go for the change!

**Comment by AlexanderYastrebov** [comment]
Looks like it is implemented by #1468
