### ISSUE TITLE
Rename inlineContent filter to finallyInlineContent

### ISSUE THREAD

**Issue by burimshala** [zalando/skipper#1451]
**Is your feature request related to a problem? Please describe.**
There is no clear indication that this filter should be placed as the last one beside the documentation.

**Describe the solution you would like**
I want to make it obvious that this filter should be placed as the last filter which will be indicated by the finally keyword.

**Would you like to work on it?**
Yes, but no time

**Comment by szuecs** [comment]
I would prefer changing documentation, because if it is missing it will be ok and I don't think a rename would make it obvious.

**Comment by AlexanderYastrebov** [comment]
Generally to use a filter user consults documentation and [documentation for the `inlineContent`](https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#inlinecontent) states 
> !!! note inlineContent filter is special and must be the last in the filter chain.

IMO this should be closed to reduce backlog.

**Comment by szuecs** [comment]
@AlexanderYastrebov Yes thanks documentation was done
