### ISSUE TITLE
Support multiple ingress controllers with different routing requirements in RouteGroup

### ISSUE THREAD

**Issue by zoonage** [zalando/skipper#1452]
**Is your feature request related to a problem? Please describe.**
We would like to utilise two ingresses, one internal-only ingress for inter-cluster communication, and one external-only ingress for customer products. These require different routing logic to be applied depending on the ingress that it comes from

**Describe the solution you would like**
An ability to apply rules defined in RouteGroups to traffic from a specific ingress.

**Describe alternatives you've considered (optional)**

**Additional context (optional)**
Copy & pasted Slack message;

```
not yet. Please create an issue for that.
It should not be that complicated clusterclient.go line 280 is the ingress filtering 
and just below is the loadRouteGroups which should have a similar 
filtering in the for loop before we append the i into rgs.
```

**Would you like to work on it?**
Yes, but no time

**Comment by szuecs** [comment]
Thanks

**Comment by szuecs** [comment]
Basically filter by class similar to ingress to separate which skipper controller deployment is reading which routegroups.
