### ISSUE TITLE
Provide filters for pathParamToX()

### ISSUE THREAD

**Issue by LaseII** [zalando/skipper#1453]
**Is your feature request related to a problem? Please describe.**
I want to create a route where e.g a `responseHeader` can consume a route variable
This would enable us to create e.g a cookie value based on parameter.

**Describe the solution you would like**
```
// Set a cookie with PR Number
 rendering_engine_pr_set_cookie:
 Path("/rengine/enable-pr-cookie/:prId") &&
 Method("GET") &&
 HostRegexp("^.+[.]zalando[.].+$")
   -> setResponseHeader("Set-Cookie", "rendering-engine-pr=${prId}; Max-Age=36000; Secure")
   -> redirectTo(302, "/")
   -> <shunt>
```

**Would you like to work on it?**
no, no time and not enough experience with skipper yet.

**Comment by AlexanderYastrebov** [comment]
It is possible with lua scripting:
```
rendering_engine_pr_set_cookie:
Path("/rengine/enable-pr-cookie/:prId") 
-> lua("
function request(ctx, params)
    ctx.serve({
        status_code=302,
        header={
            ['Set-Cookie']='rendering-engine-pr=' .. ctx.path_param.prId .. '; Max-Age=36000; Secure',
            Location='/',
        },
    })
end
") -> <shunt>;
```

**Comment by szuecs** [comment]
I think we should do https://github.com/zalando/skipper/issues/1444 instead of this specific one as @AlexanderYastrebov suggested.

**Comment by AlexanderYastrebov** [comment]
@szuecs The described solution should work and is already [documented](https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#setresponseheader).

**Comment by szuecs** [comment]
@AlexanderYastrebov then I will close this issue. Please reopen if you think it's not done, but I want to have something what needs to be done in case it's not. Thanks!
