### ISSUE TITLE
kubernetes: Add support for new ingress resource field `pathType` added in Kubernetes v1.18

### ISSUE THREAD

**Issue by mikkeloscar** [zalando/skipper#1477]
Kubernetes v1.18 introduces changes to the Ingress resource: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#extending-ingress-with-and-replacing-a-deprecated-annotation-with-ingressclass

One of these changes is adding a `pathType` field to `ingress.spec.rules.http.paths.pathType` See relevant part of this [Ingress KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md#paths-proposal)

Skipper already has some support like this via the `zalando.org/skipper-ingress-path-mode` annotation, but it would make sense to support the new `pathType` field directly in the Ingress spec.

**Comment by szuecs** [comment]
SGTM

**Comment by szuecs** [comment]
https://github.com/zalando/skipper/pull/1892 implements v1 ingress with the new pathType and new kind and released in https://github.com/zalando/skipper/releases/tag/v0.13.149
