### ISSUE TITLE
RouteGroups spec.hosts field is inconsistent with documentation

### ISSUE THREAD

**Issue by brendanmaguire** [zalando/skipper#1505]
**Describe the bug**
The documentation indicates that the `spec.hosts` field is [optional](https://github.com/zalando/skipper/blob/master/docs/kubernetes/routegroup-crd.md#L18).

**Expected behavior**
Omitting the `spec.hosts` field should be valid.

**Observed behavior**
It is [actually required](https://github.com/zalando/skipper/blob/master/dataclients/kubernetes/deploy/apply/routegroups_crd.yaml#L38).

**Comment by aryszka** [comment]
Thanks! We'll look into this. Or in case you already checked how to fix it a PR is welcome, or we're also happy to discuss a suggestion on how to fix it.

**Comment by szuecs** [comment]
@aryszka I think at Zalando cluster we enforce spec.hosts which doesn’t mean that we have to have it enforced in the oss version.

**Comment by aryszka** [comment]
Correct, I also believe that the implementation on Skipper side doesn't enforce it (to be verified), and only the CRD enforces it. I think the CRD needs to be fixed to not enforce the host, while we can find other ways for additional validation.

**Comment by szuecs** [comment]
@aryszka yes the CRD is which enforces it and it was changed also in skipper oss project via https://github.com/zalando/skipper/pull/1490

**Comment by szuecs** [comment]
Doc change was merged
