### ISSUE TITLE
Declarative validations for filters and predicates

### ISSUE THREAD

**Issue by danpersa** [zalando/skipper#153]
Right now, as soon as a predicate or filter is constructed, there are some checks done.

Those checks can be done in a more general, declarative way. For example, for a `status` filter, we could have:

    status(float)

Based on this, we know that status should accept one parameter, and that that parameter should be a float.

**Comment by lmineiro** [comment]
I don't exactly get it. What do you propose?

**Comment by LappleApple** [comment]
@danpersa Can you clarify? Otherwise, we can close this issue.
