### ISSUE TITLE
Pass along Logrus JSONFormat to ApplicationLog and AccessLog loggers

### ISSUE THREAD

**Issue by peterklijn** [zalando/skipper#1535]
**Is your feature request related to a problem? Please describe.**
We use Skipper as a framework (as code) within our company. The structured logs that Skipper sends differ slightly from our other services. 
For example, we use the field `lvl` for the log level, while Skipper uses the Logrus default `level`.
I would like to make these settings configurable, so our services aligned again.

**Describe the solution you would like**
Logrus allows for these fields [to be changed easily](https://godoc.org/github.com/sirupsen/logrus#JSONFormatter), but unfortunately Skipper does not expose a way of overriding them.
I would like to know if you're open to adding these options to the `skipper.Options`.

**Additional context (optional)**
I made [a draft PR](https://github.com/zalando/skipper/pull/1534) to illustrate what I mean.

**Would you like to work on it?**
Yes

**Comment by szuecs** [comment]
Great to see that skipper is used at your place!
The change sounds good as long as the default doesn't change.
More options for library users make always sense to me.

**Comment by peterklijn** [comment]
Awesome! It should not affect the default as the struct will be initialized empty, just like now, it’s just initialized at a different place :)
