### ISSUE TITLE
Apply Gocover.io so I can add this to Awesome Go

### ISSUE THREAD

**Issue by LappleApple** [zalando/skipper#154]
To add Skipper to https://github.com/avelino/awesome-go, it needs a Gocover link. Can you add?

**Comment by aryszka** [comment]
Added the gocover badge.

Currently, it shows an error, not sure why. On the other hand it seems like it runs only the root package tests, which is not very useful in skipper's case. I'll check yet some time if i can fix this, but seems like gocover is not prepared for sub packages. In addition to all, we have a small script to be run for being able to test, that won't be gone until we replace etcd, as the default route source with something.

**Comment by LappleApple** [comment]
Thanks, @aryszka :)

**Comment by aryszka** [comment]
np :)
i close this issue for now. We have plans to cleanup the tests, I'll give an update when that changes the coverage report.
