### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by LappleApple** [zalando/skipper#155]
Would also identify 2-3 issues you really want help with that are good candidates for community to-do's, and add them in the README. I could do the add, if you share the issue #'s here.

**Comment by LappleApple** [comment]
@aryszka @lmineiro @danpersa Went ahead and made one. This project has a fair number of open issues; to encourage contributions I would highlight a few in the README that you really need.

**Comment by aryszka** [comment]
solved by #183
