### ISSUE TITLE
Skipper available as docker image

### ISSUE THREAD

**Issue by akurkin** [zalando/skipper#157]
hey guys,
will be really nice to have skipper available as a docker image, so we can bypass the go get step and use it in a form of docker image.

Thanks,
Alex

**Comment by lmineiro** [comment]
Skipper is mainly a library, hence the reason why we never included any Docker image.
Of course, there are also the cmd binaries, eskip and skipper. Is this something that you'd like to see packaged as a Docker image?

**Comment by mo-gr** [comment]
Especially having eskip as a docker image could be useful. People could validate their eskip files without going through the whole `$GOPATH`/`go get` dance

**Comment by aryszka** [comment]
we can create a docker image and link it from here. The skipper cmd shipped here can be useful with some quick-n-dirties, while eskip can be useful qutie regularly. We can still document that the recommended way of using skipper is to compile your own for production purposes with the potential extensions.

**Comment by szuecs** [comment]
Hi!

Did you have a particular reason to have it running on Arch and not an OS which could be analyzed by https://github.com/coreos/clair ?
As some kind of frontend loadbalancer it would be better to know (or even better automated reported) your CVEs. Maybe Arch can also be used with Clair, but it's not listed.

Thanks and best, sandor

**Comment by aryszka** [comment]
ok, convinced: will make an ubuntu based one, too.

**Comment by lmineiro** [comment]
I don't think this is even relevant. Clair should be the one supporting analysis of different distros. AFAIK, it doesn't do any inspection on our Go binaries (can it?). There are clear benefits on keeping this image as slim as it is. If anything, we could consider contributing the analyser for Clair for the base image that we're using - busybox

**Comment by szuecs** [comment]
@lmineiro this is totally true, but Arch is as big as Ubuntu....
On the other hand what do you need from busybox and why not having FROM scratch?
We would have to implement and maintain a custom Certpool, but this could be good, too.
For example if you want to use an internal CA and make it possible without modifying System CA would be a feature. On the other hand you can also whitelist some CAs your system really needs to use and you would be more secure to wiretapping from systems that have a wildcard cert 3rd party CAs within your System CA of your chosen OS.

**Comment by aryszka** [comment]
@lmineiro @szuecs, sofar, i was thinking about this docker image as something that is used to have a quick-and-dirty skipper available when you don't want to install go and git and compile skipper. for more serious, prodcution use cases, i believe, it is not a big deal to create a new image that contains all that is needed for the purpose (and optimally nothing else). So we should agree on what we expect from this image.

**Comment by lmineiro** [comment]
"quick-and-dirty skipper available" sounds like the best fit. My expectation is that anyone else out there is going to build their own image with all their requirements.

**Comment by szuecs** [comment]
I am also ok with it, but it should be clearly communicated that we do not regularly update the Dockerfile and for security reasons you should only run this on localhost.

**Comment by aryszka** [comment]
agreed :+1:

**Comment by aryszka** [comment]
i leave this issue open now, and update the readme during the match

**Comment by LappleApple** [comment]
Hey @akurkin, wondering if you have any new feedback on this issue since your original comment and the ensuing discussion. Let us know. :)

**Comment by LappleApple** [comment]
@aryszka @mo-gr @lmineiro @szuecs @Raffo Now that some time has passed, and some ideas have been shared, what's our final verdict re: Docker image? Seems like something that could enhance UX (and therefore increase potential users), but correct me if I'm wrong.

**Comment by lmineiro** [comment]
I think we should push images regularly to the public Docker registry. Regardless of the chosen distribution, the image should contain the resulting binaries in the $PATH of such image for easy execution such as:

`docker run skipper`
which should default to run skipper with a basic set good working defaults)

`docker run skipper <any set of skipper parameters>`
that would run skipper with the provided argument, allowing combination with any route sources and custom settings

`docker exec skipper eskip`
that would run the eskip binary inside the container although still allowing us to pipe to/from stdout/stdin

This should depend on a formal release process and appropriate versioning, as stated on #132
