### ISSUE TITLE
Add backend host as a tag to tokeninfo span of auth filter

### ISSUE THREAD

**Issue by sergeykolbasov** [zalando/skipper#1587]
**Is your feature request related to a problem? Please describe.**
At the moment it's impossible to create a tracing stream of `tokeninfo` spans executed only for a specific backend if auth is performed by Skipper filter. Therefore, it's not straight-clear how to measure time spent on authentication in the specific service's response.

**Describe the solution you would like**
It would be nice to include a tag like `backend_host` into `tokeninfo` span inside of
https://github.com/zalando/skipper/blob/d8a1723249ca8f7fe8da4a6bd061bf4554e56907/filters/auth/authclient.go#L95

**Additional context**
Span I'm talking about would include an additional tag (attribute) here:
![image](https://user-images.githubusercontent.com/2317121/98125587-4f1ec180-1ebd-11eb-9e97-05bdd5602c7a.png)

**Would you like to work on it?**
Yes, if it makes sense

**Comment by szuecs** [comment]
Backend host will be the host (url) configured for tokeninfo or the backend application skipper will proxy to?

**Comment by sergeykolbasov** [comment]
The application's backend

**Comment by szuecs** [comment]
@sergeykolbasov why do you need this in the tokeninfo span?
It's already on the proxy span, which I think it should belong to.
Filter does not know about the chosen backend (only known by the load balancer and the proxy)

**Comment by sergeykolbasov** [comment]
>why do you need this in the tokeninfo span?

@szuecs so I'd be able to build a tracing stream out of the tokeninfo spans that are related only to the specific downstream service, meaning I would be able to tell how much time was spent on auth from the total request time

I've ventured into the codebase, and it seems one can't add custom tags to the span created in the depths of HTTP client

**Comment by szuecs** [comment]
As discussed in chat, not really possible
