### ISSUE TITLE
Hijacked connection panics when flush

### ISSUE THREAD

**Issue by ardaguclu** [zalando/skipper#1593]
**Describe the bug**
We are using skipper with upgrading and hijacking request to our websocket service. It was working without any problem with the 0.11.1 version. After upgrading to 0.11.182(with trying 0.11.177, etc.), it started getting panics while closing the connection.

`gateway           | 2020/11/05 07:32:26 http: response.WriteHeader on hijacked connection from github.com/zalando/skipper/logging.(*LoggingWriter).Flush (loggingwriter.go:39)
gateway           | 2020/11/05 07:32:26 http: panic serving 172.18.0.4:53380: runtime error: invalid memory address or nil pointer dereference
gateway           | goroutine 6346 [running]:
gateway           | net/http.(*conn).serve.func1(0xc0001377c0)
gateway           | 	/usr/local/go/src/net/http/server.go:1801 +0x147
gateway           | panic(0x137d5c0, 0x1bcf1f0)
gateway           | 	/usr/local/go/src/runtime/panic.go:975 +0x47a
gateway           | bufio.(*Writer).Flush(0x0, 0xc8, 0x7f56a8a88ad8)
gateway           | 	/usr/local/go/src/bufio/bufio.go:601 +0x26
gateway           | net/http.(*response).Flush(0xc00053e8c0)
gateway           | 	/usr/local/go/src/net/http/server.go:1673 +0x35
gateway           | github.com/zalando/skipper/logging.(*LoggingWriter).Flush(...)
gateway           | 	/go/pkg/mod/github.com/zalando/skipper@v0.11.182/logging/loggingwriter.go:39
gateway           | github.com/zalando/skipper/proxy.(*Proxy).ServeHTTP.func2(0xc000435b60, 0xc0003f61c0, 0xc0005510a0, 0xc000435c08)
gateway           | 	/go/pkg/mod/github.com/zalando/skipper@v0.11.182/proxy/proxy.go:1461 +0xfb
gateway           | github.com/zalando/skipper/proxy.(*Proxy).ServeHTTP(0xc0003f61c0, 0x16162c0, 0xc00053e8c0, 0xc00080b900)
gateway           | 	/go/pkg/mod/github.com/zalando/skipper@v0.11.182/proxy/proxy.go:1491 +0x5a9
gateway           | net/http.serverHandler.ServeHTTP(0xc0003f62a0, 0x16162c0, 0xc00053e8c0, 0xc00080b800)
gateway           | 	/usr/local/go/src/net/http/server.go:2843 +0xa3
gateway           | net/http.(*conn).serve(0xc0001377c0, 0x1619680, 0xc000472f40)
gateway           | 	/usr/local/go/src/net/http/server.go:1925 +0x8ad
gateway           | created by net/http.(*Server).Serve
gateway           | 	/usr/local/go/src/net/http/server.go:2969 +0x36c`

After extensive debugging, I realized that ctx.responseWriter(which is actually LoggerWritter) has been changed after hijacked connection (loggingwriter.go line:45)
Before:
`&{conn:0xc00011a960 req:0xc00045c000 reqBody:{} cancelCtx:0x965be0 wroteHeader:false wroteContinue:false wants10KeepAlive:false wantsClose:false canWriteContinue:0 writeContinueMu:{state:0 sema:0} w:0xc00075e940 cw:{res:0xc0002656c0 header:map[] wroteHeader:false chunking:false} handlerHeader:map[] calledHeader:false written:0 contentLength:-1 status:0 closeAfterReply:false requestBodyLimitHit:false trailers:[] handlerDone:0 dateBuf:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] clenBuf:[0 0 0 0 0 0 0 0 0 0] statusBuf:[0 0 0] closeNotifyCh:0xc0002220e0 didCloseNotify:0}`

After:
`&{conn:0xc00011a960 req:0xc00045c000 reqBody:{} cancelCtx:0x965be0 wroteHeader:false wroteContinue:false wants10KeepAlive:false wantsClose:false canWriteContinue:0 writeContinueMu:{state:0 sema:0} w:<nil> cw:{res:0xc0002656c0 header:map[] wroteHeader:false chunking:false} handlerHeader:map[] calledHeader:false written:0 contentLength:-1 status:0 closeAfterReply:false requestBodyLimitHit:false trailers:[] handlerDone:0 dateBuf:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] clenBuf:[0 0 0 0 0 0 0 0 0 0] statusBuf:[0 0 0] closeNotifyCh:0xc0002220e0 didCloseNotify:0}"`

As seen above, "w" becomes nil.

In proxy.go, when calling, it panics because of w should not be nil.
`if ctx.successfulUpgrade {
			lw.Flush()
		}`

My proposal is for hijacked connections, skipper should not rely on lw(loggingwriter) has not been changed.

**Comment by ardaguclu** [comment]
[https://github.com/zalando/skipper/pull/1594](url)

**Comment by szuecs** [comment]
@ardaguclu thanks great finding!
