### ISSUE TITLE
Duplicate routes and rewrite predicate

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#1619]
**Is your feature request related to a problem? Please describe.**
If you want to migrate ALB (http proxy) to NLB (packet forwarder), in front of your skipper fleet and use for example SourceFromLast predicate, you want to rewrite routes to use ClientIP predicate.
Context https://github.com/zalando/skipper/issues/1614#issuecomment-732818965

**Describe the solution you would like**
I would propose to use PreProcessor to duplicate routes that use for example Source() and rewrite to ClientIP(). This should be done via flag with src, dest tuples such that we can do this in general.

In the ideal case we would be able to use variables to make positional parameters rewriteable, too.

The simple example would be: `-rewrite-predicate='Source(),ClientIP()'`, which would rewrite `Source(cidr1, cidr2)` to `ClientIP(cidr1, cidr2)`.
In case of variables we could do something like: `-rewrite-predicate='Source($v),ClientIP("10.0.0..0/8", $v)'`, which would rewrite `Source(cidr1, cidr2)` to `ClientIP("10.0.0.0/8", cidr1, cidr2)`.

**Comment by AlexanderYastrebov** [comment]
@szuecs Is this PR https://github.com/zalando/skipper/pull/1822 related (or fixes this issue)?

**Comment by szuecs** [comment]
@AlexanderYastrebov yes, thanks
