### ISSUE TITLE
Client disconnecting before the request is sent can result in the wrong status code

### ISSUE THREAD

**Issue by aermakov-zalando** [zalando/skipper#1631]
**Describe the bug**

If a client disconnects before the request is sent, most of the time Skipper recognises it correctly and tracks it with the status code 499:

    [APP]time="2020-12-04T09:54:41Z" level=error msg="client canceled after 64.545424ms, route kube_XXXX with backend network http://XXXX:8080, status code 499: dialing failed false: context canceled, remote host: XXXX, request: \"POST / HTTP/1.1\", user agent: \"\""
    XXXX - - [04/Dec/2020:09:54:41 +0000] "POST / HTTP/1.1" 499 1 "-" "-" 64 XXXX - -

About 10–15% of the time, however, a different code path is triggered and the request is instead tracked as a 503. This can affect application metrics and lead to investigations even though the issue is actually on the client side:

    [APP]time="2020-12-04T09:54:41Z" level=error msg="net.Error during backend roundtrip to http://XXXX:8080: timeout=false temporary=false: readfrom tcp XXXX:59618->XXXX:8080: unexpected EOF"
    [APP]time="2020-12-04T09:54:41Z" level=error msg="error while proxying after 70.344343ms, route kube_XXXX with backend network http://XXXX:8080, status code 503: dialing failed false: readfrom tcp XXXX:59618->XXXX:8080: unexpected EOF, remote host: XXXX, request: \"POST / HTTP/1.1\", user agent: \"\""
    XXXX - - [04/Dec/2020:09:54:41 +0000] "POST / HTTP/1.1" 503 20 "-" "-" 70 XXXX - -

**To Reproduce**

    HOSTNAME=XXXX

    echo "POST / HTTP/1.1
    Host: $HOSTNAME
    Content-Length: 20

    asd" > request

    while sleep 1; do cat request|socat -dd stdio openssl:$HOSTNAME:443,verify=0; done

**Expected behavior**

All of the requests result in a 499.

**Observed behavior**

About 10–15% of the requests instead result in a 503.

**Comment by AlexanderYastrebov** [comment]
Also reproducible with
```
$ bin/skipper -inline-routes='sink: Path("/sink") -> <shunt>; test: Path("/") -> setPath("/sink") -> "http://localhost:9090"'
$ while true; do curl -q -XPOST -H "Content-Length: 10" -m 0,01 localhost:9090 ; sleep 1; done
```

Debug log
```diff
diff --git a/proxy/proxy.go b/proxy/proxy.go
index f4a966d..1b7d83a 100644
--- a/proxy/proxy.go
+++ b/proxy/proxy.go
@@ -941,6 +941,9 @@ func (p *Proxy) makeBackendRequest(ctx *context) (*http.Response, *proxyError) {
                        "event", "error",
                        "message", err.Error())
 
+               cerr := req.Context().Err()
+               p.log.Errorf("err vs cerr: same: %v, err: %v %#v, cerr: %v %#v", err == cerr, err, err, cerr, cerr)
+
                if perr, ok := err.(*proxyError); ok {
                        p.log.Errorf("Failed to do backend roundtrip to %s: %v", ctx.route.Backend, perr)
                        //p.lb.AddHealthcheck(ctx.route.Backend)
```
shows 
```
[APP]ERRO[0271] err vs cerr: same: false, err: readfrom tcp 127.0.0.1:40608->127.0.0.1:9090: unexpected EOF &net.OpError{Op:"readfrom", Net:"tcp", Source:(*net.TCPAddr)(0xc00030fa40), Addr:(*net.TCPAddr)(0xc00030fa70), Err:(*errors.errorString)(0xc000080070)}, cerr: context canceled &errors.errorString{s:"context canceled"} 
...
[APP]ERRO[0272] err vs cerr: same: true, err: context canceled &errors.errorString{s:"context canceled"}, cerr: context canceled &errors.errorString{s:"context canceled"}
```
i.e. sometimes roundtrip error (`err`) is `unexpected EOF` and sometimes it is `context canceled`, the same as request context error. Request context error seems to be always present. `unexpected EOF` results in 503 and `context canceled` in 499.

The solution could be to check request context error before inspecting roundtrip error (within or even outside of `if err != nil`) and thus give it a priority:
https://github.com/zalando/skipper/blob/9f8c62c12b9edb6d2f6147221a178383f8f3a4d6/proxy/proxy.go#L938-L973
