### ISSUE TITLE
Getting connection refused but can connect through port forward to service/pods

### ISSUE THREAD

**Issue by cartucciam** [zalando/skipper#1649]
Hi there, I have been getting 502s consistently one of our deployments. I can successfully port forward onto the service and the pod, the security groups are allowing traffic between those IPs and the container is exposing the right port.

```
[APP]time="2020-12-10T08:29:15Z" level=error msg="Failed to do backend roundtrip to : dialing failed true: dial tcp X.X.X.X:8000: connect: connection refused"[APP]time="2020-12-10T08:29:15Z" level=error msg="Failed to do retry backend request: dialing failed true: dial tcp X.X.X.X:8000: connect: connection refused"[APP]time="2020-12-10T08:29:15Z" level=error msg="error while proxying after 1.134416ms, route kube_development__frontend_dev_project_helm_frontend_ingress__dev_project_example_com_____frontend_dev_project_helm_frontend_service with backend lb http://X.X.X.X:8000, status code 502: dialing failed true: dial tcp X.X.X.X:8000: connect: connection refused, remote host: X.X.X.X, request: \"GET / HTTP/1.1\", user agent: \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36\""
X.X.X.X - - [10/Dec/2020:08:29:15 +0000] "GET / HTTP/1.1" 502 12 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" 1 dev.project.example.com- -
```

I can see the routes on a daemon and they are as expected resolving to the container port target:
```
kube_development__frontend_dev_project_helm_frontend_ingress__dev_project_example_com_____frontend_dev_project_helm_frontend_service: Host(/^dev[.]project[.]example[.]com$/) && PathSubtree("/")
  -> <roundRobin, "http://X.X.X.X:8000", "http://X.X.X.X:8000">;
```

I am using `v0.11.151`, is this something already seen?

**Comment by AlexanderYastrebov** [comment]
> I can successfully port forward onto the service and the pod
Is it possible to connect from skipper pod to application pod?

**Comment by szuecs** [comment]
@cartucciam yes I saw these when the backend restarted during this time we get connection errors until readinessProbe populated through kubernetes and skipper update the routing table again.

**Comment by cartucciam** [comment]
Hi @AlexanderYastrebov and @szuecs, I can't connect from the skipper pod to the endpoint target. With another deployment I don't have this issue. All the worker nodes have a security group to allow talking to each other and I can access the container with port forwarding.

**Comment by szuecs** [comment]
Maybe same as https://github.com/zalando/skipper/issues/1645 ?

**Comment by cartucciam** [comment]
> Maybe same as #1645 ?

I don't think so, I get this even using the same port for target and container and the routes shown on the skipper pod are correct.

**Comment by cartucciam** [comment]
It was a problem with the application, thanks for all the help.
