### ISSUE TITLE
Add filter to allow/deny certain IPs

### ISSUE THREAD

**Issue by evangelion1204** [zalando/skipper#165]
Hi,

We would need something to block or allow certain IP-Ranges to access different routes, maybe it would make sense to use a filter to return a `403`. 
A matcher could be an alternative to not even select the route blocked for certain ranges.

`allow: Path("/allow") -> allowIPv4("192.168.1.0/24", "127.0.0.1/32") -> "http://myendpoint.org"`
or
`deny: Path("/deny") -> denyIPv4("100.100.100.100/32", "192.168.2.0/24") -> "http://myendpoint.org"`

In case that the rule is not matching it will return a `403`.

**Comment by lmineiro** [comment]
We already have something in those lines. The `Source` predicate was created for similar purposes.

Check https://github.com/zalando/skipper/blob/master/predicates/source

You just need to craft your routing table in a way that only matches with the allowed source IP addresses and a catch all route that returns `403`.

**Comment by evangelion1204** [comment]
Yeah it helps, then we don't even expose that this is route is available 😄  I will come back to you if I ever need a `!source`
