### ISSUE TITLE
How to set LoadUpdate() interval for dataclient implementations

### ISSUE THREAD

**Issue by cbrgm** [zalando/skipper#1655]
Hi there,

just a quick question. I'm currently using skipper as a library and I'm implementing a custom dataclient to poll routes from.
It's working fine so far, but the `LoadUpdate()` function is called quite often during runtime. Is it hacky to simply put a `time.Sleep` statement at the end of the function like this:

```
func (c *Client) LoadUpdate() ([]*eskip.Route, []string, error) {
	// do stuff
	time.Sleep(time.Duration(5) * time.Second)
	// ...
	return updatedRoutes, deletedIDs, nil
}
```

or is there any option to set the `LoadUpdate()` interval via `skipper.Options` from the outside?

Cheers
Chris

**Comment by AlexanderYastrebov** [comment]
https://github.com/zalando/skipper/blob/7c1c975916e316a240e397df21eeabaea3218284/routing/routing.go#L89-L91

https://github.com/zalando/skipper/blob/7c1c975916e316a240e397df21eeabaea3218284/routing/datasource.go#L76

**Comment by cbrgm** [comment]
Thanks alot! That's very helpful! I'm closing the isssue.
