### ISSUE TITLE
Cpu usage can not exceed 200%

### ISSUE THREAD

**Issue by ycydk** [zalando/skipper#1661]
I found that cpu usage couldn't not exceed 200% when stress testing was performed

**Comment by szuecs** [comment]
@ycydk we run skipper sometimes with 32 CPU cores with >16 cores in use all the time.
Please create more information, because right now the issue is just not understandable and I would consider the statement as just wrong.

Thanks for your time to create more information about setup (hardware assigned, runtime, test setup, how do you measure 200%, how do you see 200% as max, which counters are used, why do you think backend is not the bottleneck, ... ?).

**Comment by ycydk** [comment]
@szuecs 
thank you for your reply!
we use skipper in a kubernetes cluster
the args 
- skipper
        - -kubernetes
        - -kubernetes-in-cluster
        - -kubernetes-path-mode=path-prefix
        - -address=:80
        - -wait-first-route-load
        - -proxy-preserve-host
        - -serve-host-metrics
        - -disable-metrics-compat
        - -enable-profile
        - -debug-listener=:9922
        - -enable-ratelimits
        - -experimental-upgrade
        - -metrics-exp-decay-sample
        - -reverse-source-predicate
        - -lb-healthcheck-interval=3s
        - -metrics-flavour=prometheus
        - -enable-connection-metrics
        - -enable-route-lifo-metrics
        - -max-audit-body=0
        - -histogram-metric-buckets=.0001,.00025,.0005,.00075,.001,.0025,.005,.0075,.01,.025,.05,.075,.1,.2,.3,.4,.5,.75,1,2,3,4,5,7,10,15,20,30,60,120,300,600
        - -expect-continue-timeout-backend=30s
        - -keepalive-backend=30s
        - -max-idle-connection-backend=0
        - -response-header-timeout-backend=1m
        - -timeout-backend=1m
        - -tls-timeout-backend=1m
        - -close-idle-conns-period=20s
        - -idle-timeout-server=62s
        - -read-timeout-server=5m
        - -write-timeout-server=60s
        - -default-filters-prepend=enableAccessLog(4,5) -> lifo(2000,20000,"3s")
        - -route-creation-metrics
        - -enable-tcp-queue
        - -expected-bytes-per-request=51200
        - -max-tcp-listener-concurrency=-1
        - -max-tcp-listener-queue=-1

we use jmeter to do stress test using 200 threads with one skipper, the backend has 5 instances. we use top command to observe the spu usage and we find that the tps is about 2000 and the cpu usage can not exceed 2core (with a 16core machine). if we increase the num of threads,  tps and cpu usage don't increase.  
Maybe I didn't use skipper properly, can you give me some help?

**Comment by szuecs** [comment]
-default-filters-prepend=enableAccessLog(4,5) -> lifo(2000,20000,"3s") 
 will allow 2000 concurrent requests to a single route. If you hit with jmeter always the same route you will be limited there.


- -enable-tcp-queue
- -expected-bytes-per-request=51200
- -max-tcp-listener-concurrency=-1
- -max-tcp-listener-queue=-1
Will limit concurrent tcp connections based on memory available in cgroup.


There are also a bunch of other cases that can limit (OS related and load test related, nothing special to skipper itself)

**Comment by ycydk** [comment]
@szuecs
thank you very much!
i found out why.
