### ISSUE TITLE
[improvement] CRD API Schema missing some field descriptions

### ISSUE THREAD

**Issue by Nilegfx** [zalando/skipper#1663]
**Is your feature request related to a problem? Please describe.**
Missing some descriptions when using `zkubectl explain` command

**Describe the solution you would like**
Being more strict with  CRD's API schema, we are missing some descriptions to some properties  (specifically the routeGroups definition so it would act as a closer and fast source of documentation)

example: 
```
$ remove-me zkubectl explain rg.spec.hosts
KIND:     RouteGroup
VERSION:  zalando.org/v1

FIELD:    hosts <[]string>

DESCRIPTION:
     <empty>
```

**Describe alternatives you've considered (optional)**
Navigating dev.zalando.net and then redirecting myself to skipper docs (which is still not explaining every single field
as an example, when backend type is `network` there is no clear way to determine that it pairs with `address` field

**Additional context (optional)**

**Would you like to work on it?**
Yes

**Comment by mikkeloscar** [comment]
The CRD generated as part of the client library has better descriptions: https://github.com/szuecs/routegroup-client/blob/master/zalando.org_routegroups.yaml

It may make sense to adapt that version in skipper
