### ISSUE TITLE
Websocket connection is not closed when backend server is stopped

### ISSUE THREAD

**Issue by LEDfan** [zalando/skipper#1669]
Hi all, first thank you for Skipper, we use it as "intermediate" ingress controller in one of our projects.

**Describe the bug**
I'll first give some context:
We use Skipper as ingress controller in a Kubernetes deployment. We have an application that makes uses of websocket connections.
The front-end of this application connects to the Java application using websockets. The front-end will show a message as soon as the websocket connection is broken. In our case we break the websocket connection by removing the pod containing the application. When not using Skipper, this is working fine and the application does notice that the websocket connection is broken. 
In addition, when we use nginx as ingress controller, we experience the same behavior. However, the browser is unable to notice that the connection is broken when using Skipper as ingress controller.

**To Reproduce**

1. have a kubernetes cluster ready, e.g. using minkube
2. deploy Skipper and the test application: https://gist.github.com/LEDfan/24bc8a648ebe9c2291eaf9447b7389bb
3. warning: the above link will make the default serviceaccount a cluster-admin *just for testing*
3. add an entry to `/etc/hosts` for `127.0.0.1	tabsets.local `
4. forward skipper port, e.g. using `sudo kubectl --kubeconfig=$HOME/.kube/config port-forward --namespace default `k get pods --selector "application=skipper-ingress" --output=jsonpath={.items..metadata.name}
` 80:9999`
5. go to `tabsets.local` in your browser
6. when you change the slider, some data will be queried over the websockets connection. The graph should be updated whenever the slider changes.
7. kill the `tabsets` pod

**Expected behavior**

The page becomes gray (see screenshot) indicating that the websocket connection is broken.

**Observed behavior**

Skipper keeps the connection alive. Therefore the application isn't aware that the connection is broken. You can still change the slider in the application, and the application will send data over the websocket connection..

Is this something you think you can solve? Would be really useful for us!

**Comment by szuecs** [comment]
@LEDfan thanks for the issue we will check it as soon we are back from vacation period.
As long we can reproduce it we should be able to fix it.

**Comment by AlexanderYastrebov** [comment]
To reproduce locally:
1. Run `openanalytics/shinyproxy-demo`
```
docker run -it --rm -p 3838:3838 openanalytics/shinyproxy-demo R -e "shinyproxy::run_06_tabsets()"
```
1a. Navigate to http://localhost:3838 move slider - chart updates
1b. Ctrl+C `shinyproxy-demo` docker - application becomes grey as expected
1c. Run `shinyproxy-demo` docker again 

2. Run skipper 
```
bin/skipper -address=:9999 -experimental-upgrade -inline-routes='* -> "http://localhost:3838"'
```
2a. Navigate to http://localhost:9999 move slider - chart updates
2b. Ctrl+C `shinyproxy-demo` docker - application does not become grey
2c. Move slider, on the second move application becomes grey, skipper prints
```
[APP]ERRO[0063] error proxying data from src to dst: write tcp 127.0.0.1:59356->127.0.0.1:3838: write: broken pipe 
::1 - - [28/Dec/2020:23:34:08 +0100] "GET /websocket/ HTTP/1.1" 0 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 55136 localhost:9999 - -
```
in the logs, dev tools websocket tab shows two update messages hanging:
![Screenshot from 2020-12-28 23-37-08](https://user-images.githubusercontent.com/697976/103246996-a2fdd200-4965-11eb-8ca3-1f77c98839e0.png)

**Comment by LEDfan** [comment]
>  Do I understand correctly that the backend pod does a non graceful teardown?

Yes indeed. 

I just built a Docker image from the PR by @AlexanderYastrebov and I can confirm this works as expected! Even in our most complex setup with two additional proxies in place. 
Many thanks, this I why I love open-source!

Enjoy your vacation and celebrations!
