### ISSUE TITLE
Slack invite in README is out of data and no longer works

### ISSUE THREAD

**Issue by spkane** [zalando/skipper#1685]
**Describe the bug**
Slack invite in README is out of data and no longer works.

As a workaround: I found this working invite via reddit: https://invite.slack.golangbridge.org/

**To Reproduce**
Attempt to use the link

**Expected behavior**
The link works and allows on to join gophers.slack.com

**Observed behavior**
It says that it is expired.

**Comment by jonathanbeber** [comment]
Thanks for the info @spkane. I believe https://invite.slack.gobridge.org/ is working again now. We can remove the extra info.

**Comment by szuecs** [comment]
Great thanks for the info!
I added this as a workaround a while ago.
