### ISSUE TITLE
OauthGrant: Documentation inconsistent with implementation regarding access token header name

### ISSUE THREAD

**Issue by k-nut** [zalando/skipper#1687]
One of the features of the new oauthGrant flow is Skipper automatically adding the auth token to a header for subsequent requests.

Then name of the header where the token should be put is defined with the `-oauth2-access-token-header-name` flag. The [documentation](https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#oauthgrant) states that the default header name is `Authorization` whereas the actual [implementation (config)](https://github.com/zalando/skipper/blob/master/config/config.go#L588) sets `""` as a default value. This means that currently if users do not pass the flag, the header is not added to their requests. See [implementation (code)](https://github.com/zalando/skipper/blob/master/filters/auth/grant.go#L128).

There are two options to fix this:
1) Change the documentation to point out that this flag needs to be set if the token should be passed on. If it is not set, the token will not be passed on.
2) Change the implementation to use `Authorization` as the default header name like the documentation currently says.

What do you think?

**Comment by AlexanderYastrebov** [comment]
The answer depends on whether auth header is mandatory for downstream application.

**Comment by szuecs** [comment]
@muaazsaleem @aryszka ^

**Comment by AlexanderYastrebov** [comment]
#1732 documents option #1
