### ISSUE TITLE
Password support for Redis server

### ISSUE THREAD

**Issue by c0nstantx** [zalando/skipper#1702]
**Is your feature request related to a problem? Please describe.**

`Skipper` has `Redis` as a persistence option to enforce cluster rate limits. Current implementation doesn't support redis servers that use password.  

**Describe the solution you would like**

A new setting will be introduced `-swarm-redis-password` which will set the password for `Redis` ring.

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Would you like to work on it?**
Yes

**Comment by AlexanderYastrebov** [comment]
Thank you for the PR. 
As there are already have quite a few of redis-related options:
```
$ grep -oE 'swarm-redis[a-zA-Z-]+' config/config.go | sort -u
swarm-redis-dial-timeout
swarm-redis-max-conns
swarm-redis-min-conns
swarm-redis-pool-timeout
swarm-redis-read-timeout
swarm-redis-urls
swarm-redis-write-timeout
```
what is the benefit of encoding password into the address over explicit password option (e.g. `-swarm-redis-password`)?

**Comment by c0nstantx** [comment]
The reason behind this decision was to be compatible with existing implementations, without having to edit code in order to support passwords.
The only thing needed with this approach is just the update of Skipper's version and add the passwords in the configuration.
Of course this applies only for cases of using Skipper as a library.

TBH, I am not very strong on my approach. Having a clear setting for password, as you described, is also nice.

Do you think it will be more consistent to have it as a separate option ?

**Comment by AlexanderYastrebov** [comment]
I think password in the url of the first shard is a bit obscure and feels unaligned with options already present. 
Having it as a separate option makes it clear and documented similar to:
```
$ bin/skipper -h 2>&1 | grep redis
  -swarm-redis-dial-timeout duration
        set redis client dial timeout (default 25ms)
  -swarm-redis-max-conns int
        set max number of connections to redis (default 100)
  -swarm-redis-min-conns int
        set min number of connections to redis (default 100)
  -swarm-redis-pool-timeout duration
        set redis get connection from pool timeout (default 25ms)
  -swarm-redis-read-timeout duration
        set redis socket read timeout (default 25ms)
  -swarm-redis-urls value
        Redis URLs as comma separated list, used for building a swarm, for example in redis based cluster ratelimits
  -swarm-redis-write-timeout duration
        set redis socket write timeout (default 25ms)
```

**Comment by c0nstantx** [comment]
Cool. Thanks for the feedback.
I will change it accordingly :+1:

**Comment by AlexanderYastrebov** [comment]
Your initial proposal is akin to the [connection string](https://en.wikipedia.org/wiki/Connection_string) approach.
As we are talking about password which is a sensitive bit, it might the best practice to specify it via environment variable, see e.g.:
* https://redis.io/topics/rediscli#host-port-password-and-database
* https://dba.stackexchange.com/questions/14740/how-to-use-psql-with-no-password-prompt

@szuecs @aryszka WDYT?

**Comment by c0nstantx** [comment]
About `ps` you can pass the password as an environment variable in the command so that it isn't visible. ex. `skipper -swarm-redis-password=${REDIS_PASSWORD}`

Regarding the `kubectl describe` you can set environment variables as secret.
See here: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

**Comment by AlexanderYastrebov** [comment]
In the first example shell would resolve variable before command execution and password will be visible in `ps` output. 
The second will work if used in conjunction with https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config

**Comment by c0nstantx** [comment]
> In the first example shell would resolve variable before command execution and password will be visible in `ps` output.

You are right on that :+1:

**Comment by c0nstantx** [comment]
Hi @AlexanderYastrebov. Do you end up in a decision on the topic ?
FYI, I updated the [PR](https://github.com/zalando/skipper/pull/1703) and moved to your initial proposal passing it as an option `-swarm-redis-password`

**Comment by szuecs** [comment]
I would suggest to do it like this:
Flag and env,
If flag is not set (not passed to skipper configuration option), then read env and pass it.
Can you please check if we can just set an empty string as password for redis without password?
I guess it works but better to check before it doesn’t work for current users.

**Comment by c0nstantx** [comment]
> I would suggest to do it like this:
> Flag and env,
> If flag is not set (not passed to skipper configuration option), then read env and pass it.

OK. I will do that. Thanks :+1: 

> Can you please check if we can just set an empty string as password for redis without password?
> I guess it works but better to check before it doesn’t work for current users.

I checked it works manually, but you can verify it works also in [tests](https://github.com/zalando/skipper/blob/08b62b1201037b5ecf2fc741b923185ffbba988b/ratelimit/redis_test.go#L185) without password.
