### ISSUE TITLE
Improve consistent hash endpoint selection strategy

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/skipper#1712]
**Is your feature request related to a problem? Please describe.**

[Consistent hash](https://github.com/zalando/skipper/blob/master/docs/reference/backends.md#load-balancer-backend) load balancing algorithm uses simple endpoint selection strategy `endpoint = endpoints[hash(request) % len(endpoints)]` to select endpoint to serve client request. When endpoint list changes (e.g. due to backend re-scaling) the assignment of nearly every request may change.

**Describe the solution you would like**

Implement true consistent hashing algorithm that minimizes request-to-endpoint reassignment when endpoint list chages.

**Describe alternatives you've considered (optional)**

None

**Additional context (optional)**

Links:
* https://en.wikipedia.org/wiki/Consistent_hashing
* https://medium.com/better-programming/load-balancers-and-consistent-hashing-in-6-minutes-b5fc460aea4e
* https://github.com/dgryski/go-rendezvous (consider using implementation used by go-redis ring client)
* https://github.com/golang/groupcache/blob/master/consistenthash/consistenthash.go

Related to #557

**Would you like to work on it?**

Yes

**Comment by cjbooms** [comment]
Worth investigating if the Bounded Load algorithm could be implemented when working on this ticket:
https://arxiv.org/abs/1608.01350
https://medium.com/vimeo-engineering-blog/improving-load-balancing-with-a-new-consistent-hashing-algorithm-9f1bd75709ed
This algorithm is still consistent hashing load balancing, but it provides excellent failover to neighbouring nodes

**Comment by cjbooms** [comment]
This ticket can be closed if PR #1715 fixes the issue of mass request-to-endpoint reassignments when endpoint list changes 
I've created a separate ticket for the bounded load algorithm. 
https://github.com/zalando/skipper/issues/1769
