### ISSUE TITLE
rateLimit and clusterRateLimit filters should use HTTP 503 response status code

### ISSUE THREAD

**Issue by rbarilani** [zalando/skipper#1728]
**Is your feature request related to a problem? Please describe.**

Rate limiting capabilities that are not based on a client quota (by IP, by header, etc.) such as the one activated by `rateLimit` and `clusterRateLimit` filters are frequently used to protect the backend to be overloaded by too many requests, stopping requests based on server maximum capacity.

The current HTTP status code returned by those rate limiters is `429`.

Considering HTTP semantics though, a [503](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) status code might be more appropriate given that 4xx error indicates a bad/malformed request sent by the client.  
In this case the client "hasn't done anything wrong", they didn't overflow the quota that was assigned to them, the maximum requests might be reached since some other client misbehaved, had more traffic to digest, etc.
The client didn't send too many requests in a given amount of time ("rate limiting"), it's the backend that is unavailable to receive more requests. 

As per [503 HTTP documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) a header like ` Retry-After` can be added to the response representing the estimated time for the recovery of the service as is used for [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)'s responses.

The usage of a different status code would help also to distinguish in HTTP-based reports (logs, stats) the requests which were rate-limited since clients exceeded their quota from requests which were rate-limited since service unavailability.

**Describe the solution you would like**

Change or allow to change the response status code used by the rate limit filters to `503`.
To make this customization possible I would like to have a configuration value that enables to choose the response status code returned by the rate limit filters.
The value can be provided per filter for all routes (at skipper configuration level) and/or can be applied on a per route basis, eg.

```eskip
route_id: Path("/hello") -> clusterRateLimit(20, "1m", 503) -> https://mybackend.com
```

**Describe alternatives you've considered (optional)**

I have considered keeping the 429 status and use some other type of filtering on logs, open tracing traces to distinguish client quota-based rate-limited requests from "capacity-based" rate-limited requests but nothing simple and immediate as a different HTTP status code come out. 
We might think also to add optionally the information on the access logs but it sounds dirty.
We can filter on open tracing spans but I am not sure based on what especially when two rate limiters one client-based such as `clusterClientRateLimit` and `clusterRateLimit` are applied to the same route.

**Additional context (optional)**
N/A

**Would you like to work on it?**
Yes

**Comment by lmineiro** [comment]
Adding my 2c. I think @rbarilani very well describes what I personally consider the fundamental difference between rate limiting and load shedding. Both can use the exact same mechanism to protect a backend but the key difference is the semantics.
- Rate limiting should adopt 4XX and inform the client that they are exceeding some quota. It doesn't depend on the current capacity of the backend.
- Load shedding should adopt 5XX and inform the client that the backend is is not able to provide service. It depends on the current capacity of the backend.

This behavior can also be used to decide which operations affect the service's error budget and which ones don't. _Rate limiting should not_ affect the service error budget but _load shedding should_.

**Comment by szuecs** [comment]
So as far as I understand we could create a loadShedding filter, but as far as I understand load shedding, it should limit per backend instance to protect max throughput measured for one instance. @aryszka started using lifo queue for this use case which works on per skipper instance but at least it response with the 5xx status code.
For ratelimit I would not change the status code.

**Comment by rbarilani** [comment]
@szuecs what you think about the `loadSheedingLimit` and `clusterLoadSheedingLimit` filters? Didn't check in depth the code necessary but the idea will be to reuse as much as possible the abstraction created for rate-limiting package.

**Comment by AlexanderYastrebov** [comment]
@rbarilani In order to limit rps per backed instance, Skipper needs to be aware if the Skipper swarm size which is not implemented yet (`rps per backend instance = total rps / Skipper swarm size / number of backend instances`)

**Comment by rbarilani** [comment]
@AlexanderYastrebov actually I was thinking of something simpler, which is basically working as the `clusterRateLimit` filter and `rateLimit` filter but returning `503` instead of 429 given the scenario that we have (developers wanting to cap the maximum amount of request on route level or a group of routes)

**Comment by rbarilani** [comment]
@szuecs @AlexanderYastrebov What you are describing if I understood correctly it's really a nice feature for skipper-ingress but in our use case we use it as a simple/gateway proxy which has not and shouldn't necessarily have the notion of the number of instances, we want to "just" to cap the maximum amount of requests that a route can receive.

How can we/I proceed? Since I think that we are talking about two different features/things?

WDYT?

**Comment by szuecs** [comment]
Maybe we can have a global option to allow to set the response code type for ratelimits.
I think this should be a global decision and not case by case at filter level.
If you create a PR with adding a flag, config and pass this as option to set a default for RatelimitStatus it could be fine IMO.

**Comment by rbarilani** [comment]
@szuecs oh damned I missed the meetup!

**Comment by rbarilani** [comment]
> Maybe we can have a global option to allow to set the response code type for ratelimits.
I think this should be a global decision and not case by case at filter level.

@szuecs I thought about on filter level just for `rateLimit` and `clusterRateLimit` to allow to switch gradually to the new behaviour which might require consumers of those endpoints to adapt their code accordingly.

**Comment by szuecs** [comment]
@rbarilani we can do this only in non "client" ratelimit filters, because then we would need to break the configuration of these client filters. For rateLimit and clusterRateLimit we could do an optional argument to set the status code of choice.

@AlexanderYastrebov wdyt?

**Comment by aryszka** [comment]
I support adding an optional status code parameter to the rate limit filters, where possible, or where not, creating a variant that can support this parameter.

Though, for the load shedding use case, a cluster aware lifo would be indeed the best approach. It's planned for the near future, I'll create a separate issue for discussing that topic.

**Comment by AlexanderYastrebov** [comment]
> @AlexanderYastrebov wdyt?

Beside allowing status code override, I was thinking about flag to enable/disable retry-after headers.

Also we have two pairs of filters `ratelimit/clusterRatelimit` and `clientRatelimit/clusterClientRatelimit` with a difference that client versions use client IP or a header to compose limit key (where non-client use fixed key) so I was thinking that maybe we can extend non-client versions with template placeholder support (it supports fixed string, client ip, any header and much more) and deprecate client versions.

**Comment by aryszka** [comment]
just started wondering if we should rather create a filter that conditionally overwrites the status: `statusIf(429, 503)`. Composing more primitive filters like this would be quite "Skipper style", and the general use case of such a filter would be 'patching' the more exotic status codes in cases when e.g. a legacy or hard to change client doesn't tolerate them well, e.g. `statusIf(524, 504)`. WDYT?

**Comment by AlexanderYastrebov** [comment]
> just started wondering if we should rather create a filter that conditionally overwrites the status
> WDYT?

Not against it, but feel that proposed `statusIf` as well as `inlineContentIfStatus` are a bit borderline between declarative and imperative. For imperative we have Turing-complete lua support which can rewrite both status and body and do everything else:
```lua
function response(ctx)
    if ctx.response.status_code == 429 then
        ctx.serve{status_code=503, body='shedded'}
    end
end
```
(with a minor pitfall that it does not distinct 429 coming from backend or ratelimit filter)

**Comment by aryszka** [comment]
> (with a minor pitfall that it does not distinct 429 coming from backend or ratelimit filter)

this is actually a very good point, I wouldn't call it minor :)

**Comment by AlexanderYastrebov** [comment]
A working demo of ratelimit status/body rewrite:
```
b: Path("/backend") -> status(204) -> <shunt>;
t: Path("/test")
-> lua("
function response(ctx)
    if ctx.response.status_code == 429 then
        ctx.serve{status_code=503, body='shedded'}
    end
end")
-> ratelimit(10, "1m")  
-> setPath("/backend") -> "http://localhost:9090"
```

> this is actually a very good point, I wouldn't call it minor :)

we may think about signalling ratelimit happened in a statebag or expose "shunted" helper in lua's filter context and rely on it.

**Comment by rbarilani** [comment]
Hi, @AlexanderYastrebov @aryszka @szuecs I have opened a minimal [draft PR](https://github.com/zalando/skipper/pull/1734) to see if we want to proceed in that direction.  Let me know.

**Comment by AlexanderYastrebov** [comment]
> So as far as I understand we could create a loadShedding filter, but as far as I understand load shedding, it should limit per backend instance to protect max throughput measured for one instance.

[`backendRatelimit`](https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#backendratelimit) filter implements this.
