### ISSUE TITLE
oidcClaimsQuery filter does not work properly with strings containing spaces

### ISSUE THREAD

**Issue by abinet** [zalando/skipper#1760]
Filter with queries containing spaces do not apply properly.

Example:
`oidcClaimsQuery("/login:groups.#[==\"appX Tester\"]")` returns 200 regardless of any content of groups in id_token.

This is probably because of split function using spaces here:
https://github.com/zalando/skipper/blob/b1981c01bfd58b807dde5349b2d3110fe3ecc18d/filters/auth/oidc_introspection.go#L70

IMHO it's valid use case to use string literals with  spaces.

**Comment by AlexanderYastrebov** [comment]
Hello, I have created #1761 to allow whitespaces in query strings. 
@universam1 Could you please have a look if that makes sense?
