### ISSUE TITLE
Make HTTP response code of backendRatelimit configurable

### ISSUE THREAD

**Issue by ethercrow** [zalando/skipper#1762]
Currently other rate limiting filters support this feature.

For example, docs of `ratelimit`:

```
Parameters:

    number of allowed requests per time period (int)
    time period for requests being counted (time.Duration)
    response status code to use for a rate limited request - optional, default: 429

ratelimit(20, "1m")
ratelimit(300, "1h")
ratelimit(4000, "1m", 503)
```

Please implement the same for `backendRatelimit` for consistency.

**Comment by szuecs** [comment]
1) iirc only one ratelimit filter has this option, because other filters have an optional argument already (all client ratelimits)
2) The filter name should be load shedding, 
so not really as you write.

 I guess we can do it anyways 🤗
