### ISSUE TITLE
Bounded Load Consistent Hash Load Balancing Algorithm

### ISSUE THREAD

**Issue by cjbooms** [zalando/skipper#1769]
**Is your feature request related to a problem? Please describe.**
We plan to use the Consistent hash load balancing algorithm in a Tier One product serving API at Zalando, using the `product-id` from the request URL as input into the consistent hash load balancing algorithm.
`GET /products/{product-id}`
This will allow small pod-local caches to have high hit rates for hot products in our Catalog. However, for extremely hot products that are queried 1000s of times a second, this runs the risk of overloading a single pod with too many requests.

**Describe the solution you would like**
The Bounded Load Consistent Hash Load Balancing algorithm addresses this problem by allowing requests to spill-over into adjacent pods on the ring that are unloaded.
 https://arxiv.org/abs/1608.01350
https://medium.com/vimeo-engineering-blog/improving-load-balancing-with-a-new-consistent-hashing-algorithm-9f1bd75709ed

This ticket is to enhance the existing Consistent Hash algorithm to allow spill-over to occur. Spill-over should be consistent. If the selected pod is overloaded it should try the next pod in the ring, going around the ring until an unloaded pod is found. This will ensure high cache hits even when spill-over occurs.  

**Would you like to work on it?**
My team is starting a huge multi-month project and will need this in place. We are open to implementing, reviewing PRs, testing implementations, or any combination of above.

**Comment by AlexanderYastrebov** [comment]
Implemented by #1797
