### ISSUE TITLE
Evaluate go-lua VM for dynamically loadable predicates/filters

### ISSUE THREAD

**Issue by lmineiro** [zalando/skipper#178]
We've thought about solutions to dynamically load filters (and later predicates)

We should evaluate the integration of https://github.com/Shopify/go-lua and benchmark:
- External script load time
- Execution of a similar native Go filter/predicate

If we get interesting results we can consider a proper integration design with a specific, separate, issue.

**Comment by LappleApple** [comment]
@lmineiro How's it going with this evaluation? Should we add a label "feedback wanted"?

**Comment by szuecs** [comment]
@lmineiro I hope you agree that this was already done, if not please reopen and write what's missing, thanks
