### ISSUE TITLE
Problem with affinity

### ISSUE THREAD

**Issue by luismanuelmontoro** [zalando/skipper#1787]
Hello, i´m working on EKS and skipper are always on pending, when i have a decribe  i got that reason:

0/1 nodes are available: 1 node(s) didn't match Pod's node affinity.  

Can you help me?
---------------------------------------------------------------------

Name:                 skipper-ingress-c8577d6ff-5vlwj
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 <none>
Labels:               application=skipper-ingress
                      component=ingress
                      pod-template-hash=c8577d6ff
                      version=v0.11.40
Annotations:          kubernetes.io/psp: eks.privileged
Status:               Pending
IP:
IPs:                  <none>
Controlled By:        ReplicaSet/skipper-ingress-c8577d6ff
Containers:
  skipper-ingress:
    Image:      registry.opensource.zalan.do/teapot/skipper:v0.12.0
    Port:       9999/TCP
    Host Port:  9999/TCP
    Args:
      skipper
      -kubernetes
      -kubernetes-in-cluster
      -kubernetes-path-mode=path-prefix
      -address=:9999
      -wait-first-route-load
      -proxy-preserve-host
      -serve-host-metrics
      -disable-metrics-compat
      -enable-profile
      -enable-ratelimits
      -experimental-upgrade
      -metrics-exp-decay-sample
      -reverse-source-predicate
      -lb-healthcheck-interval=3s
      -metrics-flavour=prometheus
      -enable-connection-metrics
      -max-audit-body=0
      -histogram-metric-buckets=.0001,.00025,.0005,.00075,.001,.0025,.005,.0075,.01,.025,.05,.075,.1,.2,.3,.4,.5,.75,1,2,3,4,5,7,10,15,20,30,60,120,300,600
      -expect-continue-timeout-backend=30s
      -keepalive-backend=30s
      -max-idle-connection-backend=0
      -response-header-timeout-backend=1m
      -timeout-backend=1m
      -tls-timeout-backend=1m
      -close-idle-conns-period=20s
      -idle-timeout-server=62s
      -read-timeout-server=5m
      -write-timeout-server=60s
      -default-filters-prepend=enableAccessLog(4,5) -> lifo(2000,20000,"3s")
    Limits:
      cpu:     4
      memory:  1Gi
    Requests:
      cpu:        4
      memory:     1Gi
    Readiness:    http-get http://:9999/kube-system/healthz delay=60s timeout=5s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from skipper-ingress-token-nk4h5 (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  skipper-ingress-token-nk4h5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  skipper-ingress-token-nk4h5
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  kubernetes.io/role=worker
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                            From               Message
  ----     ------            ----                           ----               -------
  Warning  FailedScheduling  <invalid> (x2 over <invalid>)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match Pod's node affinity.

**Comment by AlexanderYastrebov** [comment]
Hi, please check deployment spec (`kubectl get ... -o yaml`) maybe there is some more clues than `kubectl describe` provides.
I've also noticed you are using an old version of Skipper, checkout https://github.com/zalando/skipper/releases for the fresh one.

**Comment by luismanuelmontoro** [comment]
I stop using the deployment and start using the daemonset, and it works, with a little change, in EKS all nodes are workers, and I delete the restriction
