### ISSUE TITLE
Add CertPool interface for dynamically updating cert pool.

### ISSUE THREAD

**Issue by mikkeloscar** [zalando/skipper#179]
Hi,

We (Team Teapot) have a use case where we want to dynamically update the RootCA cert pool used for verifying the endpoint certificate.
#### Usecase:

We have a single [skoap](https://github.com/zalando-incubator/skoap) authenticating and forwarding clients to different GKE clusters. We want to dynamically add/remove clusters and use the etcd routes backend for this. However when creating a cluster a self signed certificate is generated (by google) and we want to verify this when connecting through skoap.

The way to do this is to somehow add the certificate to the cert pool used by skipper when making a request to the endpoint. Currently skipper can only use the hosts cert pool, so you have to add it to something like `/usr/local/share/ca-certificates/` and run `update-ca-certificates` and restart skoap to actually load the new cert pool.

My idea is to add a simple `CertPool` interface to skipper and then make it possible to implement an etcd backed cert pool which can be used by skoap.

It could look something like this: https://github.com/mikkeloscar/skipper/commit/a470a5e4b3a55b05a90111afc40b1dfefff1e5bc

And a very simple etcd Cert Pool for skoap: https://github.com/mikkeloscar/skoap/commit/60c5690876181eea02e4f3b281d05011735db2af (this is just a quick hack, don't assume it's the final implementation :) )

Let me know what you think about this idea.

**Comment by lmineiro** [comment]
How different is this from using the -insecure flag? You still control the routes... Are all those self-signed certificates issued by the same CA?

It does sound like an awful amount of moving parts with a large f*up surface...

**Comment by szuecs** [comment]
From security point of view, adding a known internal CA is much better than using -insecure, because with -insecure a man-in-the-middle attack can happen without knowledge of the caller.

The dynamic part of updating a CertPool would be nice, because we have to create backends on demand that create different certificates and we have not control and influence on the backend (It's google's GKE kube-api-server).

**Comment by mikkeloscar** [comment]
> Are all those self-signed certificates issued by the same CA?

Unfortunately not.

```
Issued by:

Common Name (CN)         europe-west1-d-255788903420-cluster-teapot@1464964579
Organization (O)         <Not Part Of Certificate>
Organizational Unit (OU) <Not Part Of Certificate>
```

**Comment by aryszka** [comment]
it sounds good to me. The approach with the CertPool interface also fine. For the f*up potential: it should be possible to make the default without moving parts, and when someone uses this feature, should be well aware what they're doing.

**Comment by mikkeloscar** [comment]
Yeah, the patch I linked doesn't change the default behavior of skipper, it only adds the CertPool field to the Options struct, which you can leave out if you don't need a custom certpool.

**Comment by LappleApple** [comment]
Hey @mikkeloscar @aryszka @lmineiro @szuecs Do we still need this issue?

**Comment by mikkeloscar** [comment]
No, this is not relevant anymore.
