### ISSUE TITLE
Improve the consistentHash LB algorithm

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#1796]
There's a little bit of a weakness in the current consistentHash implementation. Since each endpoint only gets one place on the hash ring, they are unlikely to be evenly spaced on the ring, meaning some servers are likely to get the majority of requests. From looking around at e.g. envoy proxy, the solution is to give each endpoint a lot of places on the hash ring, e.g. 100 places on the ring for each endpoint

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#ring-hash

**Comment by herojan** [comment]
Some numbers I got from testing

Skipper route: 
```
route settings, reset, route: r1: Path("/products/:product_id") -> enableAccessLog(4, 5) -> lifo(2000, 20000, "3s") -> consistentHashKey("${product_id}") -> <consistentHash, "http://127.0.0.1:9001", "http://127.0.0.1:9002", "http://127.0.0.1:9003", "http://127.0.0.1:9004", "http://127.0.0.1:9005", "http://127.0.0.1:9006", "http://127.0.0.1:9007", "http://127.0.0.1:9008", "http://127.0.0.1:9009", "http://127.0.0.1:9010">
```

Ran 100k requests, /products/sku-1 to /products/sku-100000, skipper had 10 backend endpoints.

Current implementation requests per server(servers numbered 1-10):
```
  "1": "1948",
  "2": "384",
  "3": "755",
  "4": "397",
  "5": "391",
  "6": "377",
  "7": "387",
  "8": "435",
  "9": "94086",
  "10": "839"
```

If I add 100 hashes per endpoint, it's still not great since server 6 gets 27k requests

```
"1": "6877",
"2": "17112",
"3": "9764",
"4": "4665",
"5": "7824",
"6": "27360",
"7": "3146",
"8": "1108",
"9": "8247",
"10": "13896"
```

If I replace the skipper hashring with https://github.com/serialx/hashring, then we get the closest to 10k requests per server:

```
"1": "12402",
"2": "2538",
"3": "10884",
"4": "9193",
"5": "10348",
"6": "16457",
"7": "9912",
"8": "5334",
"9": "19762",
"10": "3169"
```

The best was the external hashring, but it might just have been luckier to have the hashes for the endpoints better spread out for those 10 endpoints :thinking:

**Comment by cjbooms** [comment]
One simple solution to spread the distribution would be to use addition to derive the other hashes per endpoint.

So say we want to add 10 entires for endpoint 192.168.0.1 to a `hash_ring_size` = 1,000,000:
Compute the hash of the endpoint
hash(192.168.0.1) == 799,000

Divide `hash_ring_size` by the desired number of entries per endpoint to obtain the offset between entries:
1,000,000 / 10 == 100,000

Compute the 9 additional hash entires for this endpoint (indexes 1 -> 9) using
(hash + (entry_index * offset)) % ring_size

So for the first additional entry it's:
(799,000 + (1 * 100,000)) % 1000000 == 899,000

For the 9th entry it's:
(799,000 + (9 * 100,000)) % 1000000 == 699000

**Comment by herojan** [comment]
The results for that were:
```
"1": "38289",
"2": "9295",
"3": "8219",
"4": "11532",
"5": "1520",
"6": "15213",
"7": "7464",
"8": "7019",
"9": "747",
"10": "701"
```

It's looks around the same as the 100 hashes per endpoint

**Comment by szuecs** [comment]
Did you consider https://github.com/buraksezer/consistent ?
I just read https://dgryski.medium.com/consistent-hashing-algorithmic-tradeoffs-ef6b8e2fcae8 and it looks like the one we need in your LB case. Search for "Consistent Hashing with Bounded Loads" in the blog post.

**Comment by herojan** [comment]
> Did you consider https://github.com/buraksezer/consistent ?
> I just read https://dgryski.medium.com/consistent-hashing-algorithmic-tradeoffs-ef6b8e2fcae8 and it looks like the one we need in your LB case. Search for "Consistent Hashing with Bounded Loads" in the blog post.

Nice, I'll give this one a try too. Hopefully it can just replace the existing hash ring and give us bounded loads for free

**Comment by AlexanderYastrebov** [comment]
> One simple solution to spread the distribution would be to use addition to derive the other hashes per endpoint.

If additional hashes (vnodes) on the ring are derived in uniform way like https://github.com/zalando/skipper/issues/1796#issuecomment-866923543 proposes then in case node(backend) goes away all its requests would be reassigned to another single node(backend) which may not be desirable. To avoid that vnodes should have a bit of "randomness" e.g. obtained by hashing node name and vnode index - this way requests would be reassigned to the multitude of existing nodes

**Comment by herojan** [comment]
> To avoid that vnodes should have a bit of "randomness" e.g. obtained by hashing (node name + vnode index) - this way requests would be reassigned to the multitude of existing nodes

Yeah that's what I did for the 100 hashes per node in the original comment, I edited that comment now to make it clearer
