### ISSUE TITLE
Webhook sends back 401 for all codes above 300

### ISSUE THREAD

**Issue by realsenseme** [zalando/skipper#1838]
**Describe the bug**
I am using webhook filter to redirect the request to an external authorization service which returns 401 and 403 depending on the authorization policy. But the skipper filter handles this and always returns 401 to the client.

https://github.com/zalando/skipper/blob/master/filters/auth/webhook.go#L113

**To Reproduce**
1. Create a custom service for acl based authorization with appropriate return codes ex: 401 and 403
2. Add webhook filter in the ingress to forward the request to the external service for ACL based authorization
3. Invoke the resource API with valid token with insufficient permission for the operation on the resource
4. Test with invalid token -> external service returns 401, skipper filter returns 401
5. Test with valid token but insufficient permission -> external service returns 403, skipper returns 401

**Expected behavior**
Should return the same code as received from the external service.

**Observed behavior**
Always return Unauthorized (401) for all return codes >=300 from the external service.

**Comment by szuecs** [comment]
@realsenseme sounds good to me

**Comment by AlexanderYastrebov** [comment]
The
```go
        // forbidden
	if err != nil || resp.StatusCode == 403 {
                forbidden(ctx, "", invalidScope, f.authClient.url.Hostname(), WebhookName)
		return
	}
```
will forbid on any error.
