### ISSUE TITLE
Enable remote eskip file functionality via a flag

### ISSUE THREAD

**Issue by marcinzaremba** [zalando/skipper#1842]
**Is your feature request related to a problem? Please describe.**
Currently Skipper has already [implemented](https://github.com/zalando/skipper/pull/1735) an ability to fetch eskip routes from a remote endpoint, however it is not possible to use this functionality when running Skipper as a standalone binary, namely there is no configuration flag that would enable it.

**Describe the solution you would like**
Add a flag / adopt existing flag to be able to use it

**Describe alternatives you've considered (optional)**
-

**Additional context (optional)**
-

**Would you like to work on it?**
Yes

**Comment by xavivars** [comment]
It's great there's a flag for this now 😊
