### ISSUE TITLE
Credentials folder path should detect addition and removal of files

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/skipper#1858]
**Is your feature request related to a problem? Please describe.**

Users of [`bearerinjector`](https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#bearerinjector) may configure **folders** and **files** to look secrets at via `-credentials-paths` option. 
When **folder** is configured Skipper lists all the files and re-reads their content periodically (configured via `-credentials-update-interval`).
Newly added files are not detected automatically and require Skipper restart.
Removal of pre-existing file from the folder produces periodic error log due to refresh failure.

**Describe the solution you would like**

For every configured **folder** Skipper should re-read folder content to detect newly added files.
Files removed from the **folder** should not produce errors (to be discussed).
Note that configured **file** paths should continue to produce periodic error log on file removal.
The removal of configured **folder** itself should produce periodic error log as well.

The idea is that for dynamically added/removed files users configure **folder** path and for expected static files users configure **file** path and they should see the error if expected file has been gone.

**Would you like to work on it?**
Yes

**Comment by szuecs** [comment]
What if a single instance has a missing secret file which is required to run?
Right now we would return an error and after change we would write error logs.
Maybe it's better to crash if file is not there or start shutdown procedure. 
Maybe it's also just ok to log, but it would contradict the self healing approach if we would just stop in case files are not there.
