### ISSUE TITLE
consider killing pooled connections when a route backend has changed

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#188]
when skipper is used in the role of a service broker, the backend services may change, redeployed, or new versions tested in parallel (canary). To avoid having connections, or too many connections stuck to the old service instances in the pool, the current solution is to regularly clear the idle connections with a configurable, relatively large time interval, using `http.Transport.CloseIdleConnections()`. Brute-force, but works. There can be more sophisticated solutions that would work better, though, e.g. detecting DNS changes. This issue was created to discuss the possibilities and their trade-offs. Please, feel free to share your thoughts and ideas.

**Comment by LappleApple** [comment]
Hi @aryszka, you still planning to do this? Suitable for "Help Wanted" ticket?

**Comment by aryszka** [comment]
Hi @LappleApple , yes, help is welcome. Important to know that this is really rather for consideration first before any implementation. It's kind of a design question, and it would be important to discuss this based on the usage experience collected so far. We actually have an ongoing investigation in relation to #269 that may be relevant. I try to give a description to the issue.

**Comment by szuecs** [comment]
@aryszka can we do this without having to re-implement the whole Go net/http?

**Comment by aryszka** [comment]
I don't know. Maybe hijacking the connection can be used to keep a handle on the connections. Since the generally low interest in the topic, I will close this issue now.
