### ISSUE TITLE
add another vulnerability scanner

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#1894]
We run security scanning provided by GH, but https://github.com/zalando/skipper/issues/1756 showed a tool that we might want to use ourselves: `snyk test`

There is also https://www.praetorian.com/blog/introducing-gokart/

**Comment by demonCoder95** [comment]
I've tested `snyk` locally and it works well with the repository with no vulnerabilities found. There is a [GitHub Action](https://github.com/snyk/actions/tree/master/golang) provided by the community that can very easily be added to the CI.

`snyk` setup requires a Snyk account and uses the API_TOKEN from the account to [authenticate](https://docs.snyk.io/snyk-cli/commands/auth) the GitHub Action. I've created an account and have a token but don't have the permissions to create secrets in the repository here. Someone will [`admin` privileges](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository) to the repository can add/remove secrets.

**Comment by demonCoder95** [comment]
`gokart` setup was simple so I've added a PR to add it. It did detect a SSRF vulnerability in the code, so the pipeline might fail 🤔 

```
Using config found at /Users/noor/.gokart/analyzers.yml

Revving engines VRMMM VRMMM
3...2...1...Go!

(CWE-918: Server-Side Request Forgery) Danger: possible SSRF detected

/Users/noor/skipper/net/httpclient.go:120
Vulnerable Function: [ Do(...) (*net/http.Response, error ]
      119:		}
    > 120:		return c.client.Do(req)
      121:	}

/Users/noor/skipper/net/httpclient.go:114
Source of Untrusted Input: [ Do(...) (*net/http.Response, error ]
      113:	// Authorization header.
    > 114:	func (c *Client) Do(req *http.Request) (*http.Response, error) {
      115:		if c.sr != nil && req.Header.Get("Authorization") == "" {

############################### FULL TRACE ###############################

Untrusted Input Source:/Users/noor/skipper/net/httpclient.go:114:
[ Do(...) (*net/http.Response, error ]
>>>	func (c *Client) Do(req *http.Request) (*http.Response, error) {
------------------------------------------------------------------------------

Race Complete! Analysis took 1.429372875s and 1494 Go files were scanned (including imported packages)
GoKart found 1 potentially vulnerable functions
Identified 1 potential CWE-918: Server-Side Request Forgery
```

**Comment by szuecs** [comment]
I merged gokart, but if we can not disable this false alert then I would just drop it.

**Comment by szuecs** [comment]
@demonCoder95 I added "SNYK_VULN_SCANNER_TOKEN"

**Comment by demonCoder95** [comment]
@szuecs I've added the CI step using the secret, did you populate it with an auth token already? Or did you only create the secret? As I see the pipeline step fails due to authentication error. https://github.com/zalando/skipper/actions/runs/3606708460/jobs/6078248713

**Comment by szuecs** [comment]
I guess I have to do something at snyk page.
Checking the page looks like we likely would not be in the free plan anymore, so let's close this.
