### ISSUE TITLE
Invalid test manifests

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/skipper#1902]
**Describe the bug**

The change #1646 (for #1645) introduces a test manifest(s) that are not valid, e.g.:
https://github.com/zalando/skipper/blob/1b5dd5e4e525f4b73991e1ba7f01e591d5987589/dataclients/kubernetes/testdata/ingress/service-ports/multiple-by-name.yaml#L17-L22

```
$ docker run -it -v `pwd`/dataclients/kubernetes/testdata:/fixtures --entrypoint sh garethr/kubeval -c 'find /fixtures/ingress/ -name *.yaml | xargs kubeval --strict --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master -v 1.21.6 | grep -v PASS'
WARN - /fixtures/ingress/service-ports/multiple-by-name.yaml contains an invalid Deployment (myapp-deployment) - spec.template.spec.containers.0.ports.0.containerPort: Invalid type. Expected: integer, given: string
```
It is not immediately clear what is wrong with it, it seems not just the string vs integer. The name "multiple" suggests multiple ports in use but definitions use one port. I think we would need to understand the intent and fix the test suite accordingly.

**Expected behavior**

Manifests pass validation

**Comment by szuecs** [comment]
`grep -rl 'containerPort: web' dataclients/kubernetes/testdata | xargs sed -i 's/containerPort: web/containerPort: 8080/'`
fixed in ingress v1

**Comment by AlexanderYastrebov** [comment]
@szuecs I think it is not only about string vs ingress, the definition does not look clear. If we replace port then it matches 100% with [multiple-by-value.yaml](https://github.com/zalando/skipper/blob/1b5dd5e4e525f4b73991e1ba7f01e591d5987589/dataclients/kubernetes/testdata/ingress/service-ports/multiple-by-value.yaml#L21) so why we have two is not clear. The naming is also misleading.

**Comment by szuecs** [comment]
@AlexanderYastrebov I think this is a leftover from the time when we had an issue because we did not fully understood the service port mappings

**Comment by bl1nk** [comment]
> I think it is not only about string vs integer

I think it was! However I am not sure what "multiple" refers to here.

I agree that "multiple-by-name.yaml" can be deleted as it would match "multiple-by-value.yaml" when fixed.
