### ISSUE TITLE
Access query parameters in the `FilterContext`

### ISSUE THREAD

**Issue by sandor-nemeth** [zalando/skipper#1915]
**Is your feature request related to a problem? Please describe.**
For filters it would be beneficial to have a streamlined access to the query parameters. For example that would enable filters to provide path transformations based on query parameters.

Example:
```
/path?param1=value1&param2=value2 --rewrite--> /newPath?otherParameter=${request.query.param1}
```

**Describe the solution you would like**
The `FilterContext` interface should have a `QueryParam(string) string` method that provides access to query parameters.

**Describe alternatives you've considered (optional)**
Filters could access the query parameters from `FilterContext.Request()` or `FilterContext.OriginalRequest()` - but it would be more elegant to provide an accessor.

**Additional context (optional)**
N/A

**Would you like to work on it?**
Yes

**Comment by AlexanderYastrebov** [comment]
As for the feature request I am not sure it worth extending the interface as one may get query para as simple as 
```go
ctx.Request().URL.Query().Get(q)
```

**Comment by sandor-nemeth** [comment]
We are upgrading a filter to return a custom/special URL when a header is provided, but otherwise apply the standard redirection rules: 

```
Path("/path")
  -> customFilter("zal://some_url?param=${request.query.param}")
  -> setPath("/some_path")
  -> "http://backend-system.svc"
```

And then providing `X-Custom-Filter: true` in a request header would result in returning the url defined in the `customFilter`. 

As for the feature request you are correct, we can reach it using the way described, the proposal is to provide a more concise and explicit way to do it (`ctx.QueryParam(q)` instead of the above). It is definitely a nice-to-have and we could work around it.

**Comment by szuecs** [comment]
@sandor-nemeth the skipper way would be to match the condition you require with predicates and to do the changes to requests/response with filters. We also do not provide explicit OR matching, because this can be done with adding just another route.

There is also https://opensource.zalando.com/skipper/reference/backends/#dynamic-backend which could help you, too. Not sure, maybe you can tell us more in our internal chat. For now I would close this issue, because I think it's a won't fix.

**Comment by AlexanderYastrebov** [comment]
@sandor-nemeth  You may also use https://github.com/zalando/skipper/blob/e5a6fb5139220c56ad4ad31f7809ae3dccb3754e/eskip/template.go#L63 
if that fits your needs (`FilterContext` implements `TemplateContext`).
