### ISSUE TITLE
Broken link in SECURITY.md to security form

### ISSUE THREAD

**Issue by Shegox** [zalando/skipper#1929]
**Describe the bug**
When looking at the [SECURITY:md](https://github.com/zalando/skipper/blob/29b29fc9f4c986059f7e2c22b87ec07b9c3d27c8/SECURITY.md?plain=1#L4-L6) the link to the security form leads to a contact page without the security form.

**To Reproduce**
1. Go to https://github.com/zalando/skipper/blob/29b29fc9f4c986059f7e2c22b87ec07b9c3d27c8/SECURITY.md?plain=1#L4-L6
1. Click on https://corporate.zalando.com/en/services-and-contact#security-form

**Expected behavior**
 To find a security form

**Observed behavior**

No security form (and I wasn't able to find one either on the overall page nor via google).

--- 

Also note that [other repositories and their Security.md in the zalando organization](https://github.com/search?q=%22https%3A%2F%2Fcorporate.zalando.com%2Fen%2Fservices-and-contact%22+org%3Azalando&type=code) are affected as well. Might be worth updating it across all of the repos.

**Comment by szuecs** [comment]
@Shegox thanks, I will check with internal security team that we have something that works reliable. If not we need to create a workaround with a security mailinglist.

**Comment by conmurray** [comment]
Link to ServiceNOW ticket that this os being worked on by SOC team

https://zalandoprod.service-now.com/nav_to.do?uri=%2Fsn_si_request.do%3Fsys_id%3D84858512db5049508eb3eacbd396194b%26sysparm_view%3D%26sysparm_domain%3Dnull%26sysparm_domain_scope%3Dnull%26sysparm_record_row%3D1%26sysparm_record_rows%3D308%26sysparm_record_list%3Dactive%253dtrue%255eORDERBYDESCsys_created_on

**Comment by szuecs** [comment]
Since we only provide a workaround right now

**Comment by szuecs** [comment]
@conmurray I get a 404 response by your pasted link. Maybe handle it first internally before we paste the link here.

**Comment by szuecs** [comment]
@Shegox we updated the SECURITY.md file to fallback to send an e-mail to maintainers. We have to rely on the current not working process, but I hope you agree it makes sense to inform maintainers if you found a security issue in our code base. Thanks for the heads up and sorry that it takes that long to reply!

**Comment by Shegox** [comment]
Fully agree, I think it makes sense to have a email in there anyway.
I didn't found a security issue, but was more looking for inspiration on how other teams/projects handle their security disclose process. While doing that I found the broken link/contact and opened an issue to make you aware :)

**Comment by szuecs** [comment]
Ok great thanks!
