### ISSUE TITLE
OIDC: Aggregated and Distributed Claims

### ISSUE THREAD

**Issue by universam1** [zalando/skipper#1955]
**Is your feature request related to a problem? Please describe.**

For OIDC (using filter `oauthOidcAnyClaims` ) with _Azure AD_ we are seeing users who are member of many groups to run into a [clipped groups token behaviour](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#groups-overage-claim) of Azure. 
The `groups` claim is replaced by `hasToken` and a pointer to the Graph API.
That breaks subsequent filter `oidcClaimsQuery` for group membership, as the expected claim of groups is empty

**Describe the solution you would like**
Skipper detects this flag `hasToken` and performs a lookup to the Graph API, retrieving the actual list of groups, storing in the statebag or cookie.
It could be a configurable option to perform this lookup.

**Additional context (optional)**
Would it make sense to implement this lookup to the Graph API, ~granted this looks like a Azure-ish behaviour~?

Which filter would be the proper place to extend?

**Would you like to work on it?**
Potentially, with support.

**Comment by universam1** [comment]
It as actually a well defined standard behaviour: https://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims

**Comment by webframp** [comment]
If it's part of the oidc standard then it seems potentially useful to implement to me. Interestingly both referenced example implementations look like they were able to be implemented using `golang.org/x/oauth2` without requiring any azure specific implementation library. That's a nice design goal I would think.

Although some nice libraries like https://github.com/manicminer/hamilton/ exist, it would not seem very nice to require that just to support this feature.

**Comment by szuecs** [comment]
If it's part of the spec let's build it of course!
So I guess we should put the aggregated data into our container that we pass to stateBag which can queried via `oidcClaimsQuery` or how do you think to integrate it?
