### ISSUE TITLE
add goleak tests and check if it makes sense

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#1989]
Maybe helpful https://pkg.go.dev/go.uber.org/goleak

**Comment by alexandreliberato** [comment]
@szuecs may I work on this issue?

**Comment by szuecs** [comment]
Sure would be great!

**Comment by alexandreliberato** [comment]
Great! :)

I have a question about the existent tests:
- Is intentional that some test file use a test package(_test) and other no? That happens in the same package structure:
![image](https://user-images.githubusercontent.com/300424/183304426-04461832-b810-4acf-802c-6fe76e2265ff.png)
and
![image](https://user-images.githubusercontent.com/300424/183304446-8065c30a-845a-4e27-9ea7-50e4d7fa558e.png)

**Comment by alexandreliberato** [comment]
My analysis on it:
  - [x] what: a library the detect unexpected gorountines
  - [x] why: prevent resources leakage and unexpected behaviors(bugs/defects)
  - [x] how: use in unit tests, if there is any error: "unexpected goroutines found"
  - [x] when: when you have multiple use of channels
  - [x] where: used by test or test package

Yes, I think that would be nice to use this library, after some tests I'd found leaked goroutines:
![image](https://user-images.githubusercontent.com/300424/183308277-c595708f-218f-4eda-8640-68d67af0d6ae.png)

**Comment by alexandreliberato** [comment]
I have other question, is there any initiative to run the tests in parallel?

**Comment by szuecs** [comment]
> Great! :)
> 
> 
> 
> I have a question about the existent tests:
> 
> - Is intentional that some test file use a test package(_test) and other no? 

Yes basically think about "whitebox" vs "blackbox" testing. If you are in the same package you can use internal functions and if not you are user of the library interface.

**Comment by szuecs** [comment]
> I have other question, is there any initiative to run the tests in parallel?

Yes, but if you run with race detector it runs test not concurrently as far as I remember.

**Comment by szuecs** [comment]
> My analysis on it:
> 
>   - [x] what: a library the detect unexpected gorountines
> 
>   - [x] why: prevent resources leakage and unexpected behaviors(bugs/defects)
> 
>   - [x] how: use in unit tests, if there is any error: "unexpected goroutines found"
> 
>   - [x] when: when you have multiple use of channels
> 
>   - [x] where: used by test or test package
> 
> 
> 
> Yes, I think that would be nice to use this library, after some tests I'd found leaked goroutines:
> 
> ![image](https://user-images.githubusercontent.com/300424/183308277-c595708f-218f-4eda-8640-68d67af0d6ae.png)
> 
> 

It can be also false positive of course but it's great to check if it is or not.

**Comment by AlexanderYastrebov** [comment]
Leak detection using https://github.com/AlexanderYastrebov/noleak added by https://github.com/zalando/skipper/pull/2128
