### ISSUE TITLE
Improve route prioritization

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#199]
Currently priority routes are supported only in the form of hard coded extensions, and this makes their maintenance rigid. To benefit from the dynamic configuration in case of the priority routes, find a way to express priorities in the route configuration.

**Comment by LappleApple** [comment]
@aryszka @szuecs @mo-gr @Raffo @lmineiro Do you want to add a "Help Wanted" label here?

**Comment by aryszka** [comment]
hmm.. we had a pull request implementing this, but we decided not to merge it, because we can avoid a situation of "priority race" and keep the design simpler. Closing.
