### ISSUE TITLE
Preserve empty User-Agent header 

### ISSUE THREAD

**Issue by JordanSussman** [zalando/skipper#1994]
**Describe the bug**

Requests sent through skipper with an empty `User-Agent` header have the value of `Go-http-client/1.1` added instead of preserving the empty value.

**To Reproduce**
Add context, for example:

1. Start skipper in proxy mode with `./bin/skipper -inline-routes='r1: * -> <roundRobin, "http://127.0.0.1:9001">' --address :9999`
2. Create a http server to print out the `User-Agent` header

```go
package main

import (
	"fmt"

	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()
	r.GET("/foo", func(c *gin.Context) {
		fmt.Println(c.Request.UserAgent())
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})
	r.Run(":9001") // listen and serve on 0.0.0.0:9001
}
```

3. Start the http server

```sh
go run main.go
```

4. Send requests to skipper

```
curl http://localhost:9999/foo
curl http://localhost:9999/foo -H "User-Agent: "
```

Logs from the last step look like:

```
curl/7.64.1
[GIN] 2022/04/13 - 13:49:04 | 200 |      67.276µs |       127.0.0.1 | GET      "/foo"
Go-http-client/1.1
[GIN] 2022/04/13 - 13:49:38 | 200 |      76.356µs |       127.0.0.1 | GET      "/foo"
```

**Expected behavior**

Skipper preserves the empty `User-Agent` header.

**Observed behavior**

Skipper modifies `User-Agent` header to be `Go-http-client/1.1`.

**Comment by AlexanderYastrebov** [comment]
This is similar to https://github.com/golang/go/issues/15524

**Comment by AlexanderYastrebov** [comment]
@JordanSussman Thank you for detailed report!

**Comment by JordanSussman** [comment]
> @JordanSussman Thank you for the detailed report!

Thanks! Any chance the implementation you introduced will also change the behavior for the Kubernetes ingress?

**Comment by AlexanderYastrebov** [comment]
> will also change the behavior for the Kubernetes ingress?

The change is in the common proxy component so k8s backends should stop seeing default go user agent.

**Comment by AlexanderYastrebov** [comment]
> will also change the behavior for the Kubernetes ingress?

The change is in the common proxy component so k8s backends should stop seeing default go user agent.
