### ISSUE TITLE
Skipper fails upgrade/websocket request with pure ipv6 backend

### ISSUE THREAD

**Issue by RasmusWernerLarsen** [zalando/skipper#1997]
**Describe the bug**
We're using an IPv6 only kubernetes cluster running on AWS eks with skipper as ingress controller. Normal non-websocket traffic works as expected to all endpoints, but websocket traffic fails with the following error.

> {"level":"error","msg":"Error connecting to backend: dial tcp: address 2a05:d018:d54:c508:e3d9::8:3000: too many colons in address","time":"2022-04-19T18:32:12Z"}

The ipaddress of the backend (pod) in question is 2a05:d018:d54:c508:e3d9::8 and the service port is 3000, so somehow it looks like an extra ":" is added to the end. The service is grafana in this case, but we're seeing this with all websocket connections. The same backend can be connected to using plain http (well https), so everything works except websocket connections, it seems to be very specific to the upgrade request.

I've dug a bit into the error and it can only come from the "serveHTTP" function in upgrade.go, which is specific to websocket connections, so this seems to be a bug specific to websocket + ipv6 backends. I guess I am a bit on the bleeding edge here, so this is probably just obscure enough that I'm the first to hit this.

**To Reproduce**
1. Create an IPv6 only backend with a websocket backend.
2. Add a skipper ingress in front.
3. Try to do a websocket connection to the backend.

**Expected behavior**
A connection is established.

**Observed behavior**
> {"level":"error","msg":"Error connecting to backend: dial tcp: address 2a05:d018:d54:c508:e3d9::8:3000: too many colons in address","time":"2022-04-19T18:32:12Z"}
The connection is rejected with a 503, service unavailable.

**Comment by szuecs** [comment]
Log line is https://github.com/zalando/skipper/blob/master/proxy/upgrade.go#L78
and this seems to be wrong for IPv6 https://github.com/zalando/skipper/blob/494ca96bc8f0fb1f6cf699a6fa22defd4d30b8dd/proxy/upgrade.go#L232

go doc net.Dial shows how to set this up for IPv6:
```

    Examples:

        Dial("tcp", "golang.org:http")
        Dial("tcp", "192.0.2.1:http")
        Dial("tcp", "198.51.100.1:80")
        Dial("udp", "[2001:db8::1]:domain")
        Dial("udp", "[fe80::1%lo0]:53")
        Dial("tcp", ":80")
```

As far as I see we should replace it with `net.JoinHostPort(host, port string)`

**Comment by RasmusWernerLarsen** [comment]
@szuecs - I would be very happy to test it and thank you for the absurdly fast response.

**Comment by szuecs** [comment]
@RasmusWernerLarsen haha, you were lucky because I just checked emails and had a little time to check. Of course we try to address all bugs ASAP as we can, but I am all in agreeing with you `absurdly fast response`. :)
Test image is with a likely non working fix is registry.opensource.zalan.do/teapot/skipper-test:pr-1998-1

**Comment by szuecs** [comment]
@RasmusWernerLarsen can you please paste a result of `kubectl get endpoints <name> -o json` any endpoint that has a single IPv6 address is enough to understand the issue. It might be a problem of our assumption that we get `[ab::cd]` as IPv6 address from the kubernetes dataclient configured in our load balancer backend.

**Comment by RasmusWernerLarsen** [comment]
I can confirm that I see the exact same behavior with registry.opensource.zalan.do/teapot/skipper-test:pr-1998-1.

I think you are on the right track with the endpoints, here's data from the endpoint in question, which as you suspect does not seem to have the [] notation.

Btw, this is a kubernetes 1.22 cluster.

`{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "v1",
            "kind": "Endpoints",
            "metadata": {
                "annotations": {
                    "endpoints.kubernetes.io/last-change-trigger-time": "2022-04-17T08:53:25Z"
                },
                "creationTimestamp": "2022-04-17T08:26:44Z",
                "labels": {
                    "app.kubernetes.io/instance": "grafana",
                    "app.kubernetes.io/managed-by": "Helm",
                    "app.kubernetes.io/name": "grafana",
                    "app.kubernetes.io/version": "8.4.6",
                    "helm.sh/chart": "grafana-6.26.2"
                },
                "name": "grafana",
                "namespace": "grafana",
                "resourceVersion": "2394050",
                "uid": "2d192f04-d200-4f9d-bceb-316c3cbb4d3c"
            },
            "subsets": [
                {
                    "addresses": [
                        {
                            "ip": "2a05:d018:d54:c508:e3d9::8",
                            "nodeName": "ip-10-32-14-180.eu-west-1.compute.internal",
                            "targetRef": {
                                "kind": "Pod",
                                "name": "grafana-646b5bf999-24wqf",
                                "namespace": "grafana",
                                "resourceVersion": "2394049",
                                "uid": "e9c09208-f459-4de1-8ee8-806a18923e0f"
                            }
                        }
                    ],
                    "ports": [
                        {
                            "name": "service",
                            "port": 3000,
                            "protocol": "TCP"
                        }
                    ]
                }
            ]
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}`

**Comment by szuecs** [comment]
@RasmusWernerLarsen registry.opensource.zalan.do/teapot/skipper-test:pr-1998-3 should fix the problem, would be great if you can report if it works for you.

**Comment by RasmusWernerLarsen** [comment]
I can confirm that websocket connections to ipv6 works with registry.opensource.zalan.do/teapot/skipper-test:pr-1998-3 :)

**Comment by szuecs** [comment]
Great, then we will release as soon as @AlexanderYastrebov will have the time to review. I guess tomorrow :)

**Comment by szuecs** [comment]
Releases are automated: https://github.com/zalando/skipper/releases/tag/v0.13.202
