### ISSUE TITLE
rewrite error format string %v to %w

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#2015]
All cases that use `fmt.Errorf("...: %v", err)` should be replaced with `fmt.Errorf("...: %w", err)`

**Comment by demonCoder95** [comment]
PR is up for the refactor. Also, I saw many instances of `fmt.Errorf` where `error` type is casted as `%s`, is that okay? 🤔

**Comment by demonCoder95** [comment]
The PR has been merged so we can close this issue now. @szuecs
