### ISSUE TITLE
document redis autoscaling

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#2043]
https://github.com/zalando/skipper/pull/2009 added redis based swarm autoscaling possibility
We lack in documentation for this feature:
- [ ] kubernetes dataclient docs https://opensource.zalando.com/skipper/kubernetes/ingress-controller/#redis-based
- [ ] swarm redis tutorial https://opensource.zalando.com/skipper/tutorials/ratelimit/#redis-based-cluster-ratelimits

**Comment by trkohler** [comment]
I have briefly went through docs and haven't found mention on how skipper handles redis swarm, so it must mean the issue is still relevant?
