### ISSUE TITLE
Use checker ruleguard and semgrep

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#2055]
https://github.com/dgryski/semgrep-go code quality checker which make sense to use/test

**Comment by demonCoder95** [comment]
Tried to run `ruleguard` but it's currently known to be broken for repositories with multiple go modules and the effort needed to make it compatible is a lot. Have to import it as dependency in every package.

```bash
ruleguard: load rules: parse rules file: typechecker error: /Users/noor/semgrep-go/ruleguard.rules.go:6:8: could not import github.com/quasilyte/go-ruleguard/dsl (can't find import: "github.com/quasilyte/go-ruleguard/dsl")
```

Some references: https://github.com/quasilyte/go-ruleguard/issues/253

**Comment by szuecs** [comment]
@demonCoder95 can you try to run semgrep without ruleguard or is this a hard dependency?

**Comment by demonCoder95** [comment]
I can try running it without ruleguard, will update.

**Comment by demonCoder95** [comment]
I was able to run it locally successfully, now created a PR to test it in our CI. The PR is only for semgrep for the time, since running ruleguard had issues and they can be run independently.

**Comment by demonCoder95** [comment]
Since the PR has been merged, we can close this issue now.
