### ISSUE TITLE
Replace matched regex in Response header

### ISSUE THREAD

**Issue by ioanacraciun** [zalando/skipper#2071]
**Is your feature request related to a problem? Please describe.**
Currently, as part of the Skipper Filters, only the `modRequestHeader` is provided. It replaces all matched regex expressions in the given request header. I would need to replace an expression in the response header, in my use case `Location`.

**Describe the solution you would like**
It would be useful to have a counterpart filter for `modRequestHeader`, except for response headers.

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Would you like to work on it?**
No

**Comment by szuecs** [comment]
Sound good

**Comment by RomanZavodskikh** [comment]
Resolved in PR above.
