### ISSUE TITLE
setPath filter

### ISSUE THREAD

**Issue by mo-gr** [zalando/skipper#208]
It is a very common use case to just set the path instead of modding it. This happens for example on every route to a layout service.

So instead of writing `modPath(".*", "/new/path")` I would prefer to be able to write `setPath("/new/path")` instead to avoid unnecessary boilerplate of repeating `".*",` over and over again.

**Comment by lmineiro** [comment]
My initial instinct is to vote against this feature. It'd be the first time we change completely from the read-only nature of predicates which, until now, rely completely on the expectation that the request used for matching was, indeed, the request sent from the client.

This predicate is a clear hybrid of Predicate + Filter and challenges this current design separation.

**Comment by lmineiro** [comment]
I wrote something and even voted against it because the fact that you mentioned "predicate" in the issue title never left my mind. You mean filter, right?

**Comment by mo-gr** [comment]
yes, I meant filter... sorry... will change

**Comment by grassator** [comment]
Already implemented and available.
