### ISSUE TITLE
Add an option to override the route using k8s endpoints behaviour

### ISSUE THREAD

**Issue by peterklijn** [zalando/skipper#2089]
**Is your feature request related to a problem? Please describe.**

It would be nice if the design decision of routing traffic via Kubernetes Endpoints can be overwritten, and instead service addresses can be used.

**Describe the solution you would like**

Add an option that allows us to override the default behaviour. When provided, it will use `eskip.Route -> BackendType: eskip.NetworkBackend` instead of `eskip.Route -> BackendType: eskip.LBBackend`. If the option is not provided, nothing will change.

**Describe alternatives you've considered (optional)**

**Additional context (optional)**
A draft PR can be found here: https://github.com/zalando/skipper/pull/2088

**Would you like to work on it?**
Yes

**Comment by peterklijn** [comment]
Thanks for the quick reply 🚀 

**In short**

We expect that switching to service addresses to reduce CPU spikes in Skipper caused by updated routes.

**Detailed**

We noticed a big increase in CPU usage when we started using the Kubernetes Ingresses directly in Skipper.

We started using a [Route service](https://github.com/zalando/skipper/tree/master/routesrv), and use a custom `routing.DataClient` that only updates the routes in Skipper if the eskip routes served by the Route Service change, but noticed that the routes change frequently because of the downstream microservices autoscaling up and down all the time.

By switching to k8s service addresses we expect to see the eskip routes change less frequent, therefore reducing the number of CPU spikes in skipper that happen when Routes are updated. 


Additionally it would prevent the chance of requests failing due to rollouts (described here: https://github.com/zalando/skipper/issues/652) without having downstream applications specify a preStop hook, but we have not observed these as we have not switched production traffic to routes coming from Kubernetes ingresses (we're in the middle of testing this switch)

I hope this makes sense, if not I'm happy to provide more details 🙂

**Comment by szuecs** [comment]
We just create the preStop hook via admission webhook in kubernetes, all applications get this for free.

I wonder a bit about CPU usage.
Can you share how you run skipper-ingress hpa+deployment or daemonset, what CPU resources you assign to skipper?
Maybe you can share data before/after CPU graph or so, best would be pprof to see that it's actually the dataclient and not something else?

Great to see that people start to use routesrv. We have some changes there in the pipeline. Routesrv should be able to create all routes and skipper-ingress will just be the dumb data plane serving the pre-calculated routes. Right now there is a bit of split depending on features you use.

**Comment by peterklijn** [comment]
> > It would be nice if the design decision of routing traffic via Kubernetes Endpoints can be overwritten, and instead service addresses can be used.
> 
> Hello, thank you for raising this. What is the usecase you need it for?

In addition to the above, we have an additional reason for needing this functionality, but this is specific to our infrastructure.

We have multiple Kubernetes clusters that together form a platform, and use Kubernetes Cluster Federation using Istio's network magic to bridge the gap.

We run a RouteSrv per cluster (we have 7 clusters) and aggregate the routes in a single Skipper deployment in only one cluster, which means that most of the Kubernetes Endpoint IPs cannot be called from the cluster where Skipper runs. We use Istio's networking layer to allow secure cross cluster communication, so we have no choice but to use service addresses.

I should've started with this, but we were still running tests to double confirm that inter cluster communication is not possible.

**Comment by peterklijn** [comment]
Hi @szuecs & @AlexanderYastrebov,
Did you have some time to look at my replies? Please let me know if there's anything unclear about it, I'm happy to clarify further 🙂

**Comment by peterklijn** [comment]
Thanks @szuecs, I think so as well.
Does that mean that I can polish up the draft PR: https://github.com/zalando/skipper/pull/2088, so it can be ready for review?

**Comment by szuecs** [comment]
Yeah let's do it.
Please rename the option for example like ForceKubernetesService which defaults to false.

**Comment by AlexanderYastrebov** [comment]
@peterklijn 
> Using hashing is quite expensive (more than expected), but a lot lower than parsing the eskip routes (expected)

There is some work has been started to support Etag which would eliminate response body if routing table did not change, see #2093

**Comment by peterklijn** [comment]
Thanks @AlexanderYastrebov, Nikhil is part of my team ;) 

Thanks for your help, I'll close this issue as the PR is merged 🚀
