### ISSUE TITLE
Configurable ratelimit failure mode

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/skipper#2094]
**Is your feature request related to a problem? Please describe.**

Cluster ratelimit implementation fails open in case of Redis error
https://github.com/zalando/skipper/blob/7ac768a3370f46bc417437f5a9f5f64160a039ce/ratelimit/redis.go#L130-L132

which makes sense to prevent/postpone cascading failure in case when Redis is struggling.

Users of ratelimit filters should be able to select failure mode per route, e.g. reject requests instead of passing them through.

**Describe the solution you would like**

Add a filter to configure failure mode, something like:

```
* -> ratelimitControl("fail", "closed") -> clusterClientRatelimit("groupA", 10, "1h") -> "https://example.com"
```

**Describe alternatives you've considered (optional)**

Add failure mode configuration as a ratelimit filter argument.

**Additional context (optional)**

Consider supporting `cluster*Ratelimit` as well as `backendRatelimit` filters.

**Would you like to work on it?**

Yes

**Comment by lehnerm** [comment]
What led you to choose the filter solution over the argument solution? Generally, I don't have concerns with either approach.

**Comment by AlexanderYastrebov** [comment]
> What led you to choose the filter solution over the argument solution?

Ratelimit filters already have quite a few arguments so I'm inclined to decouple ratelimit config from control config this way

**Comment by szuecs** [comment]
@lehnerm I would say usability, because some ratelimit filters have optional arguments and then you would need to have a chosen value X that would mimic the default for the current optional setting. This makes usage also a bit ugly.
