### ISSUE TITLE
Support Etag for `routesrv` to eliminate response body if routing table did not change

### ISSUE THREAD

**Issue by nikhil88877** [zalando/skipper#2107]
**Is your feature request related to a problem? Please describe.**
Send an empty body with `StatusNotModified` when the routing table has not changed. This will make the response very efficient to process as most of the calls should result in `StatusNotModified`

**Describe the solution you would like**
Using [Etag HTTP response header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) to identify a specific version of a routing table. The client will store this cache and in the follow-up, requests send an additional header [If-None-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) and if this header matches with the current state, `routesrv` returns `StatusNotModified`  with an empty header.

This is a classic implementation HTTP [If-None-Match](https://httpwg.org/specs/rfc9110.html#field.if-none-match) protocol, which makes the request conditional on a recipient cache

**Would you like to work on it?**
Yes

**Comment by szuecs** [comment]
Now we need only to make sure our eskip remotefile dataclient leverages the Etag.
Do you want to create a PR for this @nikhil88877 ?

**Comment by nikhil88877** [comment]
> Now we need only to make sure our eskip remotefile dataclient leverages the Etag. Do you want to create a PR for this @nikhil88877 ?

Sure

**Comment by szuecs** [comment]
I created the follow up issue.
