### ISSUE TITLE
Set a name for Kubernetes data client to use it as part of a route ID 

### ISSUE THREAD

**Issue by azarakovskiy** [zalando/skipper#2126]
**Is your feature request related to a problem? Please describe.**
We are using the `routesrv` in a couple of Kubernetes clusters. Each `routesrv` loads RouteGroups from its cluster, and then there is a centralized Skipper deployment that loads the results from all `routesrv` from all clusters. 

RouteGroups are created by microservices' deployments. They would have a name like `<microservice name>-route-group`.

There is a possibility that the same microservice would be deployed to different clusters. For the centralized Skipper, the end result would be seen as two routes with the same ID. Therefore we want to add the name of that cluster to it. However, we also want to avoid microservices to be aware of our setup. In other words, microservice shouldn't add any cluster information to an RG ID.

**Describe the solution you would like**
Kubernetes Cluster Client has a new field `name` that is passed to it via Options. If not set, it defaults to `default` or an empty string. It is used as a part of RG ID in `rgRouteID(...)` and the end result looks like `kube_rg__<cluster name>__<namespace>__<route group name>__<subName>__<backend index>_<route index>`

**Describe alternatives you've considered (optional)**
<empty>

**Additional context (optional)**
<empty>

**Would you like to work on it?**
Yes

**Comment by szuecs** [comment]
Interesting setup :)
Sounds like a good idea to add the cluster in your case.
Beware that route ID can only contain `[a-z0-9_]+`.
And please signoff commits (DCO), thanks.

**Comment by AlexanderYastrebov** [comment]
> Kubernetes Cluster Client has a new field name that is passed to it via Options.

I propose we implement it differently by adding a flag (e.g. `-route-id-prefix`) and a route pre-processor to the `routesrv` that would prepend prefix to route ids.
This would not change k8s dataclient and will work for other route sources that we may add to the `routesrv` in the future (e.g. `-inline-routes` or `-routes-file` for static routes)

**Comment by azarakovskiy** [comment]
Thanks @szuecs and @AlexanderYastrebov for your fast reply :)

> Interesting setup :) Sounds like a good idea to add the cluster in your case. Beware that route ID can only contain `[a-z0-9_]+`. And please signoff commits (DCO), thanks.

The "interesting setup" involves a bit of irrelevant history, but yeah, interesting :)
Thanks for the warning, I was aware of that, but thanks anyway. And I'll sign off the commits, all going to be shiny, I only wanted to quickly show you guys a draft I've got.

> I propose we implement it differently by adding a flag (e.g. -route-id-prefix) and a route pre-processor to the routesrv that would prepend prefix to route ids.

Let me take a look at this approach and see how it would work. I wasn't aware of pre-processors.

Also, is your proposal something I can choose between and my approach, or do you believe it's the way to go and I implement it your way? I don't have a preference at the moment I am typing this message. :)

**Comment by AlexanderYastrebov** [comment]
> Also, is your proposal something I can choose between and my approach, or do you believe it's the way to go

The pre-processor has a huge advantage that it does not care about source of routes. If you want to implement it on the datasource level then we would need to have it in every datasource. Grant filter route is added by another preprocessor so its not even a datasource.

> I couldn't quickly see where other flags are parsed to do the same.

Its a bit convoluted, I think we reuse flags for skipper and routesrv so if we add a new flag it would be available to both.
We can ignore the flag in skipper or implement id rewriting as well (not sure if it is useful)

https://github.com/zalando/skipper/blob/98e7485cb93fe9c578093ba83d12040cc6258321/config/config.go#L546
https://github.com/zalando/skipper/blob/98e7485cb93fe9c578093ba83d12040cc6258321/config/config.go#L636

> Also, PreProcessor interface's docs [say that it's experimental](https://github.com/zalando/skipper/blob/98e7485cb93fe9c578093ba83d12040cc6258321/routing/routing.go#L261). Do you intend to keep it?

We (and likely library users) have a lot of stuff based on pre-processors, I doubt we can easily remove them.

**Comment by szuecs** [comment]
Let's get rid of the "experimental" mark, because it's has proven very useful. https://github.com/zalando/skipper/pull/2133

**Comment by azarakovskiy** [comment]
Ehm, a week ago we learned that our company will be ceasing business, and therefore this feature will not be needed anymore 😅  🙈 
I closed the draft PR I made and won't be finishing it.

Do you think this feature might be useful to anyone else, or shall I close the ticket?

**Comment by szuecs** [comment]
You can close it and if someone needs it we can reopen it.
Thanks for your contributions!
