### ISSUE TITLE
refactor: drop ctx!=nil check

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#2136]
In [ratelimit/redis.go](https://github.com/zalando/skipper/pull/2129/files/515f07205b67cfb82d3be35062fbe6691ba9c39b#diff-9f840da285472995967468bfc2bd84e04021dcd09b65b5e747b0a6055fad1182)
there is 
```
func parentSpan(ctx context.Context) (opentracing.Span, bool) {
	if ctx == nil {
```

ctx can be nil in case we shortcut some request creation in tests.
In order to delete the nil check we should refactor all tests that break if we drop the nil check.
We should then use context.Background for example to create a valid context.

**Comment by MustafaSaber** [comment]
Is this still valid? Tests doesn't fail

**Comment by AlexanderYastrebov** [comment]
See
https://github.com/zalando/skipper/blob/a278dae1d09c8c2390bfa1bc0808322883eedfd7/ratelimit/redis.go#L80-L87

The code checks for nil context. In practice this context is the https://pkg.go.dev/net/http#Request.Context which is never nil so this check should be removed. Once we remove this check tests may start to fail and if so, they'd need to be fixed.

**Comment by MustafaSaber** [comment]
I removed it and ran the tests but it didn't fail, that's why I'm asking.

**Comment by AlexanderYastrebov** [comment]
Ok, then please create a PR :)
