### ISSUE TITLE
Tokeninfo connection error response

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/skipper#2140]
When Skipper has connection errors to tokeninfo, the response status code should be 500 and not 401

**Comment by AlexanderYastrebov** [comment]
Or at least operator should be able to tell apart invalid token from token info connection errors.
AuthClient returns `errInvalidToken` on any error
https://github.com/zalando/skipper/blob/405acf62daf17b483a4658a0a84671979aa8a961/filters/auth/authclient.go#L116-L125
so filter never logs `Error while calling tokeninfo`
https://github.com/zalando/skipper/blob/405acf62daf17b483a4658a0a84671979aa8a961/filters/auth/tokeninfo.go#L321-L331

**Comment by szuecs** [comment]
@AlexanderYastrebov not sure if we should leak this to the client. Maybe better to have a generic error message to the client and fix the issue by logging the reason.

**Comment by AlexanderYastrebov** [comment]
@szuecs Agree, the client gets response from `unauthorized(ctx, "", reason, f.authClient.url.Hostname(), "") `, lets keep it like that for all errors. In the authClient we may return different error for 5xx token info response and have it logged.
