### ISSUE TITLE
Deprecate Jaeger Tracer

### ISSUE THREAD

**Issue by demonCoder95** [zalando/skipper#2153]
It was discovered [during refactor](https://github.com/zalando/skipper/pull/2151#discussion_r1024535936) from `go.uber.org/atomic` to `sync/atomic` that the former is still a part of the dependencies. These are derived indirectly from the [`jaeger`](https://github.com/zalando/skipper/tree/master/tracing/tracers/jaeger) module in the tracer package.

From the [official documentation](https://www.jaegertracing.io/docs/1.39/client-libraries/#deprecating-jaeger-clients), it is announced that `jaeger` tracer is being deprecated in favour of OpenTelemetry SDKs and therefore we have to deprecate and remove it from here as well. This will not only remove the deprecated tracer but also the outdated dependency on `go.uber.org/atomic` completely.

As we decide upon a deprecation strategy for this, this issue can be assigned to me and I'll work on it.

**Comment by szuecs** [comment]
I think this issue is too specific to one tracer. Basically right now all our tracers are "deprecated in favor of opentelemetry".
We also have https://github.com/zalando/skipper/issues/2345 which outlines how to go forward and let users a time to migrate from tracers to opentelemetry.
