### ISSUE TITLE
cookie lifetime

### ISSUE THREAD

**Issue by smnmtzgr** [zalando/skipper#2157]
I use skipper to do OIDC pre-auth with the filter oauthOidcAllClaims. I noticed that the skipper cookie has a lifetime of 1 hour. For a Single-Page-Application the following situation happens: If a user let the site open for over 1 hour skipper tries to refresh the cookie and does a redirect to the auth-service. For normal apps/sites this works (http-requests). But for the XHR-Requests of javascript it doesn't work. In the end this leads to a failure on the Single-Page-Application. Only a full reload of the page helps to solve it. Are there some ideas how to fix that? Is it e.g. possible to set a longer lifetime for the skipper cookie? Or are there some parameters/filters to avoid such a situation?

I would prefer to set the cookie lifetime globally via flag.

**Comment by AlexanderYastrebov** [comment]
I think it is [hardcoded to 1h](https://github.com/zalando/skipper/blob/fb852f6965fa2a5111c612b76a05f923644dfc47/filters/auth/oidc.go#L248) but could be overriden by `exp` claim, see https://github.com/zalando/skipper/pull/1903

**Comment by szuecs** [comment]
Also posting the same content from slack: In general I think 24h is reasonable default, such that you don't need to login twice per day.
