### ISSUE TITLE
refactor: config to FlagSet for testability

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#2175]
context: https://github.com/zalando/skipper/pull/2167 and https://github.com/zalando/skipper/pull/2167#discussion_r1060135429 

[This blogpost](https://eli.thegreenplace.net/2020/testing-flag-parsing-in-go-programs/) wrote that we could use flag.FlagSet or invoke the cli itself to properly test flags

The change should keep the interface to not break any users (library or binary users)

**Comment by MustafaSaber** [comment]
I think this is done right @RomanZavodskikh ?

**Comment by RomanZavodskikh** [comment]
Yes.
