### ISSUE TITLE
Incorrect constant used for SwarmPort

### ISSUE THREAD

**Issue by timo-klarshift** [zalando/skipper#2182]
Not setting a swarm port logs the following:

> time="2023-01-04T15:27:31Z" level=error msg="MaxMessageBuffer <= 0, setting to default 4194304 instead"

Here https://github.com/zalando/skipper/blob/master/swarm/swarm.go#L160
we should use `DefaultPort` instead

**Comment by szuecs** [comment]
Yes, thanks!
