### ISSUE TITLE
Cannot use oauthOidcUserInfo filter

### ISSUE THREAD

**Issue by sanjeev55** [zalando/skipper#2184]
Hello everyone,
I am using skipper as my ingress controller and Keycloak as the identity provider. I have the following Ingress object config:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <name>
  annotations:
    kubernetes.io/ingress.class: skipper
    zalando.org/skipper-filter: |
      oauthOidcUserInfo("https://<keycloack url>/auth/realms/<realm>",
      "<clientId>", 
      "<clientsecret>",
      "https://<backend>/oauth/callback", 
      "email profile", 
      "name email",
      "X=Y",
      "X-Auth-Authorization:claims.email",
      "0")
spec:
  rules:
  - host: <host>
    http:
      paths:
      - backend:
          service:
            name: vote
            port:
              number: <number>
        pathType: ImplementationSpecific
```

and have a daemonset with following args:

```
args:
          - "skipper"
          - "-kubernetes"
          - "-kubernetes-ingress-v1"
          - "-kubernetes-in-cluster"
          - "-kubernetes-path-mode=path-prefix"
          - "-address=:9999"
          - "-wait-first-route-load"
          - "-proxy-preserve-host"
          - "-serve-host-metrics"
          - "-enable-ratelimits"
          - "-experimental-upgrade"
          - "-metrics-exp-decay-sample"
          - "-reverse-source-predicate"
          - "-lb-healthcheck-interval=3s"
          - "-metrics-flavour=codahale,prometheus"
          - "-enable-connection-metrics"
          - "-max-audit-body=0"
          - "-histogram-metric-buckets=.01,.025,.05,.075,.1,.2,.3,.4,.5,.75,1,2,3,4,5,7,10,15,20,30,60,120,300,600"
          - "-credentials-paths=<path>"
          - "-credentials-update-interval=180s"
```

with this configuration, whenever i try to apply the ingress object; i get this error:
```
"failed to create filter \"oauthOidcUserInfo\": failed to read secrets from secret source: open : no such file or directory"
```

What could have been the issue? the oauthGrant() filter along with the required arguments in the daemonset works fine but this is not working. I am very new to kubernetes and skipper hence I am finding it hard to identify the root cause of these problems. 

The bigger picture is, i am trying to configure this Ingress object and Daemonset object to support multi-tenancy i.e the client id and client secret are updated in the daemonset based on the client specific URL. Any information on this would be great as well.

**Comment by AlexanderYastrebov** [comment]
Hello, I think you need to add `-oidc-secrets-file` flag
https://github.com/zalando/skipper/blob/32c873da56ff0a8d44a14afeb2d57b4619de7d45/config/config.go#L479

**Comment by sanjeev55** [comment]
> Hello, I think you need to add `-oidc-secrets-file` flag
> 
> https://github.com/zalando/skipper/blob/32c873da56ff0a8d44a14afeb2d57b4619de7d45/config/config.go#L479

Hello, 
Thank you so much for your prompt response, it worked. I'll close the issue.
