### ISSUE TITLE
Using placeholders to dynamically set values in oauthOidcUserInfo filter parameters.

### ISSUE THREAD

**Issue by sanjeev55** [zalando/skipper#2188]
Hello everyone,

Is there a way we can use placeholders as a parameter value in oauthOidcUserInfo filter? In the following way:

```
zalando.org/skipper-filters: |
  setRequestHeader("key", "value")->
  oauthOidcUserInfo("https://<keycloak>/auth/realms/${key}",
  "<clientId>", 
  "<client-secret>", 
  "https://<host>/oauth/callback", 
  "email profile", 
  "name email", 
  "X=Y", 
  "X-Auth-Authorization:claims.email", 
  "0")
```

Here i first set the header and i try to reference the value in the parameter. I tired the above way but kept getting this error:

```
Failed to create new provider https://<keycloak>/auth/realms/$%7Bkey%7D: 404 Not Found: {\"error\":\"Realm does not exist\"}
```
I tried setting up a state bag using lua script and tried to reference that, but that didn't work as well. 
I intend on using the similar approach for client-Id and client-secret. 
Is there any other way we can use a place holder to dynamically replace the values in the parameter?

**Comment by sanjeev55** [comment]
Is it at all possible to use variables as a parameter in the oauthOidcUserInfo filter?

**Comment by AlexanderYastrebov** [comment]
Looks related to https://github.com/zalando/skipper/issues/804

**Comment by sanjeev55** [comment]
Hi @AlexanderYastrebov thanks for your reponse. 

So the goal of this filter chain is to replicate a situation where a tenantId is set in the header like for example: `tenantId = tenant-01`. Now what i want to achieve with this is, based on who the current tenant is, the OpenID Connect Provider URL parameter of this oauthOidcUserInfo filter is set like this:
```
zalando.org/skipper-filters: |
  oauthOidcUserInfo("https://<keycloak>/auth/realms/tenant-01",
  "<clientId>", 
  "<client-secret>", 
  "https://<host>/oauth/callback", 
  "email profile", 
  "name email", 
  "X=Y", 
  "X-Auth-Authorization:claims.email", 
  "0")
```
The goal is to make it dynamic to support multitenancy. If it's not possible in this way, is there any other way that you would suggest with which I can achieve multitenancy?

**Comment by AlexanderYastrebov** [comment]
If you only have a handful of known tenants you may create [multiple `Ingress`es](https://github.com/zalando/skipper/blob/master/docs/kubernetes/ingress-usage.md#predicates)  (or a [RouteGroup](https://github.com/zalando/skipper/blob/master/docs/kubernetes/routegroups.md)) that would route requests to the same service based on the tenant header, e.g.
```
zalando.org/skipper-predicate: Header("TenantId", "tenant-01")
zalando.org/skipper-filters: |
  oauthOidcUserInfo("https://<keycloak>/auth/realms/tenant-01",
  "<clientId>", 
  "<client-secret>", 
  "https://<host>/oauth/callback", 
  "email profile", 
  "name email", 
  "X=Y", 
  "X-Auth-Authorization:claims.email", 
  "0")
```
and
```
zalando.org/skipper-predicate: Header("TenantId", "tenant-02")
zalando.org/skipper-filters: |
  oauthOidcUserInfo("https://<keycloak>/auth/realms/tenant-02",
  "<clientId>", 
  "<client-secret>", 
  "https://<host>/oauth/callback", 
  "email profile", 
  "name email", 
  "X=Y", 
  "X-Auth-Authorization:claims.email", 
  "0")
```

**Comment by sanjeev55** [comment]
Oh wow why did I not think of that. I was so fixated on making this filter dynamic, the whole idea of creating multiple ingresses skipped my mind. Thank you so much @AlexanderYastrebov for suggesting this. I'll close the issue now.
