### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by universam1** [zalando/skipper#2196]
**Describe the bug**

[v0.14.43](https://github.com/zalando/skipper/releases/tag/v0.14.43) causes some routes to fail with runtime error:

```
[APP]time="2023-01-12T14:17:20Z" level=error msg="error while proxying after 96.658µs, route kube_rg__redmine__cd_api_query__all__0_0 with backend lb ://, status code 500: panic caused by: runtime error: invalid memory address or nil pointer dereference, remote host: reducted, request: \"GET /issues.json HTTP/1.1\", host: api-reducted, user agent: \"curl/7.68.0\""
```

**Workaround**

Downgrade to 0.14.42, errors disappear

**Comment by szuecs** [comment]
@universam1 the error is better than just catching (ignoring) the panic and let the request pass to the backend as it was like that before.

**Comment by szuecs** [comment]
I would say it works as intended, please fix your filter to not panic. If you see this happening by skipper core filters, then file a bug for this filter with more information.

**Comment by universam1** [comment]
@szuecs not sure if I understand an `invalid memory address or nil pointer dereference` panic is intended?

**Comment by AlexanderYastrebov** [comment]
> Before the panic broke the filter chain and skipper would happily pass the request to the backend.

Fixed by https://github.com/zalando/skipper/pull/2194
