### ISSUE TITLE
filter swarm: panics and route is down

### ISSUE THREAD

**Issue by universam1** [zalando/skipper#2197]
**Describe the bug**

as requested https://github.com/zalando/skipper/issues/2196#issuecomment-1380455684 filing a bug for filter swarm

[v0.14.43](https://github.com/zalando/skipper/releases/tag/v0.14.43) causes routes to fail when runtime error happens with the swarm filter:

```
[APP]time="2023-01-12T14:07:06Z" level=error msg="cd clusterRatelimit failed to share value: cannot broadcast message, swarm is nil"

[APP]time="2023-01-12T14:17:20Z" level=error msg="error while proxying after 96.658µs, route kube_rg__redmine__cd_api_query__all__0_0 with backend lb ://, status code 500: panic caused by: runtime error: invalid memory address or nil pointer dereference, remote host: reducted, request: \"GET /issues.json HTTP/1.1\", host: api-reducted, user agent: \"curl/7.68.0\""
```

**Workaround**

Downgrade to 0.14.42, route is still served.

**Describe the bug**

A swarm error causes the routes to fail. Prior to v0.14.43 an error was thrown but the route was served. Now we have a service interruption.

**To Reproduce**
Add context, for example:
1. route or ingress definition 
```
    filters:
    - clusterRatelimit("dummy", 2, "1s")
```

**Expected behavior**

Throw an error or better no error

**Comment by universam1** [comment]
Found this stacktrace log, thanks for the hint that this is only printed once:

```
[APP]time="2023-01-12T14:07:15Z" level=error msg="stacktrace of panic caused by: runtime error: invalid memory address or nil pointer dereference:
goroutine 167 [running]:
github.com/zalando/skipper/proxy.stack()
	/workspace/proxy/proxy.go:1021 +0x65
github.com/zalando/skipper/proxy.(*Proxy).do.func1.1()
	/workspace/proxy/proxy.go:1033 +0x38
golang.org/x/time/rate.(*Sometimes).Do(0xc0000d4e60, 0xc003d6af58)
	/go/pkg/mod/golang.org/x/time@v0.3.0/rate/sometimes.go:63 +0xf9
github.com/zalando/skipper/proxy.(*Proxy).do.func1()
	/workspace/proxy/proxy.go:1032 +0x95
panic({0xfef9c0, 0x1aadc00})
	/usr/local/go/src/runtime/panic.go:890 +0x262
github.com/zalando/skipper/swarm.(*Swarm).Values(0x0, {0xc00044e000, 0x4d})
	/workspace/swarm/swarm.go:399 +0xad
github.com/zalando/skipper/ratelimit.(*clusterLimitSwim).Allow(0xc000634500, {0x1150b04?, 0xc000634500?})
	/workspace/ratelimit/swim.go:101 +0x2b7
github.com/zalando/skipper/ratelimit.(*Ratelimit).AllowContext(0xc00066a0c0, {0x12ffe08, 0xc000522540}, {0x1150b04, 0x1})
	/workspace/ratelimit/ratelimit.go:402 +0xaf
github.com/zalando/skipper/filters/ratelimit.(*filter).Request(0xc0001e6690, {0x130d6f8, 0xc003d56000})
	/workspace/filters/ratelimit/ratelimit.go:478 +0x196
github.com/zalando/skipper/proxy.(*Proxy).applyFiltersToRequest(0xc0000d4d80, {0xc000210890?, 0x1, 0x1?}, 0xc003d56000)
	/workspace/proxy/proxy.go:743 +0x303
github.com/zalando/skipper/proxy.(*Proxy).do(0xc0000d4d80, 0xc003d56000)
	/workspace/proxy/proxy.go:1090 +0x6ce
github.com/zalando/skipper/proxy.(*Proxy).ServeHTTP(0xc0000d4d80, {0x12fefd8?, 0xc003d54000}, 0xc00013e200)
	/workspace/proxy/proxy.go:1446 +0x665
github.com/zalando/skipper/net.(*HostPatchHandler).ServeHTTP(0xc00300e8b8, {0x12fefd8, 0xc003d54000}, 0xc00013e000)
	/workspace/net/host.go:60 +0x97
github.com/zalando/skipper/net.(*ValidateQueryHandler).ServeHTTP(0xc002fd7a40, {0x12fefd8, 0xc003d54000}, 0xc00013e000)
	/workspace/net/query.go:19 +0x95
github.com/zalando/skipper/net.(*ValidateQueryLogHandler).ServeHTTP(0xc002fd7a50, {0x12fefd8, 0xc003d54000}, 0xc00013e000)
	/workspace/net/query.go:30 +0x173
net/http.serverHandler.ServeHTTP({0xc000522000?}, {0x12fefd8, 0xc003d54000}, 0xc00013e000)
	/usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0001fe640, {0x12ffe08, 0xc00307b860})
	/usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x4db
```

It is related to this error:
´´´
  | [APP]time="2023-01-12T14:07:02Z" level=error msg="SWARM: failed to parse the ip "
´´´

**Comment by szuecs** [comment]
@universam1 nice one, maybe that happens on pod termination, if you like to test it.
I would recommend to switch from swim to redis for clusterRatelimits, because swim seems to have some serious bugs. We never run it in production, but redis runs fine.
I think we need more proper testing and a warning in our docs.

**Comment by universam1** [comment]
Sounds reasonable to switch to Redis. 

I'd take a step and try to handle the panic with a proper error handling - @szuecs do you have an example how such an exception should be handled now in a filter?

**Comment by szuecs** [comment]
> Sounds reasonable to switch to Redis.
> 
> I'd take a step and try to handle the panic with a proper error handling - @szuecs do you have an example how such an exception should be handled now in a filter?

In Go you would do a `recover()` in Request() or Response() depending where you have the code or in both. Of course all filters should never panic, but if you observe one you can do this.

As we exchanged some messages via our public chat and direct message, I just wanted to add this for the audience.
