### ISSUE TITLE
my route is ignored 

### ISSUE THREAD

**Issue by pcbuildpluscoding** [zalando/skipper#2204]
**Describe the bug**
Thanks for this package, it looks useful !
Yesterday I cloned the skipper repo at v0.15
For testing, I have nginx running on port 7777, which returns the default welcome page when I point my browser to localhost:7777
These are my skipper testing steps
1. In the repo root location, I ran ```make skipper```
2. I ran skipper with your simple inline route example =>
```bin/skipper -address :9090 -inline-routes 'r: * -> "http://localhost:7777"'
[APP]INFO[0000] Expose metrics in codahale format            
[APP]INFO[0000] enable swarm: false                          
[APP]INFO[0000] support listener on :9911                    
[APP]INFO[0000] Dataclients are updated once, first load complete 
[APP]INFO[0000] proxy listener on :9090                      
[APP]INFO[0000] TLS settings not found, defaulting to HTTP   
[APP]INFO[0000] route settings, reset, route: r: * -> "http://localhost:7777" 
[APP]INFO[0000] route settings received                      
[APP]INFO[0000] route settings applied                   
```
Test 1 => pasted http://localhost:9090 in my browser
Success - I get the nginx welcome page ! the skipper access log agrees
127.0.0.1 - - [19/Jan/2023:17:55:33 +1000] "GET / HTTP/1.1" 200 384 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0" 0 localhost:9090 - -

Test2 => pasted http://localhost:9090/test in my browser
Fail :< - got 404 page, access log agrees
127.0.0.1 - - [19/Jan/2023:17:55:23 +1000] "GET /hello HTTP/1.1" 404 123 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0" 0 localhost:9090 - -

Checked the route exists with your other route status endpoint on port 9911
```> curl localhost:9911/routes```=>
``` 
r: * 
-> "http://localhost:7777";
```
I thought * predicate handles any and all requests. Eg regardless of the path

**Comment by MustafaSaber** [comment]
Hi @pcbuildpluscoding, if your nginx configuration doesn't serve '/test' this config will proxy the request as it is to your backend which will return 404, `curl http://localhost:9090/test -> skipper(proxy in this case) -> http://localhost:8080(nginx port)/test` to remove you can use a filter to play with the path.

**Comment by szuecs** [comment]
I agree with @MustafaSaber , likely nginx serves 404 at /hello as the access log suggests

**Comment by AlexanderYastrebov** [comment]
Try to `curl -v http://localhost:7777/test`

**Comment by pcbuildpluscoding** [comment]
Yes ... thank you ... I was thinking unless I make a filter to pass through the original path, perhaps the path is ignored.
