### ISSUE TITLE
Path per tenant configuration

### ISSUE THREAD

**Issue by sanjeev55** [zalando/skipper#2205]
Hi,
I am trying to setup a path per tenant skipper ingress configuration for example: `<hosturl>\tenant1` will redirect to tenant1 login page and `<hosturl>\tenant2` will redirect to tenant2 login page. So far this is my configuartion for tenant1 and tenant2:

Tenant1:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenant1
  annotations:
    kubernetes.io/ingress.class: skipper
    zalando.org/skipper-predicate: Path("/tenant1")
    zalando.org/skipper-filter: |
      oauthOidcUserInfo("<keycloak url>/auth/realms/tenant1", 
      "<clientId>", 
      "<clientsecret>", 
      "<hosturl>/tenant1/oauth/callback", 
      "email profile", 
      "name email", 
      "X=Y", 
      "X-Auth-Authorization:claims.email", 
      "0")
spec:
  rules:
  - host: hosturl
    http:
      paths:
      - backend:
          service:
            name: serviceName
            port:
              number: 82
        pathType: ImplementationSpecific
```

Tenant2:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenant2
  annotations:
    kubernetes.io/ingress.class: skipper
    zalando.org/skipper-predicate: Path("/tenant2")
    zalando.org/skipper-filter: |
      oauthOidcUserInfo("<keycloak url>/auth/realms/tenant2", 
      "<clientId>", 
      "<clientsecret>", 
      "<hosturl>/tenant2/oauth/callback", 
      "email profile", 
      "name email", 
      "X=Y", 
      "X-Auth-Authorization:claims.email", 
      "0")
spec:
  rules:
  - host: <hosturl>
    http:
      paths:
      - backend:
          service:
            name: <serviceName>
            port:
              number: 82
        pathType: ImplementationSpecific
```

With this configuration, whenever I enter the url `<hosturl>\tenant1` it does redirect me to the login page for tenant1 but after entering username and password for a particular user, it says "404: not found"  and in the skipper log it says something like 
`level=error msg="error while proxying after 123.237µs, route _unknownroute_ with backend <unknown> <unknown>, status code 404: dialing failed false: route lookup failed, remote host: <host ip>, request: \"GET /tenant1/oauth/callback HTTP/1.0\", host: <hosturl>`
I inspected the flow of the whole process, and what i found was when the callback url is being called, the response header does not have `set-cookie: skipperOauthOidc; Path; Domain` and `location: /`. This was the difference that i found between the working instance and the not working one. 
I suspect it has something to do with the path but cannot really pinpoint the actual issue. 
I would be grateful if anyone could help me on this.

**Comment by szuecs** [comment]
Please check the differences between Path and PathSubtree predicates. In this case you need to set PathSubtree because your callback definition will get 404.

**Comment by sanjeev55** [comment]
Hi @szuecs , thank you for your response, i looked into Path and PathSubtree predicate and used PathSubtree but it only worked after i added `setPath("/")` at the end of the filter chain, if i don't then it shows the same error. It was able to redirect me to the backend but the skipper shows another error related to the css file: 

`level=error msg="error while proxying after 95.962µs, route _unknownroute_ with backend <unknown> <unknown>, status code 404: dialing failed false: route lookup failed, remote host: <host ip>, request: \"GET /static/stylesheets/style.css HTTP/1.0\", host: <hosturl>`

I inspected the request flow and found that for style.css it was trying to GET this url `https://<hosturl>/static/stylesheets/style.css` instead of `https://<hosturl>/tenant1/static/stylesheets/style.css`. Is it because of the `setPath` or am I completely missing the point? Is there a proper skipper configuration for path per tenant setup?

**Comment by sanjeev55** [comment]
And another issue is once i get to backend with url `<hosturl>/tenant1` and if I perform some post or get operation that redirects the page to the same url, the url changes to just `<hosturl>` which leads to 404: page not found. I am really confused on how i should handle this using skipper filters and predicates. I want the `<hosturl/tenant1>` url to persist. Any insights on this? @szuecs  @AlexanderYastrebov

**Comment by AlexanderYastrebov** [comment]
@sanjeev55 

Reading the docs https://github.com/zalando/skipper/blob/master/docs/tutorials/auth.md#openid-connect I think that callback url should align with the request url (i.e. back call is handled by the same filter).

So you would either need to use `"<hosturl>/tenant1"` as a callback url or rather use `zalando.org/skipper-predicate: PathSubtree("/tenant1")` to allow requests to `/tenant1`, `/tenant1/foo`, `/tenant1/foo/bar` and callback `/tenant1/oauth/callback`.
`Path` predicate matches request path exactly - that is why you get `route _unknownroute_` error, see https://github.com/zalando/skipper/blob/master/docs/reference/predicates.md#the-path-tree

> I inspected the request flow and found that for style.css it was trying to GET this url 

The backend request path is the same as incoming request path unless you change it with the `setPath` filter.
If you want to remove `/tenant1` prefix you'd need to use https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#modpath as `setPath("/")` basically resets all various paths to `/`.

> I perform some post or get operation that redirects the page to the same url

This is another problem as your backed does not know that you've modified the path so `Location` header value in redirects would not contain `/tenant1` prefix. You may try to rewrite Location header using https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#modresponseheader
If backed includes request path into response body then it would be hard to change it (still could be possible via https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#sed if backed does not compress the response).

It may be easier to achieve multi-tenancy by using different domains (e.g. `tenant1.example.org` and `tenant2.example.org`) then messing up with the paths.

**Comment by sanjeev55** [comment]
Hi @AlexanderYastrebov , thank you for your detailed response. I was able to solve most of the problems, but the redirection URL after a certain http operation from within the application still changes to only `<hosturl>` instead of `<hosturl>/tenant1`. The skipper logs shows the following error: 

`
level=error msg="error while proxying after 99.883µs, route _unknownroute_ with backend <unknown> <unknown>, status code 404: dialing failed false: route lookup failed, remote host: <hostip>, request: \"POST / HTTP/1.0\", host: <host>
`
and has the following request and response header values:

```
Response Header:
HTTP/2 404 Not Found
server: nginx/1.18.0 (Ubuntu)
date: Fri, 20 Jan 2023 10:24:46 GMT
content-type: text/plain; charset=utf-8
content-length: 10
x-content-type-options: nosniff
X-Firefox-Spdy: h2

Request Header:
POST / HTTP/2
Host: <host>
User-Agent: <user agent info>
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded
Content-Length: 6
Origin: <hosturl>
DNT: 1
Connection: keep-alive
Referer: <hosturl>/tenant1
Cookie: skipperOauthOidc <cookie information>
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
TE: trailers
```

I tried using the `modReponseHeader` filter but it didn't have much effect. I have the following configuration for a tenant. 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenant1
  annotations:
    kubernetes.io/ingress.class: skipper
    zalando.org/skipper-predicate: Path("/tenant1")
    zalando.org/skipper-filter: |
      oauthOidcUserInfo("<keycloak url>/auth/realms/tenant1", 
      "<clientId>", 
      "<clientsecret>", 
      "<hosturl>/tenant1/oauth/callback", 
      "email profile", 
      "name email", 
      "X=Y", 
      "X-Auth-Authorization:claims.email", 
      "0") -> modPath("/company-02", "/") -> sed("/static", "/tenant1/static") 
      -> modResponseHeader("Location", "/", "/tenant1/")
spec:
  rules:
  - host: hosturl
    http:
      paths:
      - backend:
          service:
            name: serviceName
            port:
              number: 82
        pathType: ImplementationSpecific
```
The `sed` filter helped finding the css file and the `modPath` filter helps finding the backend after authentication and authorization from keycloak. If i dont use the `modPath` filter, it gives me `404:not found` error. 

Thank you again for helping me out with my queries. If nothing works then I will opt to subdomain per tenant setup like you suggested.

**Comment by AlexanderYastrebov** [comment]
> modResponseHeader("Location", "/", "/tenant1/")

`modResponseHeader` replaces regexp match and redirect `Location` header most likely contains absolute url and this likeyl replaces each slash with `/tenant1/`.
You'd need something like `modResponseHeader("Location", "<hosturl>/", "<hosturl>/tenant1/")`

**Comment by sanjeev55** [comment]
Hi @AlexanderYastrebov @szuecs , thank you guys for the response. 
Regarding `modResponseHeader`, i added this filter to the chain as per your suggestion, but it didn't yield the result i wanted, it still gave me the `404: not found` error. So what i did instead was create a custom route as following: 

```
zalando.org/skipper-routes: |
      redirect: PathRegexp("/") && Header("Referer", "<hosturl>/tenant1") -> redirectTo(307,"<hosturl>/tenant1") -> <loopback>;
```

This allowed me to redirect to the desired URL,but I am still making some tests to observe the feasibility of this solution. 

And regarding using subdomains to separate tenants, I do agree that is better separator for tenants and will probably implement that but since I had already started working with paths I wanted to play around a bit with filters and predicates to see if I can achieve what I wanted to achieve. 

Thank you again @szuecs and @AlexanderYastrebov  for your response. I will go ahead and close this issue.

**Comment by szuecs** [comment]
Just as a hint, in case you use `zalando.org/skipper-routes` you likely want to use https://opensource.zalando.com/skipper/kubernetes/routegroup-crd/ instead.

**Comment by sanjeev55** [comment]
Hi @szuecs ,
Thank you for the suggestion, i opted to using Subdomain per tenant configuration and moving forward I will make use of the routegroup as well. Thank you again.
