### ISSUE TITLE
Obtain jwt token claims

### ISSUE THREAD

**Issue by sanjeev55** [zalando/skipper#2235]
Hello,

Is there a way to obtained the jwt token claims and store it in a state bag? For example I want to obtain the current logged in username and store in statebag using lua. I have tried `jwtValidation()` filter and `fowardToken()` but cant seem to access the statebag using lua. Or am I completely missing the point of these filters? 
All in all what i want to achieve is to obtain the user name from the token claims and store it in the statebag using lua. Any help would be appreciated.

**Comment by sanjeev55** [comment]
So i was able to solve this using the value from upstream header parameter in oauthOidcUserInfo (since i was already using this for authentication and authorization). I set it up like: 

```
oauthOidcUserInfo("https://<keycloak_url>/auth/realms/<tenantId>", 
      "<client_id>", 
      "<client_secrect>", 
      "https://<host>/oauth/callback", 
      "email profile", 
      "name email preferred_username", 
      "tenant=<tenantid>", 
      "X-Auth-Authorization:claims.preferred_username", 
      "0") -> 
       lua("function request(c,p); print(c.request.header['X-Auth-Authorization']); end")

```

From this i found out the username was stored in the `X-Auth-Authorization` header and could be accessed via lua. so i used it to redirect to the desired url using lua like:

```
lua("function request(c,p); 
c.serve({status_code=307, header={location='https://<host>/#/home/workspace/<tenantid>/' .. c.request.header['X-Auth-Authorization']}});
end")
```
I am pretty sure this not the optimal solution, but for now it works just the way I want.
Thanks again for this amazing tool.

**Comment by AlexanderYastrebov** [comment]
You may also compose redirect without lua like so
```
...
-> status(307)
-> setResponseHeader("Location", "https://<host>/#/home/workspace/<tenantid>/${request.header.X-Auth-Authorization}")
-> <shunt>
```
See https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#template-placeholders

**Comment by sanjeev55** [comment]
Thanks, @AlexanderYastrebov  for the suggestion. I tried using setResponseHeader before but now I know the `status` filter is also required to work. Thanks again.
