### ISSUE TITLE
MIME of `.mjs` files

### ISSUE THREAD

**Issue by benedictdudel** [zalando/skipper#2253]
Unfortunately skipper is serving `.mjs` files as `application/octet-stream` instead of `application/javascript`. The MIME used to identify `.mjs` files should be a [web compatible JavaScript MIME Type](https://mimesniff.spec.whatwg.org/#javascript-mime-type).

Does anyone has a workaround to set the correct `Content-Type` header for `*.mjs` files with skipper in the meantime?

**Comment by AlexanderYastrebov** [comment]
Hello, how do you serve these files? Could you provide an example route maybe?

**Comment by benedictdudel** [comment]
@AlexanderYastrebov Unfortunately I have no public route available. I stumbled across the issue with the new storybook version which uses `.mjs` files. Here is the corresponding [issue](https://github.com/storybookjs/storybook/issues/20157) in Storybook with some more context (albeit using nginx).

**Comment by AlexanderYastrebov** [comment]
If we are talking about [`static`](https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#static) filter then it uses https://pkg.go.dev/net/http#FileServer which internally uses https://pkg.go.dev/mime#TypeByExtension which relies on system mime files (see docs):

```sh
~$ grep mjs /usr/share/mime/globs2 
50:application/javascript:*.mjs

~$ mkdir /tmp/skipper2253
~$ echo "This is an .mjs file" > /tmp/skipper2253/test.mjs
~$ bin/skipper -inline-routes='* -> static("/tmp/skipper2253") -> <shunt>'

~$ curl -v localhost:9090/test.mjs 2>&1 | grep Content-Type
< Content-Type: text/javascript; charset=utf-8
```

**Comment by AlexanderYastrebov** [comment]
Actuall mjs seems to be hardcoded even https://cs.opensource.google/go/go/+/refs/tags/go1.20.2:src/mime/type.go;l=70 which explains the result discrepancy (`application/javascript` vs `text/javascript`) in https://github.com/zalando/skipper/issues/2253#issuecomment-1478287938

**Comment by AlexanderYastrebov** [comment]
See related https://github.com/golang/go/issues/32351

**Comment by benedictdudel** [comment]
Thank you for your fast response!
