### ISSUE TITLE
Improve RedisUpdater func

### ISSUE THREAD

**Issue by MustafaSaber** [zalando/skipper#2258]
**Is your feature request related to a problem? Please describe.**
RedisUpdater functions doesn't return error which may make confusion https://github.com/zalando/skipper/pull/2242#issuecomment-1485510916
https://github.com/zalando/skipper/pull/2242#discussion_r1146305821
https://github.com/zalando/skipper/pull/2242#discussion_r1146297489

**Describe the solution you would like**
Change return type of function to `([]string, error)` or `([]byte, error)`

**Tasks**

- [ ] Change function return in Skipper & RouteSRV
- [ ] Update test cases

**Comment by AKARSHITJOSHI** [comment]
Hi I would like to contribute on this.

**Comment by MustafaSaber** [comment]
Yeah that would be great @AKARSHITJOSHI!

**Comment by szuecs** [comment]
@AKARSHITJOSHI thanks, please create a PR and in case you need help please feel free to ask either here or in slack.

**Comment by AKARSHITJOSHI** [comment]
Hi @szuecs , for routersrv and redisHandler I'm able to change return type to `([] byte ,error)` .
But for `getRedisUpdaterFunc` if I change return type  to `([] string,error)` , the  `redisOptions.AddrUpdater` in `redisClient.go` will also need to be changed . Could please suggest which changes to make .

**Comment by szuecs** [comment]
It's fine to change the func redisOptions.AddrUpdater to `([]string,error)` if needed. It's a new func that won't be widely in use so breaking for the good seems to be legit. 
@AlexanderYastrebov do you have any other opinions or suggestions?

**Comment by AlexanderYastrebov** [comment]
> do you have any other opinions or suggestions?

I agree, we should change the signature
