### ISSUE TITLE
kube-skipper: data client for Kubernetes Ingress resources

### ISSUE THREAD

**Issue by hjacobs** [zalando/skipper#227]
Create a new "data source" for Skipper to configure routes automatically from declared `Ingress` resources:
* Poll on Kubernetes `Ingress` resource http://kubernetes.io/docs/user-guide/ingress/
* Configure routes accroding to defined host and path matching

Idea is to use skipper as a HTTP router in combination with [kube-ingress-aws-controller](https://github.com/zalando-incubator/kube-ingress-aws-controller) to support `Ingress` on [Kubernetes on AWS](https://github.com/zalando-incubator/kubernetes-on-aws):

* kube-ingress-aws-controller
  * Deployed as deployment with replicas=1
  * Watch on Ingress resources
  * Configure one Application Load Balancer (ALB/ELBv2) per used SSL certificate
  * Attach Auto Scaling Group to ALB (using skipper NodePort)
* skipper with Kubernetes data client
  * Deployed as DaemonSet (thus running on every node)
  * Exposes NodePort on every EC2 instance
  * Watch on Ingress resources
  * Configure routes by defined host/path matching

**Comment by hjacobs** [comment]
@aryszka started working on this: https://github.com/zalando/skipper/tree/kube-client

**Comment by melTob** [comment]
@hjacobs @aryszka can we close this? I assume it`s already done.

**Comment by hjacobs** [comment]
Yes, you can close this :smile:
