### ISSUE TITLE
Documentation is built using outdated mkdocs-material 6.2.5 (latest version is 9.1.7)

### ISSUE THREAD

**Issue by bocytko** [zalando/skipper#2278]
**Describe the bug**
The documentation seems to be built using mkdocs-material 6.2.5 whereas the [latest version is 9.1.7](https://github.com/squidfunk/mkdocs-material/releases/tag/9.1.7).
[Since 9.0.0](https://squidfunk.github.io/mkdocs-material/changelog/?h=changelog#9.0.0), the search engine has been revamped resulting in better search matches and rich previews (see examples below).

Skipper's documentation site is also linked under Zalando in the [mkdocs-material](https://github.com/squidfunk/mkdocs-material) README, so it's worth updating.

I verified the update locally using the poetry setup mentioned below and there are no adjustments needed post upgrade.

**To Reproduce**
```sh
% curl 'https://opensource.zalando.com/skipper/' | grep 'meta.*generator'
<meta name="generator" content="mkdocs-1.1.2, mkdocs-material-6.2.5">
```

**Expected behavior**
Documentation is built using mkdocs-material 9.1.7+ and the documentation build/publish process is reviewed.
One solution can be using poetry for the docs build and adding a build/serve/publish commands to the Makefile.
The dependencies to use are:

```toml
mkdocs-material = "^9.1.7"
mkdocs = "^1.4.2"
markdown-include = "^0.8.1"
```

**Observed behavior**
Documentation is built using old mkdocs-material, despite the ci buildfile pulling [most recent packages](https://github.com/zalando/skipper/blob/master/delivery.yaml#L116).

---

#### Current behavior for "setreq"
![example_1_setreq_current_behavior](https://user-images.githubusercontent.com/711379/233832832-d1e0fd1e-35a9-4a06-8b31-a7d255262ccb.png)

#### 9.1.7+
![example_1_setreq_new_behavior_rich_preview](https://user-images.githubusercontent.com/711379/233832858-c851cb12-1127-4059-b9e6-7cd33a95acaf.png)

#### Current behavior for "backends"
![example_2_backends_current_behavior](https://user-images.githubusercontent.com/711379/233833068-6155818b-f116-4bbf-8ba3-0198c78714fd.png)

#### 9.1.7+
Exact match on the header is correctly displayed as 1st result:
![eample_2_backends_higher_search_quality](https://user-images.githubusercontent.com/711379/233833090-1af0b622-c518-454e-b4ce-db81d6f323f7.png)

**Comment by szuecs** [comment]
Thanks I updated it.
Best would be that a pipeline could trigger docs update, but for now we have to use local commands, so it depends on the dev machine that runs the doc update.

**Comment by MustafaSaber** [comment]
Automation is done

Workflow: https://github.com/zalando/skipper/pull/2284
Test workflow: https://github.com/zalando/skipper/pull/2285
Job was successful and website was updated https://github.com/zalando/skipper/actions/runs/4806458719/jobs/8554003560
