### ISSUE TITLE
Docs: SVG file with pprof result is incorrectly displayed

### ISSUE THREAD

**Issue by bocytko** [zalando/skipper#2279]
**Describe the bug**
The [pprof example](https://opensource.zalando.com/skipper/operation/operation/#profiling-example) includes an SVG image that's not rendered properly:

![Screenshot 2023-04-23 at 12 04 22](https://user-images.githubusercontent.com/711379/233833295-65b2b227-600a-4f5a-aed0-cff8d3763ee7.png)

**To Reproduce**
Open https://opensource.zalando.com/skipper/operation/operation/#profiling-example

**Expected behavior**
Image is included as link or a resized PNG linking to the underlying SVG (in a new window).

**Observed behavior**
Image is truncated and not scaled down. Note that behavior is the same regardless of mkdocs-material version. I tried [setting explicit width](https://squidfunk.github.io/mkdocs-material/reference/images/?h=image#image-captions) for the image, but this does not seem to work for SVGs w/o adding a viewBox.

**Comment by szuecs** [comment]
Thanks 🙏🏽 
Weird that it does not work. My safari mobile browser also doesn't show it nicely.

**Comment by szuecs** [comment]
FF and chrome both only show a tiny part of it, so I guess best is to switch to png.
I have to set `width` and `height`explicitly in chrome to have svg work:

![image](https://user-images.githubusercontent.com/50872/233855150-f8824252-cc5d-4654-aaaf-098d30e63cbb.png)
