### ISSUE TITLE
Filters: logBody("request", "response")

### ISSUE THREAD

**Issue by bocytko** [zalando/skipper#2282]
**Is your feature request related to a problem? Please describe.**
I'd like to use skipper as proxy for APIs and log the request & response pairs, so that I can later mock the APIs.

**Describe the solution you would like**
Skipper already provides a filter [logHeader](https://opensource.zalando.com/skipper/reference/filters/#logheader) to log request headers. Similarly, there could be a filter provided `logBody` that logs the request body/response (e.g. up to a certain size) (or a lua function that provides access to the request/response body).

**Describe alternatives you've considered (optional)**
- Running skipper as library and writing the filter myself.
- Tee'ing the response to another application that will do the logging.

**Additional context (optional)**
- [nginx](https://gist.github.com/morhekil/1ff0e902ed4de2adcb7a) can do this ([alternative](https://www.hardill.me.uk/wordpress/2018/03/14/logging-requests-and-response-with-nginx/))

**Would you like to work on it?**
No

**Comment by AlexanderYastrebov** [comment]
I think there is [`auditLog`](https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#auditlog) filter for this purpose (but we have [it disabled](https://github.com/zalando-incubator/kubernetes-on-aws/blob/df67dd437c48355955bb96e5306bbdd2800d6681/cluster/manifests/skipper/deployment.yaml#L158) in our deployment).

**Comment by bocytko** [comment]
I see. I used it and it seems the default when running skipper as library was 0 bytes. Will try again soon and close the issue if it works well.

**Comment by bocytko** [comment]
Skipper with `auditLog()` configured:


Simulated backend application:
```sh
$ ./bin/skipper -inline-routes='all: * -> inlineContent("<h1>response</h1>") -> <shunt>' -address=:9092
```

Request proxy:
```sh
$ ./bin/skipper -inline-routes='all: * -> auditLog() -> "http://localhost:9092"' -max-audit-body=1024
```

Request:
```sh
$ curl -v GET localhost:9090 -d 'a=b'
```

Logs:
```sh
$ ./bin/skipper -inline-routes='all: * -> auditLog() -> "http://localhost:9092"' -max-audit-body=1024
[APP]INFO[0000] Expose metrics in codahale format            
[APP]INFO[0000] enable swarm: false                          
[APP]INFO[0000] Replacing lua filter specification           
[APP]INFO[0000] support listener on :9911                    
[APP]INFO[0000] Dataclients are updated once, first load complete 
[APP]INFO[0000] proxy listener on :9090                      
[APP]INFO[0000] TLS settings not found, defaulting to HTTP   
[APP]INFO[0000] route settings, reset, route: all: * -> auditLog() -> "http://localhost:9092" 
[APP]INFO[0000] route settings received                      
[APP]ERRO[0000] Failed to start supportListener on :9911: listen tcp :9911: bind: address already in use 
[APP]INFO[0000] route settings applied                       
{"method":"POST","path":"/","status":200,"requestBody":"a=b"}
127.0.0.1 - - [25/Apr/2023:11:03:44 +0200] "POST / HTTP/1.1" 200 17 "-" "curl/7.81.0" 2 localhost:9090 - -
```

So `auditLog` logs the [body of the request](https://github.com/zalando/skipper/blob/a3f927a46ef112db54a2d70e91897ee0e9d15492/filters/log/log.go#L158) in the response filter.

I'm looking to log the request body in the request filter and the response body in the response filter, just like the `logHeader` filter does for headers.

**Comment by AlexanderYastrebov** [comment]
> So auditLog logs the [body of the request](https://github.com/zalando/skipper/blob/a3f927a46ef112db54a2d70e91897ee0e9d15492/filters/log/log.go#L158) in the response filter.

This is done like that because request body is read only after request path of filter chain during backend request.

**Comment by trkohler** [comment]
I want to try to implement it, if it's okay.

**Comment by szuecs** [comment]
@trkohler there is already a pr that has this as a side effect 😀
I try to build a facility for streaming filters. I start to check it again in the coming days and weeks.

**Comment by trkohler** [comment]
oh, just noticed your comment @szuecs 😅

**Comment by AlexanderYastrebov** [comment]
One idea for logging request/response body without buffering is to log it in chunks along with some kind of unique request/response id (memory address?) as soon as chunks are sent (i.e. intercept Body.Read and log what has been read).
The operator then may grep the logs for request id to find all the chunks of the same request. If most of bodies fit into one chunk (needs checking) then there will be mostly one log line per body.

**Comment by szuecs** [comment]
@AlexanderYastrebov do you mean `%p` of req.Body/rsp.Body?
Something like this:
```
[APP]INFO[0003] logBody("request") 0xc0001ae0c0: {"foo": "bar"}
[APP]INFO[0003] logBody("response") 0xc000457300: aaaaaaaaaa
```

**Comment by AlexanderYastrebov** [comment]
@szuecs Yes, this or maybe x-flow-id if present (and then document that it should be used like `flowId("reuse") -> logBody("request")`)

**Comment by szuecs** [comment]
@AlexanderYastrebov this would be the same in request and response, but I guess this is even better
