### ISSUE TITLE
Docs: Tutorial – Running skipper as library

### ISSUE THREAD

**Issue by bocytko** [zalando/skipper#2283]
**Is your feature request related to a problem? Please describe.**
As I was experimenting with filters, I was trying to find out how to use skipper as a library in a simple Go application.
I haven't found an example in the [Tutorials section](https://opensource.zalando.com/skipper/tutorials/common-use-cases/) of the documentation. Also, it took me a while to discover that I need to use an override for the `go-redis/redis/v9` dependency given that `go mod` does not add it by default...

**Describe the solution you would like**
Tutorial that explains how to run skipper as library with custom code, like Filters.

**Describe alternatives you've considered (optional)**
- I found using a [plugin](https://opensource.zalando.com/skipper/reference/plugins/) more tedious.

**Additional context (optional)**
N/A

**Would you like to work on it?**
I could contribute a two-file example to the docs / repository as baseline, if needed. It worked for me, but may not be dogmatic.

**Comment by AlexanderYastrebov** [comment]
> it took me a while to discover that I need to use an override for the go-redis/redis/v9 dependency given that go mod does not add it by default

Will be fixed by https://github.com/zalando/skipper/pull/2159
