### ISSUE TITLE
cookie filter(s)

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#230]
it would be good to have filters that simplify setting cookies. Currently the only way is to set a header, wich is quite limiting and not too friendly to the user.

**Comment by evangelion1204** [comment]
In general I think the first thing that should be moved is indeed the `filterutils`. They could come in handy for all following filter development like I did here https://github.com/zalando-incubator/skoap/pull/12 I was in general missing the utils and just copied the code 😄

**Comment by DeTeam** [comment]
@aryszka guess we have it now: `requestCookie`, `responseCookie`, `jsCookie`.

We can close this one?

**Comment by aryszka** [comment]
@DeTeam agree
