### ISSUE TITLE
Log traceId in proxy logger

### ISSUE THREAD

**Issue by RomanZavodskikh** [zalando/skipper#2301]
**Is your feature request related to a problem? Please describe.**
Log traceId in proxy logger in every log line it's known.
This change would increase the visibility of skipper because it would be possible to see a connections between log lines and traces inside Opentracing/Lightstep/any other tracing solution.

**Describe the solution you would like**
Take a look at the log lines nearby and inject traceId in every place it could be theoretically found out.
https://github.com/zalando/skipper/blob/master/proxy/proxy.go
To do so, we need to expose `GetTraceID` method somehow https://github.com/zalando/skipper/blob/v0.16.29/tracing/tracing.go#L157

**Would you like to work on it?**
Yes

**Comment by szuecs** [comment]
@RomanZavodskikh I guess we can close this now.
