### ISSUE TITLE
Allow tracingTag filter to use response header values

### ISSUE THREAD

**Issue by lukas-c-wilhelm** [zalando/skipper#2316]
**Is your feature request related to a problem? Please describe.**
An application might provide a successful response that is nevertheless degraded in quality (e.g. using a static fallback value for some property). A measurement of error rate of an application might want to consider such responses as errors even if they are technically successful. If this monitoring should be based on spans, the span has to receive an error tag based on a response property.

**Describe the solution you would like**
The `tracingTag` filter should be able to use response header values.

**Describe alternatives you've considered (optional)**
n/a

**Additional context (optional)**
n/a

**Would you like to work on it?**
Yes

**Comment by AlexanderYastrebov** [comment]
`tracingTag` currently is only applied n the request path. We may add a companion filter `responseTracingTag` to do the same on the response path.

>  the span has to receive an error tag based on a response property.

If we want to set tag based on the response code then we'd need to add another filter that implements this.
