### ISSUE TITLE
Configure Zappr

### ISSUE THREAD

**Issue by hjacobs** [zalando/skipper#235]
We should enable Zappr, right?

**Comment by aryszka** [comment]
previously i was against it, because of the strange self-approval thing that we have on some projects. What are our options for approval of PRs?

Others, opinions on this issue?

**Comment by Raffo** [comment]
@aryszka I'm generally in favor, but can you give us more details on what you mean by "strange self-approval"?

**Comment by aryszka** [comment]
what i was referring to, i noticed in some repos, that the creator of the PR can approve their own PR, and when e.g. 2 approvals are required, it counts as one. I checked the zappr docs now, and it seems to be possible to configure it in a more logical way.

all-in-all, enough votes, let's install zappr :)

**Comment by Joneser** [comment]
What should the zappr rules for this repo be?

I'm assuming 2 approvals and one of them isn't the PR Opener? If so I can add a PR with the zappr file but I'm not sure if I will have permissions to enable it on this repo.
