### ISSUE TITLE
travis build fails sometimes due to test calling out start an etcd process

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#237]

**Comment by ideahitme** [comment]
https://travis-ci.org/zalando/skipper/builds/208397133 - failing 
retry build - 
https://travis-ci.org/zalando/skipper/builds/208437789 - success

**Comment by aryszka** [comment]
thanks! the solution i have on mind is to mock away etcd

**Comment by szuecs** [comment]
We stopped testing etcd on Travis so this can be closed, not?

**Comment by szuecs** [comment]
etcd is not tested in travis, so close
