### ISSUE TITLE
update the maintainers

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#240]

**Comment by hjacobs** [comment]
IMHO the `MAINTAINERS` file should not just list all contributors, but instead point to the core maintainers who feel responsible reviewing all PRs --- `MAINTAINERS` should just be 2-4 persons here I think.

**Comment by aryszka** [comment]
i like the responsibility angle. Thanks for the advice. I prefer more than less for this. Closing this for now, and will discuss it with the core maintainers.
