### ISSUE TITLE
Kubernetes: Skipper throws Internal Server Error for service without endpoints

### ISSUE THREAD

**Issue by hjacobs** [zalando/skipper#241]
I created a Kubernetes service and Ingress and the service has no endpoints (wrong label selector):

```
$ http https://myapp-ingress.example.org/
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 22
Content-Type: text/plain; charset=utf-8
Date: Fri, 16 Dec 2016 22:24:39 GMT
X-Content-Type-Options: nosniff

Internal Server Error
```

I think it's because the service has no endpoints:
```
$ zkubectl describe svc myapp
Name:			myapp
Namespace:		default
Labels:			application=myapp
Selector:		<none>
Type:			ClusterIP
IP:			10.3.0.179
Port:			<unset>	80/TCP
Endpoints:		<none>
Session Affinity:	None
```

I would expect Skipper to return HTTP error 503 in that case:

> 503 Service Unavailable
> The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state

**Comment by aryszka** [comment]
right. backend address validation is missing, ergo it's exactly how you suspect. +1 for 503

**Comment by hjacobs** [comment]
Related: #246
