### ISSUE TITLE
Kubernetes: Skipper should keep the original "Host" header

### ISSUE THREAD

**Issue by hjacobs** [zalando/skipper#242]
Here the current headers of an application deployed behind Ingress with Skipper:

```
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,de;q=0.6
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Cache-Control: no-cache
Host: 10.3.0.152:80
Pragma: no-cache
Referer: https://example.com/foo
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36
X-Amzn-Trace-Id: Root=1-5859553d-19f608145e1844b83d53b92e
X-Forwarded-For: <my client IP>
X-Forwarded-Port: 443
X-Forwarded-Proto: https
```

(I kept all original headers for demonstration)

As you can see, the `Host` header is pointing to my internal Kubernetes service ClusterIP :disappointed: 

Skipper should keep the original `Host` header value (which would be `myapp.example.com` in this case). All the other `X-Forwarded-*` headers are already set by the Amazon ALB and are fine :smile: 

Why is this important? The application must be able to find out its own URL, e.g. for redirects and callbacks (like OAuth flow). Hardcoding the application URL in a configuration (env var) is neither nice nor flexible (the same app might be accessible via multiple `Host` rules in Ingress).

**Comment by aryszka** [comment]
see https://godoc.org/github.com/zalando/skipper/proxy#Flags

in the executable it is the -proxy-preserve-host flag.

**Comment by hjacobs** [comment]
@aryszka so it's only a runtime flag to be changed on https://github.com/zalando-incubator/kubernetes-on-aws ?

**Comment by hjacobs** [comment]
This was fixed by simply using the mentioned command line option.
