### ISSUE TITLE
FlowId support in logs

### ISSUE THREAD

**Issue by grassator** [zalando/skipper#243]
Currently skipper doesn't put FlowId in the access logs or in the application log, so this makes both correlating an access log entry with some downstream request pretty difficult and it makes impossible to correlate access log entry with other logging (e.g. some other filter's error report).

Would be nice if both things worked whenever a request has an `X-Flow-Id` header already or route has `flowId()` filter enabled.

**Comment by evangelion1204** [comment]
Maybe it could be checked if either `X-Flow-Id` is part of the request or the response - currently response header is being set by ` flowId()`.
