### ISSUE TITLE
Log gzip compressed requests

### ISSUE THREAD

**Issue by DziubaR** [zalando/skipper#2430]
I use okhttp3 and send gzip compressed requests.
I would like to log gzip requests. Currently this behaviour available only for gzip responses.

I would like to make contribution for this feature request, and I will attach a pr to this FR as soon as I have it

**Comment by szuecs** [comment]
What do you want to contribute?

I think you want to log the compressed body in a decompressed way.
LogBody filter I am implementing but it will take a while.
We would need to decompress the request also streaming and since I am on streaming facility it makes no sense to start working on this.

**Comment by szuecs** [comment]
This should work: `r: * -> compress() -> logBody("response") -> decompress() -> "https://test.example";`
