### ISSUE TITLE
Watch for changes in `routes-file`

### ISSUE THREAD

**Issue by mo-gr** [zalando/skipper#248]
If skipper is started with a `-routes-file` argument, it would be cool, if skipper would watch for changes to that file and update the routing tables accordingly.

**Comment by lmineiro** [comment]
I did some initial research with https://github.com/fsnotify/fsnotify, which seems to be the de facto standard for this.

So far, under Mac OS X this seems to be a luck game. The project mentions issues with Spotlight. I tried to apply the mentioned workarounds but they don't seem to really solve the problem.

The events I got:
```
[APP]INFO[0024] event: "example.eskip": CHMOD                
[APP]INFO[0024] event: "example.eskip": REMOVE               
[APP]INFO[0024] event: "example.eskip": CREATE               
[APP]INFO[0025] event: "example.eskip": CHMOD                
[APP]INFO[0041] event: "example.eskip": CHMOD                
[APP]INFO[0041] event: "example.eskip": REMOVE               
[APP]INFO[0041] event: "example.eskip": CREATE               
[APP]INFO[0041] event: "example.eskip": CHMOD                
[APP]INFO[0041] event: "example.eskip": REMOVE               
[APP]INFO[0041] event: "example.eskip": CREATE               
[APP]INFO[0044] event: "example.eskip": CHMOD                
[APP]INFO[0189] event: "example.eskip": CHMOD                
[APP]INFO[0191] event: "example.eskip": CHMOD                
[APP]INFO[0200] event: "example.eskip": RENAME 
```

And then it stopped working. The fsnotify seems to be the more elegant way to do this but there seems to be some shortcomings.

I'll test this on Linux (native and Docker) to see if it behaves any different.

**Comment by lmineiro** [comment]
https://github.com/andreaskoch/go-fswatch could be a reasonable alternative

**Comment by lmineiro** [comment]
Tests using https://github.com/rjeczalik/notify are more promising and seem to work fine under Mac OS X:

```
[APP]INFO[0024] detected changes (notify.Write) in routes file "example.eskip" 
[APP]INFO[0024] route settings, update, route: all: * -> "https://example.org" 
[APP]INFO[0024] route settings, update, route: foo: Path("/foo") -> setPath("/") -> "https://example.org" 
[APP]INFO[0024] route settings, update, route: bar: Path("/bar") -> setPath("/") -> "https://example.org" 
[APP]INFO[0024] route settings received                      
[APP]INFO[0024] route settings applied 
```

**Comment by kode4food** [comment]
@mo-gr I'm assuming the value proposition here is that you don't incur the explicit restart cost during development.  Is that correct?  Would there be any value to this feature existing once deployed into production?

**Comment by sarslanhan** [comment]
@lmineiro @mo-gr I have a version that works with https://github.com/fsnotify/fsnotify on MacOS. I also added support for loading & watching a whole directory (and its sub-directories) based on file extensions. There was already a discussion under #29 about a manifest file that could make extension based approach better.

I will try to send a PR in the next days.

**Comment by sarslanhan** [comment]
@kode4food for Zalando's use case I believe that is correct. I am not even sure if we use `-routes-file` option in production. I guess no.

But it would unblock features like #29 which again might not have a Zalando specific use case at the moment.  (not Github client but a general git client version)

However, in my opinion, as it is an open source tool, supporting different ways to load/update routes adds value and it might have an actual use case for another user.

I would also be interested in hearing other opinions.

**Comment by kode4food** [comment]
@sarslanhan for a development workflow, it's easy enough to monitor the files externally and bounce the service, no?  the cost shouldn't be too high because it's Go, not Java.  I guess my concern is over adding a bunch of overwhelmingly cold code paths to a key piece of infrastructure.

**Comment by sarslanhan** [comment]
@kode4food I actually think it is a lot nicer if we can add these data clients as separate packages and let the user decide which data clients to attach. I think it should be possible with a modified main file since the skipper [option](https://github.com/zalando/skipper/blob/master/skipper.go#L126) is already there.

**Comment by aryszka** [comment]
Indeed. Thanks for pointing this out. Considering that this issue hasn't had any activity for quite a while, I'm closing it.
