### ISSUE TITLE
Randomly occurring 499s HTTP response code issues ("context canceled" / "timeout awaiting response headers" errors)

### ISSUE THREAD

**Issue by bperun123** [zalando/skipper#2485]
**Describe the bug**
We see randomly occurring 499s ("context canceled" / "timeout awaiting response headers" errors) at Skipper backend side with the default configuration from the documentation (https://opensource.zalando.com/skipper/kubernetes/ingress-controller/#deployment) and also with a simplified env var configuration (see below).
We are using Skipper with a k8s-service deployment setup on GCP Autopilot v1.26.

We see this 499 behaviour at LUA HTTP client calls, webhooks and usual RouteGroup backend calls.
We have tried to adjust timeout backend config values. However we couldn't find fitting settings so far.
We also tried to turn off backend keepalive (just for testing), however this also didn't work for us.

Do you have any hints for us how to solve this issue?

Thanks a lot in advance!

**Some more detailed information and screenshots**
--- Example K8s RoutGroup config ---
![image](https://github.com/zalando/skipper/assets/67438899/fc036fef-24ce-4ac8-81ef-1cc217e141bc)

--- Skipper response codes 499 over the last 7 days ---
![image](https://github.com/zalando/skipper/assets/67438899/1fcf3bae-70d2-4b66-9c1e-941a970bb780)

--- Some Skipper logs ---
![image](https://github.com/zalando/skipper/assets/67438899/1272a9ba-367a-47ec-ae31-f779dc2a38f9)

![image](https://github.com/zalando/skipper/assets/67438899/488fbc69-f85f-4172-adaa-e7a0f1df1384)

![image](https://github.com/zalando/skipper/assets/67438899/958a4d6a-6b4e-4486-b7fe-39d1a1403c34)

--- Current skipper configuration ---
It is deployed as a K8s Deployment on v1.26 GKE Autopilot
```
image: registry.opensource.zalan.do/teapot/skipper:v0.16.154
args:
  - "skipper"
  - "-kubernetes"
  - "-kubernetes-in-cluster"
  - "-kubernetes-path-mode=path-prefix"
  - "-address=:9999"
  - "-wait-first-route-load"
  - "-proxy-preserve-host"
  - "-serve-host-metrics"
  - "-serve-route-metrics"
  - "-disable-metrics-compat"
  - "-enable-profile"
  - "-enable-ratelimits"
  - "-reverse-source-predicate"
  - "-experimental-upgrade"
  - "-metrics-exp-decay-sample"
  - "-metrics-flavour=prometheus"
  - "-lb-healthcheck-interval=3s"
  - "-enable-connection-metrics"
  - '-default-filters-prepend=enableAccessLog(4,5) -> lifo(2000,20000,"10s")'
  - "-max-audit-body=0"
  - "-histogram-metric-buckets=.0001,.00025,.0005,.00075,.001,.0025,.005,.0075,.01,.025,.05,.075,.1,.2,.3,.4,.5,.6,.7,.8,.9,1,2,3,4,5,7,10,15,20,30,60,120,300,600"
  - "-idle-timeout-server=620s" # Adjustment for GCP LB
  - "-credentials-paths=/home/secrets/"
  - "-credentials-update-interval=10m"
  - "-application-log-json-enabled=true"
  - "-access-log-json-enabled=true"
```

**To Reproduce**
1. Install Skipper with the settings above at GCP Autopilot v1.26
2. Connect backend calls with auth webhooks, backend and Lua HTTP calls
3. Test over time (hard to reproduce standalone)

**Expected behavior**
No 499s or "context exeeded/canceled errors"

**Observed behavior**
Randomly occurring 499s and "context exeeded" errors

**Comment by szuecs** [comment]
499 are client timeouts, so the client connecting to skipper has a timeout and closed the connection before it got a response. You need to investigate the client timeouts and you can check with tracing (opentracing/OTel) provider, skipper will write 499 status code in the "ingress" span, so you can check the trace to figure out the client.

**Comment by bperun123** [comment]
Thx for the fast reply, @szuecs.
Then we will investigate the client side in more detail (node backend) and post the solution if we find it.
OpenTelemetry doesn't work so far with Skipper, correct (at least some other Github issues said that)?

**Comment by bperun123** [comment]
@szuecs You were totally right. Timeouts didn't have anything to do with the backend site. We also could see "client_disconnected_before_any_response" at GCP LB Audit logs which confirms that these issues are caused by clients behavior.

Thanks a lot guys for your help and your great work!!
