### ISSUE TITLE
eskip check don't fail when backend is empty string

### ISSUE THREAD

**Issue by omigongar** [zalando/skipper#2523]
**Describe the bug**
`eskip check routes.eskip` don't fail if there's a route with backend is an empty string but `skipper -routes-file routes.eskip ` fails with the message `failed to process route foo: parse "": empty url `

**To Reproduce**
Using image base `registry.opensource.zalan.do/teapot/skipper:v0.16.67`  executing `eskip check routes.eskip` there's no failure.

Executing `skipper -routes-file test.eskip`
> [APP]INFO[0000] Expose metrics in codahale format            
> [APP]INFO[0000] enable swarm: false                          
> [APP]INFO[0000] Replacing tee filter specification           
> [APP]INFO[0000] Replacing teenf filter specification         
> [APP]INFO[0000] Replacing lua filter specification           
> [APP]INFO[0000] support listener on :9911                    
> [APP]INFO[0000] Dataclients are updated once, first load complete 
> [APP]INFO[0000] Listen on :9090                              
> [APP]INFO[0000] route settings, reset, route: foo: Path("/foo") -> setPath("/") -> "" 
> [APP]INFO[0000] route settings, reset, route: bar: Path("/bar") -> setPath("/") -> "https://bar.example.org/" 
> [APP]INFO[0000] route settings received                      
> **[APP]ERRO[0000] failed to process route foo: parse "": empty url** 
> [APP]INFO[0000] route settings applied                       
> [APP]INFO[0000] TLS settings not found, defaulting to HTTP 

`routes.eskip` file content 

> foo: Path("/foo") -> setPath("/") -> ""
> bar: Path("/bar") -> setPath("/") -> "https://bar.example.org/" 

**Expected behavior**
Consistent behaviour between `eskip` and `skipper`, if `skipper` fails loading routes with empty backend then `eskip` should also fail

**Observed behavior**

**Comment by AlexanderYastrebov** [comment]
@MustafaSaber FYI
