### ISSUE TITLE
Kubernetes: support authentication via serviceaccount (do not require kubectl proxy)

### ISSUE THREAD

**Issue by hjacobs** [zalando/skipper#254]
The Kubernetes data client should work out of the box with Kubernetes when deployed into a cluster without the need of a `kubectl` sidecar. It needs to read the Kubernetes service account credentials (token and `ca.crt`).

**Comment by hjacobs** [comment]
Basically we need/want to get rid of the `kubectl` sidecar here: https://github.com/zalando-incubator/kubernetes-on-aws/blob/dd208ff0dc8a7d2b069b927813857b5379ddbc7f/cluster/userdata-master.yaml#L1062

**Comment by ideahitme** [comment]
@aryszka I will implement this task if no objections :) basically there are two ways to go, one use https://github.com/kubernetes/client-go or manually implement client using service account assigned to skipper pod. Client-go is a better option IMO for compatibility purposes, and we would just need to vendor it and replace definitions and http calls to list services/ingress with client-go API calls. Currently skipper has hardcoded definitions for k8s http paths and resource definitions and if there is no particular reason for doing this (aside from not increasing binary size), I would go with client-go.

**Comment by ideahitme** [comment]
will not use client-go, as it seems like an overkill for having this simple functionality. 

PR: https://github.com/zalando/skipper/pull/290

**Comment by szuecs** [comment]
this was done long time ago
