### ISSUE TITLE
route health state as Prometheus metrics

### ISSUE THREAD

**Issue by universam1** [zalando/skipper#2595]
**Is your feature request related to a problem? Please describe.**
As discussed in [slack](https://gophers.slack.com/archives/C82Q5JNH5/p1691523249802909?thread_ts=1691075117.833439&cid=C82Q5JNH5) having the counters of `X-Count` and `X-Timestamp` exposed as Prometheus metrics would help to alert on a Skipper replica being out of sync.

**Describe the solution you would like**
Prometheus metric exposing those counters, for customer using Prometheus ecosystem for alerting.

**Describe alternatives you've considered (optional)**
Having to invent a new monitoring concept parsing the route health endpoints `http://{}:9911/routes`

**Would you like to work on it?**
Yes - with advice

**Comment by universam1** [comment]
FYI @szuecs

**Comment by AlexanderYastrebov** [comment]
Skipper /routes handler uses "routing" object. I guess we'd need to wire metrics in and update counters around here
https://github.com/zalando/skipper/blob/4b2d6eb2161f726f1b6648de45b5e354c4896056/routing/routing.go#L364-L373

**Comment by universam1** [comment]
closed via #2597
