### ISSUE TITLE
Improve windows release

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/skipper#2666]
**Is your feature request related to a problem? Please describe.**

Currently we pack windows release into tar.gz archive and binaries do not have .exe filename extension.
```
~$ tar -C /tmp/ -xzf ~/tmp/skipper-v0.18.24-windows-amd64.tar.gz 
~$ ls /tmp/skipper-v0.18.24-windows-amd64/
eskip  routesrv  skipper  webhook
~$ file /tmp/skipper-v0.18.24-windows-amd64/skipper 
/tmp/skipper-v0.18.24-windows-amd64/skipper: PE32+ executable (console) x86-64, for MS Windows
```

**Describe the solution you would like**

Pack windows release into more commonly supported zip archive and use .exe filename extension for binaries.

**Would you like to work on it?**

No

**Comment by rasmushanning** [comment]
Hi! I made an attempt at solving this issue in #2671

**Comment by AlexanderYastrebov** [comment]
@rasmushanning Thank you
