### ISSUE TITLE
implementing the -indent option

### ISSUE THREAD

**Issue by LappleApple** [zalando/skipper#270]
From @aryszka: 

"in our practice, two spaces became a de-facto standard. It could be the default for the tool, too. For overriding, I would prefer a single option, where one can specify just anything as the atomic indentation:

-indent "    "

the value of this parameter could be validated with "\s*", because we accept all \s when parsing eskip."

See more [here](https://github.com/zalando/skipper/issues/97#issuecomment-278053006).

**Comment by AlexanderYastrebov** [comment]
Should this be closed?
