### ISSUE TITLE
improve the tee() filter

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#271]
Let's use this entry to collect additional requirements to the tee() filter and consider them together to improve it with keeping backwards compatibility.

**Comment by aryszka** [comment]
Improvement: allow the user to decide whether the branched requests should follow redirects or not.

**Comment by szuecs** [comment]
@aryszka I close this because I do not understand what other options are required. We have now tee() and teenf() to have both supported, or do I miss something?
If so please reopen.
