### ISSUE TITLE
Backend type: loopback

### ISSUE THREAD

**Issue by mo-gr** [zalando/skipper#274]
Currently, skipper supports two types of backends: shunts and hosts. I suggest adding a third type of backend named `<loopback>` (name open for discussion).

What this backend type would do, is re-execute the whole routing and filterchain a second time for the given request. This of course only makes sense if the filters leading up to this endpoint have modified the request. Otherwise, the endpoint must throw an error to avoid internal redirect loops.

## Motivation

We observed quite a few use-cases, that are hard or impossible with the current skipper but could be solved elegantly with multiple cascading skippers. However, cascading skippers add unnecessary network hops. This feature could therefore be seen as an optimization to situations, where multiple skippers are cascaded behind each other. 
However, it is not as strong as cascading skippers. The loopback is not a complete substitute for cascading skippers, but it covers the majority of use-cases in an elegant and performant way.

## Example

Consider the use-case where the routing decision between two similar routes is based on the response of a remote service (for example an A/B test). Naturally, we do not want to call services for all routing decisions, as this would add cost to _all_ routes, not just the two routes in question.

But having a cascading setup of skipper would allow us to first isolate the two routes, then call the service to make the decisiosn, then pass on to the second skipper to actually handle the two routes. With the loopback, this could all happen within the same skipper. In eskip, this would look like the following:

```
pageUnderTest: Path("/foo")
  -> callABTestService() // this will call a service and add a header
  -> <loopback>;

pageVariantA: Path("/foo") && Header("X-Test-Variant", "A")
  -> filtersForVariantA()
  -> "https://a.example.org";

pageVariangB: Path("/foo") && Header("X-Test-Variant", "B")
  -> filtersForVariangB()
  -> "https://b.example.org";
```

Note: The filter `callABTestService()` must ensure that the incoming request gets the header `X-Test-Variant` appended to it in any case. If the filter would fail to add the header, the request would loop back in to the route `pageUnderTest`.

## Specification

- The `loopback` endpoint must reevaluate the routing and filter chain for the previously modified (by the filters) request.
- The `loopback` endpoint must be able to detect infinite loops and abort the request with an appropriate error (either invalid request or server error?)
- Skipper should support an arbitrary number of loopbacks as long as they are not looping

## Open Questions
- Should the loopback reuse the same `StateBag`/`RequestContext` or generate a new one? My gut feeling says reuse the `StateBag`, but this could violate assumptions made by other filters.
- [EDIT] What would be the expected behavior when collecting metrics for a request?

**Comment by aryszka** [comment]
i think the context should be reused. For the statebag: good question. We would need to collect some data about the current usage.

**Comment by aryszka** [comment]
it is imporant to emphasize the need for protection against infinite looping. If reusing the context, then one possible way would be to have a counter. The initial value would be a global config of the proxy instance, and if reaches zero, the proxy would return with an error.

**Comment by mo-gr** [comment]
Regarding infinite looping: An alternative would be a set containing the route-ids already used in processing this request. As soon, as a route is chosen the second time, return with an error. (circle-detection)

**Comment by aryszka** [comment]
with looping, routes can change during the lifetime of the same request. so to me, the counter feels safer. wondering now, whether the routing changes can cause any other issues with looping..

**Comment by mo-gr** [comment]
Ok, so a new configuration along the lines of `maxInternalRedirects` is the way we go? Sounds reasonable.

**Comment by DeTeam** [comment]
@aryszka closing this one?

**Comment by aryszka** [comment]
yes, thx for pointing out :+1:

**Comment by aryszka** [comment]
done in: https://github.com/zalando/skipper/pull/331
