### ISSUE TITLE
Query predicate is giving inconsistent results

### ISSUE THREAD

**Issue by sepehrdaddev** [zalando/skipper#2848]
**Describe the bug**
[FuzzQuery](https://github.com/zalando/skipper/pull/2846/files#diff-7609f6a76165737f4e7c45a2db96c700297f9808b8a8a4a19d7e11589080907d) fuzz target found an inconsistency in [QueryParam](https://opensource.zalando.com/skipper/reference/predicates/#queryparam) predicate where the Predicate doesn't match for the same value.

the fuzzer panics when the Args is the following:
```go
args := Args{Key: "\x00", Value: "\x24\x00\x00"}
```

**To Reproduce**
apply the following patch:
```diff
diff --git a/predicates/query/query_test.go b/predicates/query/query_test.go
index 43e49dba..0107405d 100644
--- a/predicates/query/query_test.go
+++ b/predicates/query/query_test.go
@@ -56,6 +56,16 @@ func TestQueryArgs(t *testing.T) {
 		[]interface{}{"key", `\`},
 		0,
 		true,
+	}, {
+		"hex 1",
+		[]interface{}{"\x00"},
+		exists,
+		true,
+	}, {
+		"hex 2",
+		[]interface{}{"\x00", "\x00"},
+		exists,
+		true,
 	}} {
 		func() {
 			p, err := New().Create(ti.args)
@@ -128,6 +138,12 @@ func TestMatchArgs(t *testing.T) {
 		"key",
 		[]string{"value", "value2"},
 		false,
+	}, {
+		"hex 3",
+		[]interface{}{"\x00", "\x24\x00\x00"},
+		"\x00",
+		[]string{"\x24\x00\x00"},
+		true,
 	},
 	} {
 		func() {

```

then run `go test` in the `predicates/query`

**Expected behavior**
QueryParam must provide consistent results

**Comment by sepehrdaddev** [comment]
@szuecs as discussed earlier.

**Comment by AlexanderYastrebov** [comment]
I think these are false positives.
First two should not error
```
	, {
		"hex 1",
		[]interface{}{"\x00"},
		exists,
		false,
	}, {
		"hex 2",
		[]interface{}{"\x00", "\x00"},
		matches,
		false,
	}
```

The third one `"\x24\x00\x00"` is `"$\0\0"` which correctly does not match as `$` is the end of the line.
When argument is fixed to ` "\x5c\x24\x00\x00"` (`"\\$\0\0"`) then it works as expected matching dollar sign.

**Comment by sepehrdaddev** [comment]
@AlexanderYastrebov seems like you are right, I will change the fuzzer to take this into account (I tested this it seems to be regex vs string issue)

thx a lot for checking this, I will close it as a non-issue.
