### ISSUE TITLE
ClientIP predicate is giving inconsistent results

### ISSUE THREAD

**Issue by sepehrdaddev** [zalando/skipper#2852]
**Describe the bug**
[FuzzClientIP](https://github.com/zalando/skipper/pull/2846/files#diff-84e4882219d180a437d9fff5d2316ba969545913914487f865a79c87096b2d00) fuzz target found an inconsistency in [ClientIP](https://opensource.zalando.com/skipper/reference/predicates/#clientip) predicate where the Predicate doesn't match for the same value.

the fuzzer panics when the ip address is `::`

**To Reproduce**
apply the following patch:
```diff
diff --git a/predicates/source/source_test.go b/predicates/source/source_test.go
index e52efac8..d77bda80 100644
--- a/predicates/source/source_test.go
+++ b/predicates/source/source_test.go
@@ -299,6 +299,11 @@ func TestMatchingClientIP(t *testing.T) {
                []interface{}{"C0:FF::EE/127"},
                &http.Request{RemoteAddr: "[C0:FF::EC]:1234"},
                false,
+       }, {
+               "invalid case",
+               []interface{}{"::"},
+               &http.Request{RemoteAddr: "::"},
+               true,
        }} {
                t.Run(ti.msg, func(t *testing.T) {
                        pred, err := (&spec{typ: clientIP}).Create(ti.args)
   
```

then run `go test` in the `predicates/source`

**Expected behavior**
ClientIP must provide consistent results

**Comment by szuecs** [comment]
But `::` is not a valid client IP.

The input data is like here:
```
% go doc http.Request.RemoteAddr
package http // import "net/http"

type Request struct {
    // RemoteAddr allows HTTP servers and other software to record the network address
    // that sent the request, usually for logging. This field is not filled in by
    // ReadRequest and has no defined format. The HTTP server in this package sets
    // RemoteAddr to an "IP:port" address before invoking a handler. This field is
    // ignored by the HTTP client.
    RemoteAddr string
```

Of course in local tests you can define it different but you won't be able to create a call to http.Server, such that this will lead to `::` as RemoteAddr.

**Comment by AlexanderYastrebov** [comment]
> the fuzzer panics when the ip address is ::

Hm, is there a panic in skipper code?

**Comment by sepehrdaddev** [comment]
@szuecs yes, thats clear that `::` is not a valid IP but the reason why I created an issue is that, I would expect it to throw an error during the predicate creation saying that its not a valid IP rather than accepting it and then not being able to enforce it.

**Comment by sepehrdaddev** [comment]
@AlexanderYastrebov so, I wrote the fuzzer in a way that if it finds something that is not correct, it would [panic](https://github.com/zalando/skipper/pull/2846/files#diff-84e4882219d180a437d9fff5d2316ba969545913914487f865a79c87096b2d00R21), this is because the fuzzer only detects panics, so anything unexpected must panic to be able to detect it.

so no, there is no panic in skipper code.

**Comment by AlexanderYastrebov** [comment]
I think we can trust RemoteAddr as it comes form the server. Do we need to fix this at all?

**Comment by szuecs** [comment]
I think it's fine to fix it because it's a generic function in skipper's net package.

**Comment by sepehrdaddev** [comment]
I think, this is an error case that hasn't been covered by the library which is important when using skipper as a library but its not something that causes a huge problem, its more a usability issue than anything else (I see Sandor already created a patch for it).
