### ISSUE TITLE
OAuth2CallbackPath using https when no TLS is defined

### ISSUE THREAD

**Issue by n123456789k** [zalando/skipper#2898]
**Describe the bug**
When running locally and using `OAuth2CallbackPath` - `/callback` It will pass `https://` protocol in the url callback when the server TLS settings are not found and defaults to http.

Logs for TLS:
```
{"level":"info","msg":"TLS settings not found, defaulting to HTTP","time":"2024-02-01T00:00:00Z"}
```

Route:
```
callback: Path("/callback")
    -> grantCallback()
    -> <shunt>;
```

**To Reproduce**
Run from localhost with no TLS config, add the callback uri, set your oauth2 provider callback to be `http://localhost/callback`

**Expected behavior**
Not to pass `https://` and use `http://` when no TLS config defined

**Observed behavior**
`https://localhost/callback` is being passed, which doesn't match the redirect uri on the oauth2 provider.

**Comment by AlexanderYastrebov** [comment]
Hello, please check whether `-oauth2-grant-insecure` flag introduced by https://github.com/zalando/skipper/pull/2457 solves your problem.
