### ISSUE TITLE
Kubernetes: handle sigterm to support graceful shutdown in daemonsets

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#298]
The scenario would look like this:

1. handle SIGTERM
2. when received, disable the healthcheck but continue serving
3. get killed by the kubelet

@hjacobs please add the required details

**Comment by hjacobs** [comment]
That sounds about right.

**Comment by szuecs** [comment]
closed in favour of #307

**Comment by aryszka** [comment]
done in #307
