### ISSUE TITLE
glob standard for free wildcards?

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#30]
it could be tested if /some/path/** works, and then it could be mentioned in the documentation.

https://github.com/zalando/skipper/pull/28#discussion_r43122909
https://github.com/zalando/skipper/pull/28#discussion_r43139473

**Comment by LappleApple** [comment]
Is this done yet?

**Comment by lmineiro** [comment]
No. It's a potential enhancement with very low priority.

**Comment by aryszka** [comment]
Just tested. It works.
