### ISSUE TITLE
Kubernetes dataclient race condition

### ISSUE THREAD

**Issue by ese** [zalando/skipper#304]
I am testing skipper with k8s and I am having weird behaviour with some requests that are ending arbitrarily in different endpoints.
Finally I think it can be a race condition while skipper is pulling routes from Ingress resources and a general route is loaded before the specific one that should be use. This happens all the time so I think skipper is reloading the rules constantly even if there is no changes in Ingress resources

I was doing some tests loading exactly the same routes with a static file and all requests works as expected. Some of this makes sense? Somebody with more experience with the code has some clue about what can be happening?

**Comment by hjacobs** [comment]
@ese thanks for checking out Skipper+Kubernetes --- I haven't experienced such problems yet (but I'm also no Skipper expert). We use it in production, but I think we only use path-based Ingress routing in one or two places (all other Ingress resources use only host-based routes). Can you describe your setup and how your Ingress looks like?

**Comment by hjacobs** [comment]
@ese you can also enable `DEBUG` logging to see what's going, like https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/skipper/daemonset.yaml#L38

**Comment by ese** [comment]
This is the use-case:

A service with a default route to send all requests. An ingress resource something like this:
```yaml
[...]
  rules:
  - host: test.local
    http:
      paths:
      - backend:
          serviceName: default-service
          servicePort: 80
        path: /
```
translated in eskip to `kube_default_service__test_local___: Host(/^test[.]local$/) && PathRegexp(/\//) -> "http://100.68.83.203:80";`

And another ingress with specific paths to send requests to another service (In our case 380 rules)
```yaml
  rules:
  - host: test.local
    http:
      paths:
[...]
      - backend:
          serviceName: specific-service
          servicePort: 3000
        path: /tr/stad
      - backend:
          serviceName: specific-service
          servicePort: 3000
        path: /tr/spat
      - backend:
          serviceName: specific-service
          servicePort: 3000
        path: /tr/work
      - backend:
          serviceName: specific-service
          servicePort: 3000
        path: /work
[...]
```
translated to eskip to a bunch of lines :)

**Comment by ese** [comment]
Here is a log about the issue. One of the backend responds with 200 to the path an another 301. It is supposed to reach always the same backend but the requests are reaching both. When there is a change in the behaouviour is always when skipper reload the rules:

```yaml
[APP]time="2017-03-30T22:15:24Z" level=info msg="route settings, update, route: kube__healthz: Path("/kube-system/healthz") && Source("10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "127.0.0.1/32", "fd00::/8", "::1/32") -> status() -> <shunt>" 
[APP]time="2017-03-30T22:15:24Z" level=info msg="route settings received" 
[APP]time="2017-03-30T22:15:25Z" level=info msg="route settings applied" 
XX.XX.XX.XX - - [30/Mar/2017:22:15:25 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 188 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:27 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 55 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:28 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 74 test.local
[APP]time="2017-03-30T22:15:28Z" level=info msg="route settings, update, route: kube__healthz: Path("/kube-system/healthz") && Source("10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "127.0.0.1/32", "fd00::/8", "::1/32") -> status() -> <shunt>" 
[APP]time="2017-03-30T22:15:28Z" level=info msg="route settings received" 
[APP]time="2017-03-30T22:15:28Z" level=info msg="route settings applied" 
XX.XX.XX.XX - - [30/Mar/2017:22:15:29 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 144 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:30 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 71 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:31 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 81 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:32 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 57 test.local
[APP]time="2017-03-30T22:15:32Z" level=info msg="route settings, update, route: kube__healthz: Path("/kube-system/healthz") && Source("10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "127.0.0.1/32", "fd00::/8", "::1/32") -> status() -> <shunt>" 
[APP]time="2017-03-30T22:15:32Z" level=info msg="route settings received" 
[APP]time="2017-03-30T22:15:32Z" level=info msg="route settings applied" 
XX.XX.XX.XX - - [30/Mar/2017:22:15:33 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 201 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:34 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 129 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:34 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 62 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:35 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 56 test.local
[APP]time="2017-03-30T22:15:36Z" level=info msg="route settings, update, route: kube__healthz: Path("/kube-system/healthz") && Source("10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "127.0.0.1/32", "fd00::/8", "::1/32") -> status() -> <shunt>" 
[APP]time="2017-03-30T22:15:36Z" level=info msg="route settings received" 
[APP]time="2017-03-30T22:15:36Z" level=info msg="route settings applied" 
XX.XX.XX.XX - - [30/Mar/2017:22:15:36 +0000] "GET /test-path HTTP/1.1" 301 0 "" "curl/7.47.0" 27 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:37 +0000] "GET /test-path HTTP/1.1" 301 0 "" "curl/7.47.0" 1 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:38 +0000] "GET /test-path HTTP/1.1" 301 0 "" "curl/7.47.0" 1 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:39 +0000] "GET /test-path HTTP/1.1" 301 0 "" "curl/7.47.0" 2 test.local
[APP]time="2017-03-30T22:15:40Z" level=info msg="route settings, update, route: kube__healthz: Path("/kube-system/healthz") && Source("10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "127.0.0.1/32", "fd00::/8", "::1/32") -> status() -> <shunt>" 
[APP]time="2017-03-30T22:15:40Z" level=info msg="route settings received" 
[APP]time="2017-03-30T22:15:40Z" level=info msg="route settings applied" 
XX.XX.XX.XX - - [30/Mar/2017:22:15:40 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 138 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:41 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 51 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:42 +0000] "GET /test-path HTTP/1.1" 200 21686 "" "curl/7.47.0" 65 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:43 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 64 test.local
[APP]time="2017-03-30T22:15:44Z" level=info msg="route settings, update, route: kube__healthz: Path("/kube-system/healthz") && Source("10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "127.0.0.1/32", "fd00::/8", "::1/32") -> status() -> <shunt>" 
[APP]time="2017-03-30T22:15:44Z" level=info msg="route settings received" 
[APP]time="2017-03-30T22:15:44Z" level=info msg="route settings applied" 
XX.XX.XX.XX - - [30/Mar/2017:22:15:44 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 55 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:45 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 51 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:46 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 60 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:47 +0000] "GET /test-path HTTP/1.1" 200 21687 "" "curl/7.47.0" 71 test.local
[APP]time="2017-03-30T22:15:47Z" level=info msg="route settings, update, route: kube__healthz: Path("/kube-system/healthz") && Source("10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "127.0.0.1/32", "fd00::/8", "::1/32") -> status() -> <shunt>" 
[APP]time="2017-03-30T22:15:47Z" level=info msg="route settings received" 
[APP]time="2017-03-30T22:15:47Z" level=info msg="route settings applied" 
XX.XX.XX.XX - - [30/Mar/2017:22:15:48 +0000] "GET /test-path HTTP/1.1" 301 0 "" "curl/7.47.0" 2 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:49 +0000] "GET /test-path HTTP/1.1" 301 0 "" "curl/7.47.0" 1 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:50 +0000] "GET /test-path HTTP/1.1" 301 0 "" "curl/7.47.0" 1 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:51 +0000] "GET /test-path HTTP/1.1" 301 0 "" "curl/7.47.0" 1 test.local
[APP]time="2017-03-30T22:15:51Z" level=info msg="route settings, update, route: kube__healthz: Path("/kube-system/healthz") && Source("10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "127.0.0.1/32", "fd00::/8", "::1/32") -> status() -> <shunt>" 
[APP]time="2017-03-30T22:15:51Z" level=info msg="route settings received" 
[APP]time="2017-03-30T22:15:51Z" level=info msg="route settings applied" 
XX.XX.XX.XX - - [30/Mar/2017:22:15:52 +0000] "GET /test-path HTTP/1.1" 301 0 "" "curl/7.47.0" 102 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:53 +0000] "GET /test-path HTTP/1.1" 301 0 "" "curl/7.47.0" 3 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:54 +0000] "GET /test-path HTTP/1.1" 301 0 "" "curl/7.47.0" 1 test.local
XX.XX.XX.XX - - [30/Mar/2017:22:15:54 +0000] "GET /test-path HTTP/1.1" 301 0 "" "curl/7.47.0" 1 test.local
```

I dont paste debug logs becouse I think it doesn't offer extra relevant information and is very difficult to follow it 

I saw that skipper poll the same k8s API endpoints for every path in the ingress resource, maybe it would be nice cache it and not repeat it if that service was already polled.

```yaml
[APP]time="2017-03-30T22:34:15Z" level=debug msg="making request to: https://100.64.0.1:443/api/v1/namespaces/default/services/specific-service" 
[APP]time="2017-03-30T22:34:15Z" level=debug msg="request to https://100.64.0.1:443/api/v1/namespaces/default/services/specific-service succeeded" 
[APP]time="2017-03-30T22:34:15Z" level=debug msg="service port as number: 3000" 
[APP]time="2017-03-30T22:34:15Z" level=debug msg="requesting service: default/specific-service" 
[APP]time="2017-03-30T22:34:15Z" level=debug msg="making request to: https://100.64.0.1:443/api/v1/namespaces/default/services/specific-service" 
[APP]time="2017-03-30T22:34:15Z" level=debug msg="request to https://100.64.0.1:443/api/v1/namespaces/default/services/specific-service succeeded" 
[APP]time="2017-03-30T22:34:15Z" level=debug msg="service port as number: 3000" 
[APP]time="2017-03-30T22:34:15Z" level=debug msg="requesting service: default/specific-service" 
[APP]time="2017-03-30T22:34:15Z" level=debug msg="making request to: https://100.64.0.1:443/api/v1/namespaces/default/services/specific-service" 
[APP]time="2017-03-30T22:34:15Z" level=debug msg="request to https://100.64.0.1:443/api/v1/namespaces/default/services/specific-service succeeded"
```

**Comment by hjacobs** [comment]
@ese thanks for your report, I guess @aryszka or @lmineiro might take a look.

**Comment by lmineiro** [comment]
Thanks for reporting this.

Do those 400 rules use the Path() predicate or PathRegexp() ? It makes a difference. Exact path matches have the highest priority during matching.

If they're using PathRegexp(), this may be due to how Skipper handles routes with the same "weight
" (usually, the same amount/type of predicates).

In this case, the chosen route is non deterministic. At update time the memory structures will be built with different order. This seems to be your case.

The way for you to test this would be add some "dummy" predicate to one of them to make it more specific, hence, getting higher priority. Try, for example, Method("GET") and test with a GET request if it starts behaving deterministically.

After finding this, we may be able to help further.

**Comment by lmineiro** [comment]
I just realised (thanks @hjacobs ) that the 400 rules are coming directly from the Ingress.

After looking at the data client implementation it seems to be the case that they're created with PathRegexp() https://github.com/zalando/skipper/blob/master/dataclients/kubernetes/kube.go#L349

We'll check this and report back with some possible solution(s)

**Comment by hjacobs** [comment]
@aryszka apparently is on this topic according to @lmineiro

**Comment by aryszka** [comment]
@ese do I understand correctly that the requests go to the default-service when you expect them to go to the specific service? In that case, what I recommend as a quick fix, is to remove the 'path: /' entry from the default-service rule. Based on the spec, it is possible, will check it in a bit.

Even better could be to use the the default ingress backend, if that works for you: https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_ingressspec

```
backend:
  serviceName: default-service
  servicePort: 80
rules:
  [...]
```

The reason for the observed behavior is something that @lmineiro already explained: all these routes had the same priority, and the expressions '/' and '/foo/bar' overlap. By removing the path from the default backend, it will have a lower priority.

This non-deterministic way of which route is matched first, is on purpose, and every PathRegexp() predicate has equal priority. Normally, one would use the Path() predicate that implements a tree lookup and is evaluated before the other predicates, but enabling that in the Kubernetes ingress client is still to be done.

Let us know, please, if these quick fixes work for you.

@hjacobs @lmineiro : I think until the spec supports different path matching, we could enforce the path tree with a special flag in the metadata. What makes using the path tree somewhat hard with the current spec are mainly these two statements: "Path is an extended POSIX regex..." and "Paths must begin with a /". We already checked, and "^/" doesn't work. What do you think about the metadata in the ingress item?

**Comment by ese** [comment]
@aryszka Thanks for your proposal.

The thing is with default backend in the ingress resource you can't define a domain so you end with a wildcard rule and we want that specific default service only to for a specific domain. I think that kind of definition is not feasible with current ingress resource :disappointed: 

But trying a rule like this to use as default backend is working well so we can move to find a workaround.

```
rule____: Host(/^example[.]com$/) -> "http://100.68.83.203:80";                                                    
```

Apart of this we also detected some overlapping in rules when you specify for example this paths like `/foo` and `/bar/foo`, since `/foo` match in both cases. So since all paths in kubernetes ingress must starts with `/` we think it is reasonable to append `^` at the beggining of the expression to avoid this overlapping.
https://github.com/zalando/skipper/pull/305

**Comment by aryszka** [comment]
@ese thanks

i think this can solve part of the problems, but i would keep the issue open for now, because there can be still conflicts, e.g. with paths like /foo and /.*. We'll test a potential solution using a combination of PathRegexp() and PathSubtree() internally.

**Comment by aryszka** [comment]
closing this issue for https://github.com/zalando/skipper/issues/360
