### ISSUE TITLE
static filter: can make a log warning if the local path is not available

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#32]
https://github.com/zalando/skipper/pull/28#discussion_r43128631

**Comment by LappleApple** [comment]
Added yet? If there are a lot of these docs-related issues filed, I'd just add them directly as a to-do list on #28 and close all these issues.

**Comment by lmineiro** [comment]
This seems like a good issue for someone that wants to get started contributing to skipper. Should be relatively simple and easy with low risk

**Comment by aryszka** [comment]
how about creating a more generic "improve logging" issue? One thing that could be about is to make the modules accept a generic logging object, by providing an interface. This makes it flexible for projects that use skipper as a lib, plus it also helps testing in some cases. See https://github.com/zalando/skipper/pull/189/files#diff-7a3cafdda88442b1b3b129de879f5441R1 in #189 

the small, trivial logging improvements like this could be bundled with that issue.

on the other hand, it is true that this a quite safe place to start with contribution.
