### ISSUE TITLE
List current rules

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#320]
It would be nice to have an API endpoint to list the current rules from the management port for example:

    % curl localhost:9911/routes 
    ...skipper routes here...

Best would be if we could also specify the Content-Type: application/json for example.

**Comment by jreyeshdez** [comment]
Skipper would need to have a new http Handler for this request but, what would it be its behavior if no route is defined in routes-file for /routes? Should it be bypassed somehow?

**Comment by aryszka** [comment]
my understanding is that in this case it would just return an empty response, meaning there are no routes. This would be on a separate port and not on the main serving port, so no need to define this endpoint in the configuration for the routing.

**Comment by szuecs** [comment]
Since we have :mgmtport/routes which lists routes in eskip format, I consider this as done.
In case you need json format please add a new issue referencing this one.
