### ISSUE TITLE
Add flag for logs in json format

### ISSUE THREAD

**Issue by milosradovanovic** [zalando/skipper#326]
It would be nice to have config param to enable logs in json format. 
That way logs shall look like:

{"duration":68,"host":"::1","level":"info","method":"GET","msg":"","proto":"HTTP/1.1","referer":"","requested-host":"localhost:8088","response-size":0,"status":304,"time":"2017-05-05T17:20:55+02:00","timestamp":"05/May/2017:17:20:55 +0200","uri":"/v2/customers/","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"}

**Comment by jreyeshdez** [comment]
There is no need to output "time":"2017-05-05T17:20:55+02:00" and "timestamp":"05/May/2017:17:20:55 +0200" ; I think it is enough to just have the latter ("timestamp":"23/Jun/2017:10:23:06 +0100")

The above can be achieved by using custom Timestamp Format and by disabling automatic timestamps in output in JSONFormatter.

**Comment by aryszka** [comment]
@milosradovanovic @jreyeshdez can we considered this completed by https://github.com/zalando/skipper/pull/357 ? Please feel free to reopen it or create a new issue if something is missing.

**Comment by jreyeshdez** [comment]
@aryszka I am happy with it. If there is any issue related to it, please let me know.

**Comment by milosradovanovic** [comment]
Looks good. Thanks
