### ISSUE TITLE
zsh: command not found: eskip

### ISSUE THREAD

**Issue by stevoPerisic** [zalando/skipper#351]
Trying to run the skipper via the directions given in the readme file, however trying ```eskip check example.eskip``` only returns "command not found: eskip". Please help.

**Comment by stevoPerisic** [comment]
Figured it out, one must run the ```./skipper`` and ```./eskip``` commands instead of just skipper, eskip. Closing this.

**Comment by aryszka** [comment]
@stevoPerisic that's right. If you use the GOPATH and add $GOPATH/bin to $PATH, and use go install ./... in skipper, then the two commands should be accessible from the path.
