### ISSUE TITLE
migrate skoap into skipper

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#366]
Migrating Skoap [https://github.com/zalando-incubator](https://github.com/zalando-incubator) would make a lot of sense because many default scenarios of skipper could benefit from it, while after migration, skipper could be used as a drop-in replacement of Skoap, without loosing any feautres.

Issues to take care of:
- verify that the authentication api that Skoap is calling is following the oauth2 standards
- define a formal web hook interface to support the current team service dependency in Skoap so that any user can plug in their own implementation or provide an API translation layer if the team service is required
- rename 'team' to 'group' so that it has a more generic meaning

Plan:
1. in the first step migrate the tests and the implementation of Skoap with small changes to skipper, ideally the auth filter under the package filters/oauth (open for better naming), and the command under cmd/skoap (let's keep the legacy name). The audit filter should go to its own package, if there's no better suggestion then under filters/audit. Mark this phase as experimental, because it is possible that backwards incompatible changes will be required in the further steps. At the same time, give an early notice in the Skoap repository about the migration. Suggested deadline before Skoap gets deleted: 2017.08.15
2. consider saving over the work in this WIP PR of Skoap: https://github.com/zalando-incubator/skoap/pull/12 . This should provide browser support with authentication redirects to an oauth provider for human users. (Check other similar efforts: i am aware of a less general, but already working approach that can be useful to add to skipper, but infortunately not yet open-source.)
3. at this phase it should be possible to delete the Skoap repo. RIP
4. finalize the oauth API, and settle the group web hook definition for the group service

**Comment by aryszka** [comment]
further improvements after phase 3:
- add proper timeouts for the service calls

**Comment by aryszka** [comment]
WIP PR here: https://github.com/zalando/skipper/pull/367

**Comment by szuecs** [comment]
I think we have everything we need for oauth in the mentioned cases and with https://github.com/zalando/skipper/issues/744 everyone can build there "group" filter.
