### ISSUE TITLE
Route api calls through skipper??

### ISSUE THREAD

**Issue by fjvierap** [zalando/skipper#376]
Hi,

Checking this issue https://github.com/zalando/tailor/issues/132#issuecomment-289533687...

Could you please let me know which are the advantages of routing api request through skipper in compared with some api gateways service?

Thanks in advance.

**Comment by szuecs** [comment]
@fjvierap It would be nice to get a better understanding what your request is about, so please can you answer some questions:

- Which API gateways service are you referring to? 
- What kind of features do you need from an api gateway? 
- What goal do you have?

My personal opinions:
- Skipper is proven to be fast and is indeed core infrastructure of Zalando.
- Skipper does not need to reload (use etcd backend) to get new routes populated
- Skipper has Kubernetes integration, if you need more dynamic routing. For example in Kubernetes you will often get new Ingress, Services and PODs, so Skipper watches the kube-apiserver to build proper routes to Kubernetes service backends.

**Comment by fjvierap** [comment]
@Shinzu Thanks for your quick answer.

- Which API gateways service are you referring to? Zuul or api connect 
- What kind of features do you need from an api gateway? Initially load balancing to endpoints, circuit breaker, monitoring.
What goal do you have? 
The main goal is to break a break a monolithic application following strangler pattern. We need to route only request most of the request to the existing monolithic system... but the route certain requests to new application based on microservices. 

Also we need to keep sessions between monolithic and new apps. So we are considering skipper as a routing engine engine for the solution. And also we are thinking about send the api calls to skipper.

I think we might have incremental rollout API deployments and API AB Testing routing API in skipper.

Would you recommend using skipper for API routing in the given scenario or you see some const I am not aware?

Thanks in advance

**Comment by Shinzu** [comment]
@fjvierap i think that answer is for @szuecs

**Comment by szuecs** [comment]
@fjvierap I don't know Zuul nor api connect, but everything you want to do sounds for me exactly what we did to split our monolith..

**Comment by fjvierap** [comment]
@szuecs 

Great... In principle it this skipper suits quite well in our approach.
Thank you so much.
