### ISSUE TITLE
Support Rate Limiting for K8s Ingress

### ISSUE THREAD

**Issue by ChristianLohmann** [zalando/skipper#382]
We set up an nginx reverse proxy to establish rate limiting on a k8s application:

```
limit_req_zone $binary_remote_addr zone=by_ip:10m rate=100r/s;
    limit_req_zone $http_authorization zone=by_oauth_token:100m rate=1r/m;
    limit_req_zone $request_uri zone=by_uri:10m rate=100r/m;
    limit_req_status 429;

    server {
        listen 80;

        location / {
            proxy_pass_header       Host;
            proxy_pass_header       X-Forwarded-For;
            proxy_pass_header       X-Forwarded-Proto;
            proxy_pass_header       X-Forwarded-Port;
            limit_req zone=by_ip burst=100;
            proxy_pass http://localhost:8080;
        }
```

It would be nice to have rate limiting support directly for the ingress YAML resource. For example as annotation...

**Comment by Raffo** [comment]
Given that this is Kubernetes related, [istio](https://istio.io/) provides this feature: https://github.com/istio/istio.github.io/blob/master/_docs/tasks/rate-limiting.md

**Comment by szuecs** [comment]
@ChristianLohmann can you please specify the attributes that you would like to choose from an ingress.
We need a better specification to add this feature.

**Comment by hjacobs** [comment]
@szuecs I asked @ChristianLohmann to add this feature request to not forget about it, we don't have a annotation proposal at the moment. I guess this feature is something "for later".

**Comment by szuecs** [comment]
@hjacobs as OpenSource project maintainer I strongly believe we should define issues well and not as fast as possible to forget something. We should show that we believe in OpenSource and do the right thing to make this great. If there will be no good spec provided I will close the issue. We can get help from the community if we have nice and clear specs. Rate Limiting is a not so complicated feature if it's well defined how this should work.

**Comment by szuecs** [comment]
Close in favour of #414
