### ISSUE TITLE
provide possibility to set exact, non-regexp host predicates

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#386]
it's a typical use case to match every route by the request host header, but the host values don't show a high variance, and so it is not very effective to execute a regular expression for every route to be matched. It could improve the lookup performance in many scenarios if there was an exact Host matching predicate, e.g:

```
HostExact("www.example.org")
```

On the other hand, it is also a typical use case to match different TLDs, e.g. country domains, and in our experience, the regexp matching of the host header is used primarily for this. Question: if we implemented an exact host predicate, what would be the best way to allow multiple hosts for the same route? How about:

```
HostExact("www.example.org", "www.example.net", "www.example.de", "www.example.fr")
```

?

@mo-gr, @lmineiro  do you think the above example would be a too strong precursor to "OR" predicates?

**Comment by lmineiro** [comment]
The difference I anticipate with the proposal versus having the "OR" as part of the predicates matching is that we'd have to support expression grouping for more complex "predicate trains", like:

`HostExact("example.com") && Path("/foo") OR Path("/bar")`
vs
`HostExact("example.com") && (Path("/foo") OR Path("/bar"))`

This would become mandatory if the "OR" is introduced.

The variadic host matching for this new Predicate seems reasonable

**Comment by mo-gr** [comment]
Maybe we should consider adding a custom predicate for our main use case? This would heavily reduce the amount of repetitive boilerplate and potential for stupid typos.
I'm thinking something like:

```
Zalando() -> ... -> "tailor"; // this matches all valid (www|m).zalando.TLD
ZalandoDesktop() -> ... -> "tailor"; // this matches all valid www.zalando.TLD
ZalandoMobile() -> ... -> "tailor"; // this matches all valid m.zalando.TLD
Zalando('de', 'ch', 'ch-fr') -> ... -> "tailor"; // this matches only (www|m).zalando.de and (www|m|fr|m-fr).zalando.ch
```

Internally, those could be implemented more efficient than a regular expression and it would cover all our use cases.

But apart from that, having a `HostExact` is probably a good idea. Having an `OR` is something, I would strongly object against.

**Comment by aryszka** [comment]
the Zalando() predicates are definitely a z-skipper matter, but it's also useful insight for others and a good use case for the custom predicates, so we can give documentation hints.

**Comment by grassator** [comment]
I think we should normalize the names of standard predicates as I think `Host` is the only one that takes Regexp. To maintain backwards compatibility I suggest adopting the following scheme:

- `*Exact`
- `*Regexp`

So we would have:

- `HostExact` **new**
- `HostRegexp` alias for `Host`
- `Host` deprecated
- `PathExact` alias for `Path`
- `PathRegexp` as it was
- `Path` deprecated
- *... the same for the rest of built-in filters*

**Comment by lmineiro** [comment]
This last proposal should also allow us to close #33

**Comment by aryszka** [comment]
@grassator i started working on this ticket, and your proposal exactly how I started. nice to see this :)

However, due to the tests and all it was becoming a surporisingly big CR, so i'll handle this naming issue separately.
