### ISSUE TITLE
Feature request: external k8s ingress overrides

### ISSUE THREAD

**Issue by mo-gr** [zalando/skipper#390]
Our k8s currently supports blue/green (and canary) deployments utilizing skipper ingress routes. It would be cool to have an option to override the traffic weights from the outside on a per request basis via request headers. I'll give a concrete example of what I want to achieve based on canary deployments, but I see no reason, this couldn't also work for blue/green deployments.

## Usecase
Let's assume, I have a risky deployment of my app. Something that can't be done behind a feature switch like a major dependency/language/framework update.
Therefore I deploy a single pod of my new version as a canary.

Now, ideally, I want 0 real traffic to that new pod, since I don't know how it will behave in the live environment.

Now I have something like this:

```

  Browser ---> Skipper ---> Tailor ---> Fragment ---> MyApp
  
                                                      MyApp-Canary
                                                      
```

And I would like to trigger some requests against the canary through the whole system. Currently, my only option is to teach the fragment about the canary (via a feature switch?), such that I can selectively hit it.

However, if I could override the ingress of MyApp from the outside, via a header(that is forwarded by all parties involved), I could create requests, that will ultimately hit my canary.

```

  Browser ---> Skipper ---> Tailor ---> Fragment ---> . MyApp
                                                      .
                                                      . . . > MyApp-Canary
                                                      
```

This would enable me test my Canary in the context of the live system until I have enough confidence to put some real customer traffic against it.

One could even think this further and create single-pod-canaries for every pull request to MyApp and run automated smoke-tests against the integrated system as a whole.

## Suggestion

I suggest the following header:
```
X-Ingress-Stage: MyApp=canary
```
and/or (since many applications in the fashion store forward all `x-zalando-*` headers by default):
```
X-Zalando-Ingress-Stage: MyApp=canary
```

The header should support multiple applications, comma seperated like so:
```
X-Zalando-Ingress-Stage: MyApp=canary,Fragment=beta,Skipper=go3.0.0
```

### The behavior should be as follows:

- if a kubernetes ingress skipper sees that header, it takes the value and splits it on `,` obtaining a list of `=` separated keys and values
- if it manages a service named like one of the keys, it looks for a `stage` of this keys value. 
- - If such a stage is deployed, the traffic will be routed to that stage.
- - if such a stage is not deployed, this key-value pair is ignored and the request is handled as usual

It follows, that it is valid to have an applications multiple times in the header, with the first matching stage winning.

Also, since invalid stages are ignored, the worst case would be, that we hit the usual production endpoint.

**Comment by hjacobs** [comment]
@mo-gr that's what linkerd provides with "dynamic request routing" (change route through multiple microservices via HTTP header): https://linkerd.io/features/routing/

**Comment by szuecs** [comment]
Linkerd provides dtab (~ eskip) overwrite via http header, which could be done in skipper with overriding eskip routes per header, but this should not be leaked to callers in the return path https://buoyant.io/2017/01/06/a-service-mesh-for-kubernetes-part-vi-staging-microservices-without-the-tears/

**Comment by aryszka** [comment]
@mo-gr do you think there is a big difference between setting in the client:

```
X-Ingress-Stage: MyApp=canary,Fragment=beta,Skipper=go3.0.0
```

and

```
X-Ingress-Stage: MyApp=canary
X-Ingress-Stage: Fragment=beta
X-Ingress-Stage: Skipper=go3.0.0
```

?

asking because the latter could be implemented with the given Header predicate, and it also could be generalized for other stuff, e.g. taking different custom conditions form ingress annotations.

**Comment by mo-gr** [comment]
I would not mind. I'm not strongly opinionated about the actual form of the headers. I would also be fine with something like: `X-Ingress-Stage-MyApp: canary`

With your multiple-header suggestion, I would be a little bit afraid, that some clients in-between don't handle them correctly and drop/conflate multiple occurrences of the same header

**Comment by mikkeloscar** [comment]
@mo-gr as I understand you would like to route traffic based on a pod label (e.g. `stage: canary`). However, this is not quite possible as skipper operates on Ingress resources which only has Kubernetes *Services* defined as backends. I.e. it looks like this:

```
                                 /--> pod-1-abc
            /--> backend-svc-1 _/
           /                    \
          /                      \--> pod-1-xyz
         /
skipper -
         \
          \
           \                     /--> pod-2-abc
            \--> backend-svc-2 _/
                                \
                                 \--> pod-2-xyz
```

Given this, it would probably make more sense to specify a header:

```
X-Ingress-Backend: my-svc-canary
```

With an ingress resource defined like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
  annotations:
    zalando.org/backend-weights: |
      {"my-svc": 100, "my-svc-canary": 0}
spec:
  rules:
  - host: live.shop.com
    http:
      paths:
      - backend:
          serviceName: my-svc
          servicePort: main-port
      - backend:
          serviceName: my-svc-canary
          servicePort: main-port
```

Which means 100% of traffic goes to the `my-svc` backend, unless the `X-Ingress-Backend: my-svc-canary` header is set.

This is probably not quite as flexible as you would like, but given how Ingress works, I think this is a more feasible solution.

**Comment by szuecs** [comment]
@mo-gr in ingress you can now use all filters and predicates, which you can use to enable an ingress with only a special cookie. If you have 2 ingress defined, one with cookie predicate and one without, you would be able to have a cookie to change the path within a hierarchy call you described.

Ingress with cookie to route to myapp-alpha version:

    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      annotations:
        zalando.org/skipper-predicate: Cookie("version", /^alpha$/)
      name: myapp-alpha
    spec:
      rules:
      - host: myapp.example.org
        http:
          paths:
          - backend:
              serviceName: myapp-alpha-svc
              servicePort: 80


ingress to route to current myapp:

    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: myapp
    spec:
      rules:
      - host: myapp.example.org
        http:
          paths:
          - backend:
              serviceName: myapp-svc
              servicePort: 80

On the other hand you have blue-green traffic switching as mikkel described.

I hope we can close this issue, if this is good enough, of not please describe what is missing. :)

**Comment by szuecs** [comment]
I think that's already possible if you use RouteGroup https://opensource.zalando.com/skipper/kubernetes/routegroup-crd/
