### ISSUE TITLE
Kubernetes ingress healthcheck only on bootstrap and teardown

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#395]
Background: We use skipper as ingress implementation, so it's a central component for us.

For Kubernetes ingress the healthcheckRoute will be switched to unhealthy if the Kubernetes apiserver is not reachable. This means all production services are going down, if the control plane is not reachable.

For production this we consider as a bug.

It should only be unhealthy in the case of startup as long as we have no routes populated and on teardown to stop new incoming connections.

**Comment by szuecs** [comment]
#396

**Comment by aryszka** [comment]
fixed in #396

**Comment by hjacobs** [comment]
Thanks @szuecs!
