### ISSUE TITLE
more humble branding

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#400]
Proposing here to be a bit less agressive with the branding headers: Server and X-Powered-By.

For one, I think we could remove the X-Powered-By header, because this is not what really Skipper does in my understanding. (https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#cite_ref-52) Other opinions?

For the Server header, I see the following cases:

	- original response doesn't have a server header => set Server: Skipper
	- original response has server header            => keep original
	- filter sets server header                      => use the one from the filter
	- filter deletes server header                   => don't send a Server header with the response

This way could support all different needs on the happy path.

What should happen when shunting? I also wonder what should happen when experiencing one of the proxy error cases: connection error, streaming error, loop detected, configuration error.

**Comment by hjacobs** [comment]
Yes, please get rid of the header "spam" :smile:  --- the current branding is not really helping anybody (just makes it look bad because of the double header).

**Comment by aryszka** [comment]
Dude... more respect and reverence, please!!!! This is our first feature and the one and only without a single bug ever!
