### ISSUE TITLE
Rate limiting support in ingress/deployment

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#414]
As **developer**, I want to specify rate limiting in my Ingress spec and do not implement it in my application code. I want to define how much requests per minute my application can handle and what the max peak of connections should be. This is part of #411 as Skipper in Kubernetes.

For example I have a /login path and I want to make sure that this can not be easily enumerated by a distributed attacker, so I want to be able to configure:

* limit requests per second per client: IP or [X-Forwarded-For)](https://en.wikipedia.org/wiki/X-Forwarded-For)
* limit requests per Authorization header (better than token, because it's also limit per userid in case of basic auth)
* ~set burst limits, such that we can have 10 req/s, but a peak of 100 is also ok~

## implementation
- [x] Skipper should have a filter implementation #424

## config
ingress annotation:
* zalando.org/ratelimit: '{"req": 100, ~"burst": 2,~ "req_per_auth_header": 20}', this would allow 100 requests per second~, a burst factor of 2 meaning 200 requests per second,~ and 20 requests for the same Bearer token

### Example how this was used with a nginx reverse proxy
```
limit_req_zone $binary_remote_addr zone=by_ip:10m rate=100r/s;
    limit_req_zone $http_authorization zone=by_oauth_token:100m rate=1r/m;
    limit_req_zone $request_uri zone=by_uri:10m rate=100r/m;
    limit_req_status 429;

    server {
        listen 80;

        location / {
            proxy_pass_header       Host;
            proxy_pass_header       X-Forwarded-For;
            proxy_pass_header       X-Forwarded-Proto;
            proxy_pass_header       X-Forwarded-Port;
            limit_req zone=by_ip burst=100;
            proxy_pass http://localhost:8080;
        }
```

## Questions:
- [ ] Does it makes sense to use an annotation on ingress or is it better to add an annotation in the POD? POD spec has the advantage, that you are able to vertical scale or deploy an optimized version and change the numbers for the new containers, without changing the old deployments.
- [X] Does it makes sense to have burst as a factor? I consider this as not necessary

**Comment by aryszka** [comment]
could be implemented in a generic way and used from ingress, too
