### ISSUE TITLE
Opentracing-API

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#421]
Placeholder to reference, work in progress

**Comment by szuecs** [comment]
There was some work in https://docs.google.com/document/d/1FbdxmjviqhN_wBdo4fgTnvBcbspjxHy59nSL6yJs5BI/

**Comment by szuecs** [comment]
It was published at https://github.com/skipper-plugins/opentracing, but it's rough and needs some cleanu and documentation how to build it. Go plugins was not to simple to compile, because it needs to be in the same GOPATH.

**Comment by mvalkon** [comment]
This is very interesting. This is one of the features that I think would be very useful for many teams. I would be interested in trying out Jaeger with Skipper.

**Comment by szuecs** [comment]
@mvalkon Would you like to implement Jaeger in https://github.com/skipper-plugins/opentracing/tree/master/tracers or should we do this?

**Comment by mvalkon** [comment]
@szuecs I can take a look at implementing the plugin, but current priority for me is the upcoming BF so may be that the PR comes after that.

**Comment by szuecs** [comment]
I close this issue, because we already have opentracingAPI, not Jaeger, but this is tracked at #411 epic issue and https://github.com/skipper-plugins/opentracing/issues/1.
