### ISSUE TITLE
Provide access to backend metrics from filters

### ISSUE THREAD

**Issue by grahamar** [zalando/skipper#443]
Filters should have access to more information about the call to the backend, at response time. At least the following metrics should be available.

- `send` - Time spent in Skipper before sending the request to the backend
- `wait` - Time spent waiting for a response from the backend
- `receive` - Time spent receiving the response from the backend (including any posible parsing)

For example, I'd like to be able to write a filter that sends all request/response pairs to a third party service such as [Galileo](https://getgalileo.io/) and to fulfill their API I need access to the send, wait, receive timings of the backend call.

**Comment by szuecs** [comment]
What is the problem with the current metrics filters?
Can't you just use this?
I would also question, why it should be in the core infrastructure in the hot path, but only one use case "send metrics to Galileo" is the requirement for that.

**Comment by grahamar** [comment]
Galileo is just one example of a third party API analytic service. We want to be able to extract analytics on all calls going through the proxy, IP addresses, metrics, size of calls, etc.

Forgive me if this information is already available to filters, but I couldn't find it. What current metric filters are you referring to?

**Comment by szuecs** [comment]
I refer to this: https://godoc.org/github.com/zalando/skipper/metrics

We have a lot of metrics, for example "servehost" or if you want to measure runtime of filters is also available.

**Comment by grahamar** [comment]
Ok, yeah that's not what I was getting at. I get that Skipper is tracking lots of metrics already, and if I want I can track custom metrics in a filter.

What is not possible in Skipper is the capability to track and report on full API request and responses including headers, parameters.

For example reporting on all unique client IPs or OAuth client_ids in a given time frame. Or call latency or error count for a given user of an API (across IP addresses).

In any case we're going to go with an API gateway/management solution that can already provide this. Thanks anyway.

**Comment by szuecs** [comment]
@grahamar I think you should write down the features/use cases you want to build before. In your initial PR and issue you did not add the features you want to have, so we also can not discuss how to achieve this. It is disappointing to me as a colleague, that you now just close this and say we go for something else, just because I ask and propose solutions. I think this shows only that I am interested and not that I don't care.
It's ok for me if you want to choose another product that fits
