### ISSUE TITLE
metrics filtering with the request path

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#457]
calling "/metrics/all.backend" returns only the metrics called "all.backend" but "/metrics/all.backen" returns both "all.backend" and "all.backend.5xx"

**Comment by lmineiro** [comment]
I see that [the feature](https://github.com/zalando/skipper/blob/2f06af6c3231d29671c6718a71fea380a537a69a/metrics/handler.go#L22) is not appreciated :)

**Comment by aryszka** [comment]
ok, clear now! :)

i even missed the docs when shooting with the issue: https://godoc.org/github.com/zalando/skipper/metrics

thx
