### ISSUE TITLE
Cannot reload new routing rules from ETCD if we delete the route root 

### ISSUE THREAD

**Issue by zhen-w** [zalando/skipper#474]
Reproduce steps:
1. Launch skipper with ETCD prefix /skipper/test
2. Setup the test routing rule by: `curl -XPUT http://localhost:2379/v2/keys/skipper/test/routes/tobedelete -d value='Path("/google") -> "https://www.google.com"'`
3. You would see 'route settings received' in your console
4. Delete the route root by: `curl -XDELETE http://localhost:2379/v2/keys/skipper/test/routes?recursive=true`
5. The route would not be removed.
6. Then we add a new routing rule under the same root: `curl -XPUT http://localhost:2379/v2/keys/skipper/test/routes/tobedelete -d value='Path("/baidu") -> "https://www.baidu.com"'`
7. Skipper will not reload any route rules

The attachement is my fix for the issue. 

[code_diff.txt](https://github.com/zalando/skipper/files/1420366/code_diff.txt)

**Comment by lmineiro** [comment]
Seems like a good catch. Care to send that as a PR?

**Comment by zhen-w** [comment]
Sure. Thanks

**Comment by szuecs** [comment]
thanks @zhen-w
