### ISSUE TITLE
ordering of ingress items with the same host can cause dropped filters and predicates

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#482]
when there are multiple ingresses with the same host, only one of them, the first one in the order of being returned from the API, will have its custom filters and predicates applied if any

**Comment by aryszka** [comment]
a raw test in this branch demonstrates the failure: [ordering-bug](https://github.com/zalando/skipper/blob/ordering-bug/dataclients/kubernetes/orderingbug_test.go)

**Comment by szuecs** [comment]
Thanks @aryszka! 
I changed your PR as you suggested. I think it makes totally sense to simplify it.
