### ISSUE TITLE
ETCD data client doesn't support basic authentication

### ISSUE THREAD

**Issue by zhen-w** [zalando/skipper#487]
https://coreos.com/etcd/docs/latest/v2/auth_api.html#v2-auth

**Comment by zhen-w** [comment]
Are you gonna put it on your roadmap? If yes, do you mind me to submit a preliminary PR for it? Or you guys prefer implementing it by yourselves.

**Comment by mikkeloscar** [comment]
@zhen-w PR's are very welcome! I'm not sure this is a feature we need ourselves in the near future, but if it would be useful for you I see no reason not to support it :)

**Comment by szuecs** [comment]
@zhen-w I just assigned it to you, such that everyone can see who will do the development. Thanks so much for your work on that. :)

**Comment by zhen-w** [comment]
Ok, I will work on it.

**Comment by MALPI** [comment]
@zhen-w Any news? Otherwise I'll take it.
