### ISSUE TITLE
Loadbalancer support

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#499]
Why:

- This would enables `ingress -> endpoints` circumventing service (`ingress -> svc -> endpoints`). 
- This is also required to enable service mesh
- optimize backend dispatch
- find faster miss behaving backends

**Comment by szuecs** [comment]
Development started in branch **kube-endpoints**

Current implementation has a bug getting 404s if I loadtest from my local machine to a test cluster in about 0.1-0.2% of the requests.

feature state:

- ingress -> endpoints if endpoints are available, so we have the optimized dispatch, but do not disrupt service without endpoints
- find miss behaving endpoints is not started yet

**Comment by szuecs** [comment]
I started to implement the loadbalancer feature "find miss behaving endpoints"

This can be achieved in 2 ways:
1. active: health checking
1. passive: understand failing requests, for example timeouts should result in marking unhealthy/dead endpoints

### active 
Active health checking requires 2 more information as before:
- health check endpoint
- response treated as "OK" 

We could achieve both if we would have an axiom, that /healthz has to return http status code 200 to be healthy. I think it would be nice, but not practical, because each language or framework community have it's own idea of what makes sense.

**health check endpoint**: The dataclient should provide the data. In case of kubernetes the data is defined in the container spec of the POD definition. This would require to add another API call to the kubernetes API to get the data from the POD specs got from the corresponding service selector. In case of kubernetes I would suggest to use the readinessProbe if httpGet is defined. 

**response treated as "OK"**: In my opinion we should use http status code 200 as **ok**, timeout as **dead** and rest **unhealthy**. This will result in:
- ok: serve traffic
- dead: delete route and safe as dead for at least 30s 
- unhealthy: stop using route (delete from list from LoadUpdate()) until health check is successful 

### passive
Passive health checking requires data of healthiness comes from a part of the code that call the backend. The proxy **do()** function can pass data to the healthchecker part of our loadbalancer. In my opinion in this case all http status codes are healthy, besides if the do() call results in a timeout, which would mark the route as unhealthy and we could retry the call to another endpoint of the same group. Maybe we can also use 504 and some other 5xy codes to mark the route as unhealthy. 

- dead: timeout
- unhealthy: 504 and maybe other 5xy status codes
- ok: all other

Any thoughts @aryszka @lmineiro ? Should all 5xy status codes be treated as unhealthy?

**Comment by lmineiro** [comment]
Sounds good to standardize on a default health check endpoint like the one proposed albeit on a different default port like 7979. It would make sense to extend the DataClient API to allow route authors to customize the health check endpoint.
s/dead/zombie to adopt common terminology. The described behavior seems like a circuit breaker to me. Don't we already have something in place that could be leveraged?

I don't think deleting the route make sense here. The target may be going through some temporary overload or hiccup, enough to be considered unhealthy but actually recover. How do we restore the route? Are these targets individual backend instances or, potentially, service/load balanced targets?

I am wondering if the ideas from https://landing.google.com/sre/book/chapters/load-balancing-datacenter.html#identifying-bad-tasks-flow-control-and-lame-ducks-bEs0uy couldn't be used if we went the same direction - client side load balancing, essentially.

**Comment by szuecs** [comment]
@lmineiro I appreciate all the input, but where do you have that common terminology zombie vs. dead, because zombie?

I read the mentioned section, thanks for linking it.

I changed the dead state to connection refused case, where there is not TCP connection possible anymore. This case for example happens if a node in kubernetes dies for example with kernel panic, such that kubelet can not deregister the node (no pod eviction, until ETCD timeout will happen and controller-manager will take over to handle the issue). What do you think about the changed behaviour?

The direction for me is "make client side load balancing possible, but not mandatory".

**Comment by lmineiro** [comment]
I think we should decide on which topology Skipper should focus.

"if a node in kubernetes dies for example" fits in the client side load balancing, where skipper would need to have knowledge about all the worker nodes. Does any if this conflict with Kubernetes' service endpoints?

Right on the topic, a good write up from last December (https://blog.envoyproxy.io/introduction-to-modern-network-load-balancing-and-proxying-a57f6ff80236) where the different topologies are described. I'm inclined to agree that the sidecar proxy model is going to replace all other topologies for service-to-service communication. The edge proxy topology will always be required prior to traffic entering the service mesh.

This suggests that we should decide on which topology(ies) we'd like to prepare Skipper for. Some of the open questions in this issue have trivial answers if we focus just on one of them. That's the reason why I was asking about the client side load balancing, which fits perfectly in the Sidecar Proxy topology. I believe Skipper is a good fit for it, although it has shown to be very powerful as an Edge Proxy also.

**Comment by szuecs** [comment]
@lmineiro loadbalancer support will change from using service to endpoints, such that we can do understand healthiness of an endpoint. We do roundrobin with Predicates and compile 1 route per endpoint with the predicate.

I read the whole envoy and following them, but I have to disagree with a lot in the article (mostly the last part). I also read a lot about facebook and google loadbalancing and think that l7 edge will always be a use case, also ingress, but also in the future sidecar/client proxy. I am not convinced, that it makes in general sense to proxy l4 in the same proxy as l7 (see postgres) and I am also not convinced in istio or envoy APIs. I think we have a better alternative with our swim based gossip implementation of skipper-cluster awareness.
