### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by slok** [zalando/skipper#504]
Hi there!

At this moment Skipper has a bunch of good metrics, but they are in a custom format. The problem is that this format is not portable to other kind of monitoring stacks.

Could be nice to have this same metrics in Prometheus format, knowing that Prometheus is one of the "de facto" standards out there nowadays.

Is this feature something you see valuable to have it in Skipper?

Thank you!

**Comment by szuecs** [comment]
@slok for sure, we do not use Prometheus ourselves, but this could attract people using skipper.

Do you want to contribute it?

**Comment by slok** [comment]
Yes, I would like to try :)

**Comment by jbergstroem** [comment]
Interesting -- kind of assumed the statistics were prometheus-friendly (the docs didn't really mention any kind of standard). I'd love to see this as well.

**Comment by szuecs** [comment]
@slok thanks for your efforts :)
