### ISSUE TITLE
hardcoded healthz check Source predicate

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#531]
The hardcoded healthz check Source predicate is not possible to be overwritten by the user.
Possible workaround for users, use an inline route parameter to proxy the health check call:

    -inline-routes 'Path("/health") -> setPath("/kube-system/healthz") -> <loopback>'

**Comment by lmineiro** [comment]
The hardcoded values include ~all private networks.
I'd be curious to know why the health check endpoint would support public networks. That being said, I agree that it could be user-defined since the Source predicate already supports it anyway...

**Comment by mikkeloscar** [comment]
I'm wondering if we really need to define any source networks in skipper. It seems out of scope to define it in the application rather than restrict this on the security group/firewall level?

**Comment by szuecs** [comment]
@lmineiro I think we should just drop the Source predicate, because you can easily fake it

    % curl -kv -H"X-Forwarded-For: 192.168.0.4" -H"Host: localhost" https://some-ingress-endpoint/kube-system/healthz
    < HTTP/1.1 200 OK
    < Date: Thu, 04 Jan 2018 14:44:12 GMT
    < Content-Type: text/plain; charset=utf-8
    < Content-Length: 0
    < Connection: keep-alive
    < Server: Skipper

**Comment by lmineiro** [comment]
Can you try that behind the ELB/ALB?

**Comment by szuecs** [comment]
@lmineiro It will work, because we use X-Forwarded-For header as remote ip if it's in the header and the host header is chosen by the user, so no difference anyways

**Comment by lmineiro** [comment]
I'd still like to see how the ELB/ALB handles an existing `X-Forwarded-For` header. If it just appends itself the multivalue header or as the last comma-separated list of proxies.

The [source predicate takes the left most host as the client IP](https://github.com/zalando/skipper/blob/master/net/net.go#L29).

**Comment by szuecs** [comment]
Amazon documentation is undefined for ALB and is different from ELB:

    curl -kv -H"X-Forwarded-For: 192.168.0.4" -H"Host: localhost" https://some-endpoint/kube-system/healthz

15:58:31.794845 IP 172.31.2.194.3768 > 172.31.20.165.9999: Flags [P.], seq 1502:1748, ack 159, win 10209, options [nop,nop,TS val 2407620323 ecr 572090078], length 246
E..*-L@...............'..F.     w6.>..'........
..^.".f.GET /kube-system/healthz HTTP/1.1
X-Forwarded-For: 192.168.0.4, 185.85.220.142
X-Forwarded-Proto: https
X-Forwarded-Port: 443
Host: localhost
X-Amzn-Trace-Id: Root=1-5a4e4f27-3296565b163f1c0935eeb9f6
User-Agent: curl/7.49.0

**Comment by lmineiro** [comment]
Seems to have followed the same behavior as [Go's reverse proxy](https://github.com/golang/go/blob/e676dbbdaf20e00609ba4cddfd55619a1e530b21/src/net/http/httputil/reverseproxy.go#L187).

Thanks for confirming.

**Comment by szuecs** [comment]
Fun fact: AWS is somehow wrong and not wrong and everyone else does it exactly the way skipper is doing it right now.

https://en.wikipedia.org/wiki/X-Forwarded-For
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

https://tools.ietf.org/html/rfc7239#section-7: has only one example showing that wikipedia is somehow right, but the order can not be considered as a definition.
https://tools.ietf.org/html/rfc7239#section-8: security: "can not be relied on" 

I think we have to pass an option to change the lookup order, similar to the PR: https://github.com/zalando/skipper/pull/533

**Comment by szuecs** [comment]
Was merged
