### ISSUE TITLE
Allow to suppress http access log entries for distinct endpoints and/or sources

### ISSUE THREAD

**Issue by tkrop** [zalando/skipper#534]
The (http) access log entries in skipper contain any request. It is not possible to filter logging to hide certain requests, e.g. cluster internal request, or filter requests to certain endpoints, e.g. health endpoints. This can be helpful to reduce log volume to important information.

**Comment by lmineiro** [comment]
We could also consider optional sampling. In hight traffic situations a small percentage of the requests should be statistically enough for many use cases.

**Comment by szuecs** [comment]
With Predicates and https://opensource.zalando.com/skipper/reference/filters/#enableaccesslog or https://opensource.zalando.com/skipper/reference/filters/#disableaccesslog you can already do this.
For log sampling I will create another issue, but you could duplicate the routes and having on each duplicated one a Traffic(0.1) predicate and an enableAccessLog() filter to log 10% of traffic.
https://github.com/zalando/skipper/issues/1472
