### ISSUE TITLE
Allow to add distinct headers into http access log output as extension.

### ISSUE THREAD

**Issue by tkrop** [zalando/skipper#535]
In certain situations it may be interesting to have certain header information available in the http access log entries, e.g. call/trace identifiers, that help to match requests across system boundaries.

**Comment by lmineiro** [comment]
I think the filter to dump all the headers is good enough for general, one-off, debugging troubleshooting while the call/trace identifiers seems to me that is better solved with distributed tracing.

Skipper already supports via opentracing. See https://github.com/skipper-plugins/opentracing. PRs with more tracers that adopt the standard are welcome, like Jaeger and/or OpenZipkin.

**Comment by AlexanderYastrebov** [comment]
Closing in favor of #551
