### ISSUE TITLE
CORS filter

### ISSUE THREAD

**Issue by DeTeam** [zalando/skipper#559]
Just experienced a use-case when it would be nice to have a convenience `cors` filter which would take care of setting the right response headers.

**Comment by szuecs** [comment]
@DeTeam Could you describe how this should be ideally looks like from the user perspective?
Please also specify which headers we should write into the response.

I think it makes a lot of sense, but please provide more information, such that we can build it fast. Thanks!

**Comment by DeTeam** [comment]
In my particular use-case: `Access-Control-Allow-Origin: *` + any methods + any headers
But I guess it's only good for testing.

It could also in theory take care of setting up a separate "pre-flight route" which would response to OPTION and quickly return cors headers.

<sup>1</sup> https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS - nice reference

Thinking about it again, it might be enough to just use `setResponseHeader("Access-Control-Allow-Origin", "*")` which we can already do manually 🤔

**Comment by DeTeam** [comment]
Another thing which this filter could do: take some request headers (access-control-allow-*) and just return them (for methods and headers) %)

**Comment by ruiaraujo** [comment]
@DeTeam It should take options for allowed origins since the header only allows sending a single origin.

**Comment by szuecs** [comment]
@ruiaraujo I assigned you according to your twitter message, you might want to do additional work, so I let this issue open.

**Comment by vetinari** [comment]
@ruiaraujo @szuecs  is this done with #595?

**Comment by ruiaraujo** [comment]
I believe so but I will check when I try to use it. I will close it now myself and once I have it in production, if something is missing I will reopen.
