### ISSUE TITLE
Path rewrite for Ingress

### ISSUE THREAD

**Issue by andreasottosson** [zalando/skipper#560]
Trying to use the modPath filter to strip away a part of the path thats being sent to the backend but nothing seems to happen. Similar to Traefik's PathPrefixStrip.. Am i missing something or does this not work?

Example (Strip away /api/):

annotations:
  zalando.org/skipper-filter: modPath("^/api/", "/")

**Comment by szuecs** [comment]
Hi!

In general it should work like this in a skipper route:

     Path("/api/foo") -> modPath("^/api", "") -> "http://localhost:10000"

or

     Path("/api/foo") -> modPath("^/api/", "/") -> "http://localhost:10000"

You can check the routes within your container with, which often helps to understand what is wrong:

    wget -O/dev/stdout localhost:9911/routes | grep -C 2 modPath
    kube_default__demo__demo_f_test_zalan_do____demo: Host(/^demo[.]f-test[.]zalan[.]do$/)
     -> modPath("^/api/", "/")
     -> "http://10.3.194.80:80";

**Comment by andreasottosson** [comment]
Hi! Thanks @szuecs for you quick answer! I do see something similiar: (i have modified this response a bit for security reasons...) 

kube_dev__freight_flip__testdev_freight_domain_com____freight_flip_service_0: Host(/^testdev-freight[.]domain[.]com$/) && LBMember("kube_dev__freight_flip__testdev_freight_domain_com____freight_flip_service", 0) && Path("/flip/:wildcard")
  -> modPath("^/flip", "")
  -> "http://100.107.148.70:80";

And what i want now is when i go to www.domain.com/flip/metrics skipper should send that request to my backend as www.domain.com/metrics but i just get "Not Found", and that is route not found right? We will have multiple services on the same ALB so this one should only respond on /flip.

This is the YAML for the Ingress,

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: freight-flip
  namespace: dev
  annotations:
    zalando.org/skipper-predicate: Path("/flip/:wildcard")
    zalando.org/skipper-filter: modPath("^/flip", "")
spec:
  rules:
  - host: 'www.domain.com'
    http:
      paths:
      - backend:
          serviceName: freight-flip-service
          servicePort: 80

I guess my basic question is how to config Skipper routes in the YAML files.

**Comment by szuecs** [comment]
@andreasottosson, 

The `Path("/flip/:wildcard")` predicate will match on /flip/bar, but not /flip/bar/foo. Are you sure that you have no longer path than shown in your URL that you call?
If you have a longer path you can use `Path("/flip/*")` to match all subtree patterns.

### Additional questions if this was not your problem
Which skipper version and flags are you using?

From your ingress object it looks fine to me.

The 404 can come from skipper route not found (default is reply with 404) or your backend, which you might want to check to be sure the backend is fine. 
Do you tried one or multiple requests to http://www.domain.com/flip/metrics ? Do all of them reply with 404?

Can you send us the output of the following command (grepping all the lb rules)?

    wget -O/dev/stdout localhost:9911/routes 2>/dev/null | grep kube_dev__freight_flip__testdev_freight_domain_com____freight_flip_service


If you have the time can you check that your flags are similar to [1], and if so change the skipper version to the one linked [1]. The release was heavily tested, but not yet running in production. You might want to run our production version [1].

[1] https://github.com/zalando-incubator/kubernetes-on-aws/blob/beta/cluster/manifests/skipper/daemonset.yaml#L43

**Comment by aryszka** [comment]
@andreasottosson , I believe the root of the problem here is caused by this bug:

https://github.com/zalando/skipper/issues/544

What this means that the Path("/api/:wildcard") predicate is not applied at the moment. The fix is on its way.

Until that, the best workaround should be to use the ingress style path specification instead of the Path predicate annotation, while leaving only the modPath filter as an annotation. (Note that the ingress sepcification expects regexp for the path, with starting by /, and doesn't support wildcards.) Otherwise your route specification looks correct to me, and it should work once the bug in #544 gets fixed.

Please let us know if this helps. And also thanks for trying Skipper :)

**Comment by andreasottosson** [comment]
You guys are awesome with your quick responses! Much appreciated! ;) It's my 10th day of using Kubernetes so this is all new to me.. I managed to solve this now by using version v0.9.152. Indeed Path("/api/:wildcard") predicate is not applied. I just changed the version of skipper and it now works as expected. Thanks again @szuecs & @aryszka !
