### ISSUE TITLE
pass hash based history to skipper?

### ISSUE THREAD

**Issue by alex-roger-1942** [zalando/skipper#577]
Hi,

Sorry if this is not the right place to ask but I'm curious. Is it possible without writing additional plugins to pass hash based paths to skipper? I'm currently migrating an app to microservice architecture and would like to put skipper in front as I migrate.

So resolving something like 
testplatform.domain.com/auth#/signin
testplatform.domain.com/auth#/signup

and eskip routes such as -

login:
        Path("/login")
        -> setPath("/auth")
        -> setQuery("#/signin")
        -> "testplatform.domain.com";

login:
        Path("/signup")
        -> setPath("/auth")
        -> setQuery("#/signup")
        -> "testplatform.domain.com";

Probably setQuery is not the correct function here but this is more pseudocode to demonstrate what I'm trying to achieve.

**Comment by mikkeloscar** [comment]
This is not possible with skipper (or any proxy) because the hash ([Fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier)) is a client side thing, so your browser will not send it in the request.

**Comment by alex-roger-1942** [comment]
Interesting, so when you guys push state to the url bar at zalando do you guys use html5 push state, how do you rewrite so that things work correctly with skipper and tailor?

**Comment by alex-roger-1942** [comment]
I suppose there is nothing stopping my caller from specifying this for my current need.
so I can go /signup#/signup for now.

**Comment by szuecs** [comment]
@alex-roger-1942 I can't answer your html5 use question, but if you need to set/modify/delete a fragment it should be fairly easy to implement. If you do not mind creating a PR, you can have a look at the implementation of the *Query() filters in https://github.com/zalando/skipper/blob/master/filters/builtin/query.go.

**Comment by alex-roger-1942** [comment]
Thanks!
