### ISSUE TITLE
refactor: kubernetes tests

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#583]
the tests and the harness in the kubernetes package reflect an early, rather premature state of the kubernetes integration, and they cause some pain when testing and reviewing changes. We need to clean up and refactor the tests. Ideally without changing the prod code.

- Improve the test kubernetes API mock to support independent tests cases
- create a better set of Kubernetes Spec initialization functions for the common cases (antipattern: testIngress())

**Comment by szuecs** [comment]
I think this was done @aryszka
