### ISSUE TITLE
Fix unstable tests: httpsredirect_test.go

### ISSUE THREAD

**Issue by mikkeloscar** [zalando/skipper#585]
The tests in `dataclients/kubernetes/httpsredirect_test.go` are currently failing quite often, making PRs with unrelated changes fail.

I believe the failure is caused by a race in setting up the router and running tests against it before it has got the initial routes from the dataclient.

Some ideas for fixing this:
1. Drop the whole integration test and just test that we create the expected redirect route.
2. Make it possible to load routes from the dataclient in a synchronized way for testing.
3. Add a sleep after the router initialization (I don't like this).

/cc @aryszka @szuecs

**Comment by aryszka** [comment]
@mikkeloscar can you confirm that this changeset was already applied when you ran this test? https://github.com/zalando/skipper/commit/2773183b47f7fcca0d25039b3b8bf09fff4bd829#diff-9ce10fec44f49e925acea5a07258d3b7 . Because it's not failing for me anymore.

1. dropping the integration: the reason i am not a big fan of it is that we had recently a couple of bugs that would have been immediately spotted if having at least one layer of integration

2. currently i often use this monitored logger for synchronizing tests with the tested behavior. Seemed like a good idea before, but now I think it is rather a hack. I would support adding some synchronization hooks, primarily in the routing.Routing object.

3. no sleeps. We've been there, did once a major cleanup session.

**Comment by szuecs** [comment]
Thanks for sharing ideas how to fix the tests.
There was once a very good talk from Mitchel Hashimoto how to test in Go.

For timing dependent tests he presented a solution which we could try to use:

- do not use fake time!
- add multiplier to increase timeouts as CLI parameter and default it to 1

```
var int timeMultiplier // set from CLI with default = 1
func TestThing(t *testing.T) {
  // ..

  timeout := 3 * time.Minute * timeMultiplier

  select {
    case <-thingHappened:
    case <-time.After(timeout):
      t.Fatal("timeout")
  }
}
```

**Comment by mikkeloscar** [comment]
> @mikkeloscar can you confirm that this changeset was already applied when you ran this test? 2773183#diff-9ce10fec44f49e925acea5a07258d3b7 . Because it's not failing for me anymore.

Yes, unfortunately I still see it fail when I run tests on master now. I also saw it on both travis and CDP when working on #581 where I also rebased on master after we merged your changes.

I have tried on both my old laptop and my desktop :) and it happens roughly every 1/10 runs.

> For timing dependent tests he presented a solution which we could try to use:

I think this is still a form of sleep, which we should try to avoid IMO.

I would go with some sort of synchronization hooks like @aryszka suggest, so we still have the benefit from the integration tests.

**Comment by aryszka** [comment]
ok, thanks for confirming, i look into it. There's a race condition. Thanks for finding it.

I also don't like Mitchel's approach in this (rare) case. Apart of the nicer coding solution, it's the same as we did before and leads to the before mentioned problems.

I see two alternative solutions for this syncing:

1. use buffered channels on the objects, like the routing.Routing, that act as synchronization points
2. use a shared even bus, also buffered

The advantage of 1 is that it's relatively easy to implement for specific cases. Also it is similar to what the stdlib does here and there. The disadvantage is that it doesn't generalizes in a nice way.

The advantage of 2 is that it may provide a nice common interface for the tests, if done well. The disadvantage is that it's an additional tool to be aware, and also it has to be implemented.

I prefer 2, and I see a chance that something like this can be extracted from the current logging/loggingtest package.

Anyway, first i'll look into the failing test...

**Comment by aryszka** [comment]
it's not a concurrency race but a randomness race :smile_cat: 

see #586 

So, we can fix this test now just to fix the build, but there is this design question of what to do with the competing default backends.

**Comment by aryszka** [comment]
The suggestion to improve concurrent testing are still good and we should address them as improvements.
