### ISSUE TITLE
Multiple Skipper Deployments

### ISSUE THREAD

**Issue by daviddyball** [zalando/skipper#613]
Hi All,

Is there a way to use a `labelSelector` or similar to have `Ingress` objects handled by certain deployments of Skipper? When I was using Traefik I was able to use a `labelSelector` to target only `Ingress` objects with certain metadata, which allowed me to have 3 different deployments of Traefik on the same cluster.

Is this possible with Skipper? I can't see anything in the documentation regarding selectors for targeting specific resources.

Is there another way I should be thinking about doing this in the Skipper world?

Thanks!

**Comment by szuecs** [comment]
Hi @daviddyball,

I might not understand 100% your question, so I will ask some questions first and sum up with a solution from what I understood.

Why you have 3 different deployments of the same ingress controller?
Do you run some kind of loadbalancer in front of skipper ingress?

A solution can also be to let 3 different skipper deployments have all routes and pick the skipper you want to call with a different labelSelector group via DNS name. So you might have something like 3 service type loadbalancers selecting the 3 different skipper deployments and choose by DNS name the target. If this is feasable is dependent on your use case, so I would like to understand it better.

Best, sandor

**Comment by daviddyball** [comment]
Forgive me if my thinking is incorrect, but I want the following:

1. AWS Internal ELB -> `skipper-internal` -> All `Service`s labelled with `ingress-type=internal`
2. AWS External ELB -> `skipper-api` -> All `Service`s labelled with `ingress-type=api`
3 AWS External ELB -> `skipper-admin` -> All `Service`s labelled with `ingress-type=admin`

Am I thinking about this the right way? If I was deploying Traefik I would have 3 `skipper-ingress-controller`s running with different `labelSelector=` values and they would control what `Service` objects end up attached to which ELB.

**Comment by szuecs** [comment]
Thanks for elaborating on this.

I think right now we have no similar solution with splitting these as you wrote. 

You can use another way as I think should be feasible, let me know if it's not.
In the end you want to decide per ingress who is allowed to do access based on IP space.
The following links show you how to do this. You can use one ALB with SNI certs in front of skipper and use the predicate `SourceFromLast()` in the AWS case to do "IP" (X-Forwarded-For header base) whitelisting:
https://godoc.org/github.com/zalando/skipper/predicates/source and https://zalando.github.io/skipper/kubernetes/ingress-usage/#ip-whitelisting

**Comment by daviddyball** [comment]
Apologies for the late response @szuecs , just returning from holiday today.

I think the ability to roll out multiple ingress controllers and use service-label selectors is one of the strongest features of Traefik. Doing it via IP-space filtering, while possible, feels like extra overhead to me and isn't really feasible for the project I'm currently working on, so I'd love to see selector support added to Skipper. Unfortunately my Go skills are non-existent, so I can't contribute to any implementation (yet) but if there is extra manpower and others like the idea, perhaps it could work it's way into the codebase.

Thanks for your help. I really appreciate it 😄

**Comment by szuecs** [comment]
@daviddyball I think your request makes a lot of sense, so I would consider implementing it. I think we just need a CLI option `--kubernetes-ingress-class` and use this in the `ingress.class` annotation used as a selector if we "own" this ingress or not. Default could be get all, if this flag is not provided.
Does this makes sense to you?

**Comment by daviddyball** [comment]
Yep, that's exactly how Traefik handles it 👍

**Comment by szuecs** [comment]
I will close this issue because everything should be possible already and it's now documented at:
https://zalando.github.io/skipper/kubernetes/ingress-controller/#multiple-skipper-deployments
