### ISSUE TITLE
kubernetes uneven loadbalanced members

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#614]
I assume a proper fix would be to implement https://github.com/zalando/skipper/issues/556.
I do not fully understand the problem, yet but we see in 3 ingress uneven balanced distribution of backend calls.

We tried to:

- [X] restart skipper instances which did not help to spread again
- [X] checked with tcpdump and saw that backend calls with X-lb-member was passed to backends
 

As a workaround you can use an older version, that does not have this issue: https://github.com/zalando/skipper/releases/tag/v0.9.152.

**Comment by aryszka** [comment]
related #608
