### ISSUE TITLE
introduce versioning

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#62]

**Comment by Raffo** [comment]
How? Can I contribute providing Godeps? Did you evaluate that?

**Comment by aryszka** [comment]
we considered that, and the builtin solution that appeared with go 1.5. We didn't like either of them too much. But we will need some solution. Let's do a chat about it tomorrow. And, we're very happy for your contriubtion, of course :)

**Comment by aryszka** [comment]
another possible approach, also Luis's recommendation, is: http://labix.org/gopkg.in

**Comment by Raffo** [comment]
Let's chat about it :-) 
I'll have a look at gopkg.in, but for the moment I'm quite happy with Godeps... in the end is used by Google itself like in https://github.com/kubernetes/kubernetes

**Comment by Raffo** [comment]
https://github.com/zalando/skipper/pull/73

**Comment by Raffo** [comment]
Closed by #73
