### ISSUE TITLE
Requests failing on VPN

### ISSUE THREAD

**Issue by stevoPerisic** [zalando/skipper#625]
Skipper requests are failing with "status code 502: proxy error with code -1" when used on VPN. How can I make it use the system Proxy settings?

**Comment by szuecs** [comment]
@stevoPerisic I might not follow the problem. 
Do you want to use skipper as forward proxy to proxy all http calls through skipper?
This use case is not possible right now, because skipper is a reverse proxy.

**Comment by stevoPerisic** [comment]
@szuecs, while I am on a VPN connection the https calls that are routed through skipper are failing.

**Comment by stevoPerisic** [comment]
1. Start a VPN like GhostVPN on your local machine
2. Start Skipper with a route to an https URL
3. Try to navigate this route and see "status code 502: proxy error with code -1" 

That's all I have :)

**Comment by szuecs** [comment]
Your setup is not clear from your description.
Is your VPN terminating into your cluster?
Where do you terminate TLS?
Which URL are you calling? 
Which skipper version are you using?
Can you show us some skipper logs around this error?

**Comment by szuecs** [comment]
Seems like no issue
