### ISSUE TITLE
Extract and log "sub" claim from JWT token from Authorization header

### ISSUE THREAD

**Issue by hjacobs** [zalando/skipper#631]
To be discussed: In order to have authorization information in the Skipper access log, we could consider extracting the `sub` claim from the JWT access token passed in `Authorization` header (OAuth Bearer token).

**Comment by szuecs** [comment]
I guess #630 is a precondition as far as I understand or is tokeninfo #367 good enough?

**Comment by hjacobs** [comment]
@szuecs I would actually not call any Token Info endpoint, I would simply parse the JWT JSON and extract the claim --- i.e. Skipper would not have the responsibility of authorization, but it could log the `sub` claim and the status code easily tells whether it was successful or not.

**Comment by lmineiro** [comment]
@hjacobs you mean, just base64 decoding it and pull the `sub` claim, without checking its integrity?

**Comment by hjacobs** [comment]
@lmineiro yes, it's only for logging purposes and having the correlation in Kubernetes ingress logs. The app MUST have the authorization logic anyway (and already has).
