### ISSUE TITLE
fine tune the proxy response streaming buffer size with benchmarks

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#64]
as an extra, may check if a buffer pool pays back the cost of the additional complexity

**Comment by aryszka** [comment]
measure the impact os using a buffer pool (sync.Pool?)

**Comment by LappleApple** [comment]
Labelled as "enhancement." If "Help Wanted" can also apply, thumbs-up this comment.

**Comment by aryszka** [comment]
actually this was done, to some extent, and the usage of the pool was tested, as well. Closing it for now. The benchmarks are saved as part of the repo (skptesting), so when someone experiences issues with different use cases, they can use them to make measures.
