### ISSUE TITLE
configuration documentation of the Oauth2 auth filters 

### ISSUE THREAD

**Issue by ebuychance** [zalando/skipper#640]
So I am fairly new to GO and Skipper. I have been using the latest Skipper docker image from within a docker-compose file and that works fine for me. But now I want to implement an Oauth2 authorization layer via the auth filters as described here: https://godoc.org/github.com/zalando/skipper/filters/auth

First question: Is the latest docker image up to date with the recent auth changes in the repo? Or do I need to build my own docker image? [running Skipper -version returns 'Skipper version  (commit: )' ]

Second question: How do I configure the CLI arguments? Can I use a config file or do I just set them inline via the docker entrypoint Skipper command?

Thanks

**Comment by hjacobs** [comment]
@ebuychance to answer your first question: the latest Docker image is v0.10.2-1-g4d9b358 (automatically build from master via our CI/CD pipeline). You can also find this yourself via https://registry.opensource.zalan.do/teams/pathfinder/artifacts/skipper/tags (or use the Swagger UI on https://registry.opensource.zalan.do/ui).

**Comment by szuecs** [comment]
@ebuychance to fully answer your first question: if we release in Github releases (https://github.com/zalando/skipper/releases), then we trigger the next docker build to https://registry.opensource.zalan.do/. Nothing is wrong with @hjacobs answer, but to show the process behind.

second question: We use only cli parameters for global configurations everything else is configured per route https://opensource.zalando.com/skipper/.

Right now the authorization filters are limited to tokeninfo svc-to-svc communication. 
For the next iterations in development of authorization filters, I want to ask you some questions:
What kind of OAuth2 authorization flows you want to use in the future? 
Do you have a tokeninfo endpoint or do you have a token introspection endpoint?
Do you use a specific provider (I could find more information myself to understand the possibilities better)?

**Comment by ebuychance** [comment]
Glad to hear the CI/CD builds a new docker image for each 'release.'

@hjacobs, @szuecs => **Thanks for the quick answers!**

1. _Do you use a specific provider?_
     A: [AWS Cognito](https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html) - **Can Skipper authenticate with Cognito?** (_Right now the authorization filters are limited to tokeninfo svc-to-svc communication_)

2. _Do you have a tokeninfo endpoint or do you have a token introspection endpoint?_
     A: tokeninfo

3. _What kind of OAuth2 authorization flows you want to use in the future?_
     A: I assume I will have to use the implicit grant flow with Skipper. I would like to use the authorization code grant in the future.

Thanks I am enjoying learning about these technologies outside of my front-end developer comfort zone! Any examples/direction of how to use Cognito (if possible) would be greatly appreciated.

**Comment by szuecs** [comment]
tokeninfo validation with skipper in a svc-to-svc should just work, but I am not sure if AWS Cognito has a tokeninfo endpoint. I tried to find the tokeninfo endpoint description in AWS but I did not find it.

You would start skipper with `-oauth2-tokeninfo-url=https://sometokeninfo/url` and then you can use all the filters with prefix `oauthTokeninfo` documented at https://godoc.org/github.com/zalando/skipper/filters/auth

**Comment by ebuychance** [comment]
So I thought I would play with Skipper some and see what I can figure out and hit this first thing:
**flag provided but not defined: -oauth2-tokeninfo-url**

• Do I still need to build my own docker image and import the auth lib?
• What other Oauth2 settings do I need to set? (credentials perhaps)

**Thanks in advance.** I have read all the documentation I have found so far and still not clear what all needs to be done.

**Comment by szuecs** [comment]
I am just building this, that's why I ask and can give you hints. 
As I said current state is tokeninfo should work as defined filters you can see in  https://godoc.org/github.com/zalando/skipper/filters/auth.

We have also a slack channel #skipper at https://gophers.slack.com/, invite  you can get from https://invite.slack.golangbridge.org/. Let me know if I can help you to test this setup.

The next things I will build is token_introspection filters (done in a branch) similar to tokeninfo and OpenID Connect filters based on https://github.com/coreos/go-oidc. I guess the last is what most users like to have, but I am not sure and this is why I ask. :)

**Comment by ebuychance** [comment]
Honestly I am not sure the difference between tokenInfo and introspection.
I thought introspection was only for checking if a token is 'active' and I have not seen any Cognito responses that return 'active'.

I did manually change the /home#access_token=... to /home?access_token=...

And then I got the auth failure {"method":"GET","path":"/home","status":401,"authStatus":{"rejected":true,"reason":"**auth-service-access**"}}

I will check out the Slack channel thanks.

**Comment by szuecs** [comment]
@ebuychance tokeninfo seems to be an older agreement from some oauth2 providers. There is no rfc or so. Token introspection has an rfc. The RFC https://tools.ietf.org/html/rfc7662#section-2.1 says you you have either ?access_token=<a-token> or the Authorization header with Bearer <a-token> 
The invalid Bearer token says that it did not found a token in the Authorization header.

At https://github.com/zalando/skipper/blob/master/filters/auth/oauth.go#L75 we get the access token from the request. We check the query and the header, which is a problem, if you get a fragment. What you can do is to write a custom filter for your query to fragment handling.  Maybe in the future we can implement the fragment check, too.
To unblock you you can write a script in lua or create a go plugin to build custom filters.
- https://opensource.zalando.com/skipper/scripts/
- https://opensource.zalando.com/skipper/plugins/#filter-plugins

If you like to do more source browsing:
In https://github.com/zalando/skipper/blob/master/filters/auth/oauth.go#L150 we prepare the call to the tokeninfo/ maybe this is also different form what AWS expects.

**Comment by szuecs** [comment]
@ebuychance tokeninfo seems to be an older agreement from some oauth2 providers. There is no rfc or so. Token introspection has an rfc. The RFC https://tools.ietf.org/html/rfc7662#section-2.1 says you you have either ?access_token=<a-token> or the Authorization header with Bearer <a-token> 
The invalid Bearer token says that it did not found a token in the Authorization header.

At https://github.com/zalando/skipper/blob/master/filters/auth/oauth.go#L75 we get the access token from the request. We check the query and the header, which is a problem, if you get a fragment. What you can do is to write a custom filter for your query to fragment handling.  Maybe in the future we can implement the fragment check, too.
To unblock you you can write a script in lua or create a go plugin to build custom filters.
- https://opensource.zalando.com/skipper/scripts/
- https://opensource.zalando.com/skipper/plugins/#filter-plugins

If you like to do more source browsing:
In https://github.com/zalando/skipper/blob/master/filters/auth/oauth.go#L150 we prepare the call to the tokeninfo/ maybe this is also different form what AWS expects.
