### ISSUE TITLE
redirect filter after failed oauthfilter

### ISSUE THREAD

**Issue by ebuychance** [zalando/skipper#642]
How do I redirect after a failed oauthfilter?

I incorrectly thought I could do something like this:
home: Path("/home") ->  auditLog() -> oauthTokeninfoAnyScope("openid", "email") -> redirectTo(401, "http://tailor:8080/login") -> "http://tailor:8080/home";

**Comment by ebuychance** [comment]
@aryszka Ok thanks. Is that feature part of the introspection branch I wonder?

**Comment by szuecs** [comment]
Not right now, I think I will implement in the next weeks the authCode exchange which I guess you also like to have. 
Is my assumption correct?

**Comment by ebuychance** [comment]
yes thanks
