### ISSUE TITLE
Scope Kubernetes Dataclient to a Single Namespace

### ISSUE THREAD

**Issue by daviddyball** [zalando/skipper#686]
Hi Guys,

I can see in https://github.com/zalando/skipper/blob/master/dataclients/kubernetes/kube.go#L1100 that Skipper currently uses the cluster-scoped URI for listing ingresses. Is it possible to have a flag that allows switching between the two types of ingress list endpoints?

Cluster scoped: `/apis/extensions/v1beta1/ingresses`
Namespaced: `/apis/extensions/v1beta1/namespaces/{namespace}/ingresses`

Perhaps something like `-kubernetes-namespace={namespace}` that would allow switching between the two types of behaviour?

Cheers,
David

**Comment by szuecs** [comment]
What is the use case for that?
We have the ownership model via annotation, so what is the advantage of having it per namespace separated?
I am in general fine with that, but the use case should be clear and documented.

**Comment by daviddyball** [comment]
Hi @szuecs ,

We have multiple environments separated by namespace (and taints/tolerations for hardware segregation). If, for example, we have `development`, `staging` and `production` namespaces we would have the following ingresses configured: `web`, `api` and `internal` and each of these has an AWS load-balancer. For ease of configuration, we'd like to re-use the same `ingress.class` values for each, otherwise it's more templating that needs to be done when we deploy into each environments namespace (e.g. using `ingress.class: api` is better than having to do `development-admin`, `staging-admin` and `production-admin`).

Thoughts?

I've also started writing a PR to add support for it, but my Go unit-testing experience is very limited and it feels bad-form to submit a PR without unit-tests 😖 

Cheers,
David

**Comment by szuecs** [comment]
Sounds like a good use case.
Can you add this to the docs/kubernetes/ingress-deployment.md, please? (I hope I remember the filename correctly)

**Comment by daviddyball** [comment]
Docs updated in the PR 👍

**Comment by daviddyball** [comment]
Added a commit for basic unit-test as well 😄

**Comment by aryszka** [comment]
done in https://github.com/zalando/skipper/pull/688
