### ISSUE TITLE
Weight() predicate - former: https redirect with kubernetes dataclient is radomly bypassed

### ISSUE THREAD

**Issue by ese** [zalando/skipper#689]
It seems related with #662 

Requests to http endpoints are supposed to be responded with a 301 to https but are radomly bypassed directly to the service. This seems only happened in services with several replicas and the loadbalancer feature is creating the routes.

I guess it can be related with how routes are gen and stored in memory and how the predicates are weight.

As much skipper replicas and ingresses you have more probabilities this happens.

example of routes with this problem:
```
kube_default__nginx_1__test_nginx______nginx_slash_1: Host(/^test-nginx$/) && PathRegexp(/^\//) && LBMember("kube_default__nginx_1__test_nginx______nginx_slash", 1)
  -> dropRequestHeader("X-Load-Balancer-Member")
  -> "http://100.96.3.5:8080";


kube_default__nginx_1__test_nginx______nginx_slash_2: Host(/^test-nginx$/) && PathRegexp(/^\//) && LBMember("kube_default__nginx_1__test_nginx______nginx_slash", 2)
  -> dropRequestHeader("X-Load-Balancer-Member")
  -> "http://100.96.3.8:8080";

kube_default__nginx_1__test_nginx______nginx_slash_0: Host(/^test-nginx$/) && PathRegexp(/^\//) && LBMember("kube_default__nginx_1__test_nginx______nginx_slash", 0)
  -> dropRequestHeader("X-Load-Balancer-Member")
  -> "http://100.96.1.27:8080";

kube_default__nginx_1__test_nginx______nginx_slash__lb_group: Host(/^test-nginx$/) && PathRegexp(/^\//) && LBGroup("kube_default__nginx_1__test_nginx______nginx_slash")
  -> lbDecide("kube_default__nginx_1__test_nginx______nginx_slash", 3)
  -> <loopback>;

kube__redirect: PathRegexp(/.*/) && Header("X-Forwarded-Proto", "http") && HeaderRegexp("X-Forwarded-Port", /.*/)
  -> redirectTo(301, "https:")
  -> <shunt>;
```

**Comment by szuecs** [comment]
It looks like we created a race condition in the predicate between the lb group lookup and the redirect.
@aryszka can you check that?
For me it looks like 3 predicates vs. 3 predicates.

**Comment by aryszka** [comment]
checking

**Comment by aryszka** [comment]
true, this is a priority race between the redirect route and the loadbalanced routes. My first idea to fix it would be to check explTicitly on the other routes that the X-Forwarded-Proto header is set to https and not http. But I can't say that I really like this approach. What do you think? Or do you have a different suggestion?

Another way can be to put a skipper in a separate container next to the main ingress container, with an inline route that does only the redirect, listens on a different port, and the non-https traffic is directed to that port. In one of our non-kubernetes deployments, we use a similar approach and works for us.

@ese as a temporary workaround, until we fix this you can try either the separate container approach, or you can set a `Header("X-Forwarded-Proto", "https")` as a custom predicate in an annotation for the ingress specifications.

**Comment by aryszka** [comment]
as @szuecs pointed out, for the real fix, we could also generate a Prioirty or Weight predicate for the redirect route, once a Weigh(Priority) predicate feature makes it to the master, that is something similar to what suggested here: https://github.com/zalando/skipper/issues/360#issuecomment-393123286

**Comment by szuecs** [comment]
@aryszka in this case we could just have a negative match for example: `url.Scheme != "https"`, not sure if this is set, but we could test it and do not match the redirect route.

**Comment by stormmore** [comment]
I believe I just ran into this issue but in my case, I have narrowed it down to if you have a trailing / when you put the FQDN in or not, e.g. domain.com vs domain.com/. In the former case, it is bypassing the redirect, the latter is successful.

I am currently running v0.10.92

**Comment by cg-rsands** [comment]
Hsas there been any update on a fix for this?  The suggested one above does not cover it 100% of the time

**Comment by szuecs** [comment]
- 4 steps sound great to me.
- `Weight()` should return an `int`, not float, because do not use a complicated type if a simple is enough. Float is not easy to compare with `==` for example (you need always to define an epsilon and use `<=` and `>=').
- Weight() should be also counted as predicate, because you could workaround some problems if you just have multiple Weight() defined in your route, if you need

**Comment by aryszka** [comment]
"return an int" :+1: 
"Weight() should be also counted as predicate" :+1: 
"Match() int" not sure at the moment, because i believe we can do this more effectively during the route generation phase outside of the request processing instead of the route matching phase.

**Comment by ese** [comment]
:+1: to count as predicate and return int

**Comment by szuecs** [comment]
Thanks! Then I think we just do the proposal from @aryszka as stated in https://github.com/zalando/skipper/issues/689#issuecomment-426021387

**Comment by xavivars** [comment]
Is there appetite for such a feature? We'd need the `weight()` predicate, and we're happy to implement it.

**Comment by szuecs** [comment]
We started to have a [public document](https://docs.google.com/document/d/1fBrCTcvDGFVmCnmcwTevOfCa9j86TewAnn-D1U-Xtas/edit#) to collect problems and solution ideas.
Everyone is welcome to suggest paragraphs, changes, ....

**Comment by szuecs** [comment]
https://opensource.zalando.com/skipper/reference/predicates/#weight-priority was done
