### ISSUE TITLE
Brotli Support in `compress()` filter

### ISSUE THREAD

**Issue by grassator** [zalando/skipper#696]
Brotli is [widely supported by the browsers](https://caniuse.com/#feat=brotli) and [seems to offer better compression than gzip with faster speed](https://blogs.akamai.com/2016/02/understanding-brotlis-potential.html).

There seem to be [official binding](https://github.com/google/brotli/tree/master/go) but no native go implementation from what I could find.

**Comment by szuecs** [comment]
We could also implement an opensource filter plugin to implement brotli

**Comment by grassator** [comment]
@szuecs Would you make it as a separate filter then?

**Comment by aryszka** [comment]
wondering if the init phase of the brotli support requires any native calls. If it doesn't, then there's not much difference. In case we decide to build it as a plugin, then yes, it has to be a separate filter. Also, if it's a plugin, then we should extract the stream encoding logic of the current compress filter into its own support package (e.g. "streamencoding").

**Comment by grassator** [comment]
@aryszka how would you imagine adding support without native calls?

**Comment by szuecs** [comment]
@yes I would put it into https://github.com/skipper-plugins/filters

**Comment by grassator** [comment]
@szuecs I'm not sure that a separate filter is a good idea. The problem is that the client sends a list of preferred encodings as a header: `Accept-Encoding: brotli,gzip,deflate`. If we implement `brotli()` as a separate filter, the order `compress()` and `brotli()` in the route will influence the resulting behavior which is brittle.

Alternative would be to have a default `compress()` filter implementation that does not include brotli and then have some kind of code generation / compile time flag that pulls in brotli native code.

We could also do `compressWithBrotliSupport()` but seems ugly as well...

**Comment by szuecs** [comment]
You are right that it can be done withing `compress` filter or you could add filters to configure what compress will support via filters like `brotli()`.

**Comment by szuecs** [comment]
https://github.com/andybalholm/brotli could be likely used to implement the reader and writer. I also created https://github.com/klauspost/compress/issues/443 , because this includes optimized drop in replacements for other compress algorithms, too.
