### ISSUE TITLE
unknown field 'DisableTimestamp' in struct literal of type logrus.JSONFormatter

### ISSUE THREAD

**Issue by jalateras** [zalando/skipper#700]
Has anyone else come across this issue when building skipper

```
$make build
go build ./packaging/... ./predicates/... ./filters/... ./metrics/... ./cmd/... ./tracing/... ./innkeeper/... ./net/... ./oauth/... ./proxy/... ./eskip/... ./eskipfile/... ./circuit/... ./loadbalancer/... ./script/... ./ratelimit/... ./pathmux/... ./etcd/... ./dataclients/... ./routing/... ./skptesting/... ./logging/... .
# github.com/zalando/skipper/logging
../../zalando/skipper/logging/log.go:64:84: unknown field 'DisableTimestamp' in struct literal of type logrus.JSONFormatter
make: *** [lib] Error 2
```

using

```
go version go1.10.3 darwin/amd64
```

**Comment by szuecs** [comment]
Do you have another version of logrus in your $GOPATH or did not run `glide install`?

We specified in glide.yaml:

    - package: github.com/sirupsen/logrus
      version: ~1.0.0

**Comment by aryszka** [comment]
the latest logrus has this field in the jsonformatter, too. A `go get -u github.com/sirupsen/logrus` can fix it, too.

**Comment by szuecs** [comment]
I think we can close this, because it’s most likely dependency missing or not updated.
