### ISSUE TITLE
Ingress redirectTo doesn't keep the url suffix

### ISSUE THREAD

**Issue by fpozzobon** [zalando/skipper#701]
Hi,

when adding the annotation : redirectTo(301, "https://myUrl")
for the host : redirected.url.do

I was expecting that https://redirected.url.do/aSufix?prop=value
would redirect to https://myUrl/**aSufix?prop=value**
but instead redirect to https://myUrl/**?prop=value**

Is there a way to keep the full url sufix when redirecting ?

Thanks by advance,

Fabien

**Comment by fpozzobon** [comment]
Got the answer from @szuecs : 

modPath("^/", "/")
      -> redirectTo(301, "https://myUrl")

Note : in my case I wanted a redirect like : 
 - redirectTo(301, "https://myUrl/foo")
so it should be like 
 - modPath("^/", "/foo")
      -> redirectTo(301, "https://myUrl")

**Comment by addityasingh** [comment]
@fpozzobon Seems you found the answer to your issue. @szuecs Is this issue still valid for documentation purpose?

**Comment by szuecs** [comment]
@addityasingh https://opensource.zalando.com/skipper/filters/#redirectto does not show it so I would say, yes

**Comment by fpozzobon** [comment]
Hi @addityasingh, I kept the issue open as a reminder to update the documentation.
But from my point of view the issue is solved ;)

**Comment by addityasingh** [comment]
@szuecs I will try to add somethings soon so that we can close it
