### ISSUE TITLE
Consider: filter to put a specific header to the opentracing span as a tag

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#704]
Would it make sense to create a filter that takes a request header and puts it into the current span? E.g:

```
setTracingTag("X-Flow-ID", "http.flow_id")
```

would take the value of the X-Flow-ID header if any and set it as the http.flow_id tag in the ingress span.

**Comment by lmineiro** [comment]
This sounds like a useful addition. We should also have the matching `setTracingLog()`. The example given is a good use case for logs instead of tags due to the high cardinality.

The name of the filter doesn't really suggest that it extracts the header. Would something like `tracingTagFromHeader()`/`setTracingTagFromHeader()` make it easier to grasp?

**Comment by aryszka** [comment]
+1 for both tracing logs and the naming.

the reason for using tag in the example was that some vendors implement querying only for the tag, and thought it can be useful to find a trace starting from having a flow id only. Not sure how realistic this is.

**Comment by addityasingh** [comment]
Also this would easily enable organizations using skipper to enforce their standard conventions for Tracing spans

**Comment by szuecs** [comment]
Do we need more than https://opensource.zalando.com/skipper/reference/filters/#tracingtag or close this issue?

**Comment by ruiaraujo** [comment]
@szuecs the idea would be to have something like `headerToTracingTag`, although something like https://github.com/zalando/skipper/issues/1444 could allow implementing this in a different way.

**Comment by szuecs** [comment]
I agree and think maybe #1444 is the more generic one which would allow better combinations for composition

**Comment by AlexanderYastrebov** [comment]
If we enhance `tracingTag` filter to support [template placeholders](https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#template-placeholders) the solution would look like
```
* -> flowId("reuse") -> tracingTag("xflowid", "${request.header.X-Flow-Id}")
```
