### ISSUE TITLE
Plugin usage harms Skipper as library use case

### ISSUE THREAD

**Issue by ruiaraujo** [zalando/skipper#706]
We are using Skipper as a library for building an internal proxy.
Recently we added vendoring to ensure build stability, unfortunately this resulted in issues with the lightstep plugin which we are using.

```level=fatal msg="module lightstep's InitTracer function has wrong signature"```

I do not think plugins should be used by user of Skipper library capabilities so it makes the downstream projects harder to build.

**Comment by aryszka** [comment]
for the tracing plugins, see: https://github.com/skipper-plugins/opentracing

**Comment by szuecs** [comment]
We now have opentracing pulled inside skipper. Therefore I close this
