### ISSUE TITLE
Routes endpoint not giving every route loaded

### ISSUE THREAD

**Issue by jchanam** [zalando/skipper#713]
We're using Skipper on our k8s cluster. It's loading automatically all ingresses and converting them to it's own routes.

We sometimes need to get all the routes loaded. We do that executing a curl inside the pod:
```
curl "http://localhost:9911/routes"
```

The problem we're facing is that even though this call returns a list of routes, it's not complete. If we check the number of lines, it's a changing number near to 4300 lines.

Is there any way of not limiting this response?

**Comment by jchanam** [comment]
I'm reading the routing code, and I've seen that a header called `X-Count` is added with the total number of routes loaded.

In our case this value is `6842`. It's way higher that the routes given in the body.

**Comment by szuecs** [comment]
@jchanam do you use kubernetes dataclient or some other dataclient?

**Comment by aryszka** [comment]
@jchanam @szuecs the /routes support endpoint enforces paging, and by default page limit 1024. The paging can be done with query parameters, e.g.:

```
curl 'http://localhost:9911/routes?offset=128&limit=512'
```

...will return the routes from offset 128, and 512 of them. Could you please try if it works for you as expected?

**Comment by jchanam** [comment]
Hi!

@szuecs Yes, I'm using the K8S datasource.
@aryszka Thanks! After reading the code i get to that information. I've done a PR in order to add that info to the docs. I confirm it's working.

**Comment by aryszka** [comment]
thanks a lot @jchanam !
