### ISSUE TITLE
Kubernetes ingress custom-routes not setting Path() based predicates based on the ingress definition

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#719]
When I updated the docs https://github.com/zalando/skipper/pull/718 , I found out that we do not care about the path setting from the ingress spec definition, in our custome-routes settings. 
We should add to all custom-routes based on the ingress spec not only the Host() predicate but also the Path() PathSubtree or PathRegexp predicate as defined in the skipper cli as parameter.

**Comment by aryszka** [comment]
See: #720

**Comment by szuecs** [comment]
https://github.com/zalando/skipper/pull/718 was merged
