### ISSUE TITLE
authnzWebhook filter

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#744]
Based on https://github.com/zalando/skipper/issues/741#issuecomment-413602859.

`authnzWebhook(<url>)`  filter should:
- send the request headers and query to `<url>`, which can implement an authorization service and will reply with 200 to allow access to the backend or 401, 403 to disallow access and all other responses will disallow access log an error and return a static string to the client.

**Comment by aryszka** [comment]
how about just hook()? To make it more generic.

**Comment by aryszka** [comment]
the authnzWehook() filter could be a specialization of a more generic filter: hook(<url>). hook(<url>[, sendBody]) could initially work like this:

On the request path:

1. pause the request processing
2. send a copy of the request to the configured URL (hook request)
3. hook request returns...
3a. 2xx: continue the request processing
3b. non-2xx: shunt with the status of the hook request

On the response path: noop

**Comment by szuecs** [comment]
sendBody is abool which is optional in your spec?

**Comment by aryszka** [comment]
correct, it's an optional bool, defaulting to false. It should use a similar logic to the audit filter, so that the body for the case of forwarding the request is preserved.

**Comment by szuecs** [comment]
#747 was merged
