### ISSUE TITLE
Route based on missing headers

### ISSUE THREAD

**Issue by patrickdk77** [zalando/skipper#749]
I can use predicate to route via headers, but it only works if a header exists. There doesn't seem to be any method to set a route, if a header is missing.

**Comment by szuecs** [comment]
@patrickdk77 so a negative header predicate?
Makes sense to me.

**Comment by aryszka** [comment]
I am not sure if this is a good predicate among the main built-in ones. Negative predicate logic may lead to various ambiguities. We decided not to have them very early on, but unfortunately I can't recall now the exact reasoning (wish to have had a decision log).

What works for in most cases, is something like this:

```
routeForMissingHeader: Path("/foo") -> "https://backend1";
routeForHeaderPresent: Path("/foo") && HeaderRegexp("X-Foo", ".*") -> "https://backend2";
```

Which is basically the other way around, and will send the requests without the X-Foo header to backend1, while the requests with the header present to backend2.

Of course when there is a large number of routes, and more overlapping cases, then the routes should be rather generated.

**Comment by szuecs** [comment]
A workaround was provided, by @aryszka and he is right it would have a negative impact on other routes easily.

**Comment by tglocicero** [comment]
How does this work?
`routeForMissingHeader: Path("/foo") -> "https://backend1";
routeForHeaderPresent: Path("/foo") && HeaderRegexp("X-Foo", ".*") -> "https://backend2";`

Then wouldn't host.com/foo (without X-Foo header) match two routes? How would you know which backend it would be routed to?

**Comment by szuecs** [comment]
The answer is documented at https://opensource.zalando.com/skipper/tutorials/basics/#route-matching
