### ISSUE TITLE
Switch to Go 1.11 modules (and streamline build)

### ISSUE THREAD

**Issue by mikkeloscar** [zalando/skipper#763]
Currently the skipper Makefiles consists of a mix of `go get` and `glide install --strip-vendor`. It's a bit confusing this way and hard to understand what version of packages skipper really is being build against. We also have some hacks in place to be able to build plugins: https://github.com/zalando/skipper/blob/5d7ae30e7f71a566b2562906f86959a6044ed319/Makefile#L89-L94

Since we have Go modules in Go 1.11 I would like to take this as an opportunity to streamline the skipper build/dependency management a bit.

What do you think? Does it make sense to try out Go Modules already or is it too early? It will put a hard depedency on Go 1.11 for skipper. IMO this is fine, and I believe Go Modules are much better than glide already!

/cc @szuecs @aryszka @vetinari

**Comment by szuecs** [comment]
The current try to link the build does not work at runtime. My idea was also to use go modules or use plain go get -d (IIRC works, but is is not nice) or rewrite the plugins into the library and use the register approach at build time to choose which implementation to use (similar to db package in go, but it will require one binary per opentracing plugin)
