### ISSUE TITLE
Create routes for ingress east/west communication (cluster internal svc-to-svc)

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#791]
I just had a discussion with my colleagues how to enable cluster internal "east/west" communication to be proxied and loadbalanced through skipper, too. This is an enhancement for cluster internal communication through Kubernetes service, because of more functionality for east/west calls (used as internal API GW) and reliability, for example transparent connection retry.

External-DNS or [CoreDNS](https://github.com/coredns/coredns) (or maybe /etc/hosts, but wildcards seem not to work) can create records for skipper into coredns derived from ingress name and namespace: `<name>.<namespace>.skipper.cluster.local`
A flag in skipper would enable `-enable-kubernetes-east-west` (better name?) duplication of additional routes for all ingress with `Host()` predicates and change the `Host()` predicate for the cluster internal route.

## Example

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
  namespace: default
spec:
  rules:
  - host: demo.example.org
    http:
      paths:
      - backend:
          serviceName: example
          servicePort: 80
```

The shown ingress normally creates a frontend route and for all endpoints corresponding to the service backend routes. All of these have to be duplicated if these contain the `Host()` predicate, which is automatically set for  `demo.example.org`.
If enabled, skipper would additionally to these duplicate the routes and change the `Host()` predicate to `demo.default.skipper.cluster.local`.  (Thanks @aermakov-zalando for the better hostname hint!)

## additional things to solve to enable this

From skipper and HTTP Host header point of view this would already work. We only need to have a documented idea how to create the DNS entries pointing to the skippers.

### Kubernetes service to access skipper

Skipper should be deployed additionally with kubernetes service type ClusterIP to have a fixed, loadbalanced IP for all the skippers.

### populate DNS

Creating the DNS records is simple with the `template` plugin from CoreDNS.

Corefile example:
```
.:1053 {
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        upstream
        fallthrough in-addr.arpa ip6.arpa
    }
    template IN A skipper.cluster.local  {
      match "^.*[.]skipper[.]cluster[.]local"
      answer "{{ .Name }} 60 IN A 10.3.11.28"
      fallthrough
    }
    prometheus :9153
    proxy . /etc/resolv.conf
    cache 30
    reload
}
```

### resolve DNS

DNS resolution should just work as the normal flow, no changes needed.

#### optional add custom search in resolv.conf

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-config shows that you can pass a custom `dnsConfig` with `searches` to add also `skipper.cluster.local` domain to the resolv.conf and add one additional `ndots` to resolve it. 

## Old idea to create routes for service type ClusterIP

If you create a service type ClusterIP `foo` in namespace `bar` you get service name in DNS: `foo.bar.svc.cluster.local`
If skipper would create automatically for all of these a service type clusterIP with prefix "skipper-"  and points to skipper-ingress (by label selector), we would get `skipper-foo.bar.svc.cluster.local` pointing to the skipper ingress controller.

Skipper would then need to create for all these "skipper-" prefixed services the routes with endpoints from the endpoints without the "skipper-" prefix.

Like this we could support cluster internal traffic to pass through skipper and users only need to send traffic to the "skipper-" prefixed DNS to call their destination service.

How do you like the idea or do you have other similar ideas?

Cc @mikkeloscar @aermakov-zalando @aryszka @arjunrn  @ese @jchanam

**Comment by aermakov-zalando** [comment]
We could also map hostnames like `foo.bar.skipper.cluster.local` somehow to the Skipper endpoint (with CoreDNS?) and then we wouldn't have to create hundreds of useless services and keep them in sync.

**Comment by stormmore** [comment]
being nitpicky and the keystroke conscientious person that I am, I would prefer something like `*.skp.cluster.local`, kinda like the `svc` for service.

nice to have, would be the ability to configure LB policy for the services.
