### ISSUE TITLE
auditLog() filter captures the body in logs

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#798]
https://github.com/zalando/skipper/blob/master/filters/log/log.go#L157-L162 shows the relevant code.
Default is set to 1024 https://github.com/zalando/skipper/blob/master/cmd/skipper/main.go#L43
This can be overidden via  `--max-audit-body=<int>`

I learned that this was done on purpose, but maybe we should change the default.
Therefore I will remove the **bug** label.

**Comment by aryszka** [comment]
i think this is the intended behavior of the auditLog filter, and the defaults and/or the documentation doesn't meet the expectations. Currently, by default 1024 bytes of the body is logged.

**Comment by szuecs** [comment]
We also do not have it in our new documentation
