### ISSUE TITLE
Add pre-route and post-route filters

### ISSUE THREAD

**Issue by lmineiro** [zalando/skipper#8]
Pre-Route filters allows us to always go through a set of filters that are relevant enough to be applied to each and every route. Owners of the routes don't need to include them and they also can't opt-out.

Post-Route filters can be used to blacklist given headers / cookies, for ex. or override specific headers like 'X-Powered-By', for ex.

**Comment by danpersa** [comment]
:+1:

**Comment by aryszka** [comment]
done
