### ISSUE TITLE
Make Innkeeper WriteClient secure

### ISSUE THREAD

**Issue by danpersa** [zalando/skipper#80]
Write now, we create it with the insecure flag. `writeclient.go:32`

**Comment by aryszka** [comment]
note: this issue belongs to add-innkeeper-cmd

**Comment by LappleApple** [comment]
Labelled as "enhancement." If "Help Wanted" can also apply, thumbs-up this comment.

**Comment by aryszka** [comment]
some of the related issues could be bundled into a single "innkeeper client" issue.

**Comment by szuecs** [comment]
I close this, because we decided to deprecate inkeeper.
