### ISSUE TITLE
X-Forwarded-Proto not sent to backend services

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#807]
Investigation required: the X-Forwarded-Proto header seems not to be forwarded to the backend services.

**Comment by lmineiro** [comment]
Is the hypothesis that skipper receives such header which, for some reason, is not delivered to the route backend?

**Comment by szuecs** [comment]
@aryszka I don't see that this is true:

```
./bin/skipper -inline-routes '* -> "http://127.0.0.1:8080/"' 

# backend
% nc -l 8080
GET / HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: curl/7.49.0
Accept: */*
X-Forwarded-Proto: foo
Accept-Encoding: gzip

# client 
curl -H"X-Forwarded-Proto: foo" localhost:9090

**Comment by diegoroccia** [comment]
@szuecs you're right, it was a problem on the LB configuration.

**Comment by szuecs** [comment]
So I close this one
