### ISSUE TITLE
tee() filter between two kubernetes clusters with skipper load balancing between the endpoints

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#808]
in load balanced routes, the X-Load-Balancer-Member is dropped at the end of the route. This causes a problem in case of the tee() filter, when the tee requests go to another similar Kubernetes cluster.

**Comment by aryszka** [comment]
suggested solution: consider moving the generated dropRequestHeader("X-Load-Balancer-Member") filter in front of the custom annotation filters

**Comment by lgogolin** [comment]
@aryszka workaround for this issue that works is to add dropRequestHeader() before tee()

After that routes will looks like this:

```
tmp_svc: Host(/^prod.domain.name$/) && LBMember("prod_domain_name___tmp_svc", 2)
  -> dropRequestHeader("X-Load-Balancer-Member")
  -> tee("http://stg.domain.name")
  -> dropRequestHeader("X-Load-Balancer-Member")
  -> "http://X.X.X.X:8080";
```

**Comment by aryszka** [comment]
yes, it should be the first.
