### ISSUE TITLE
service__lb_group, status code 500: http: invalid Read on closed Body

### ISSUE THREAD

**Issue by vpistis** [zalando/skipper#809]
Hi,

we experienced some trouble with our web app (we use skipper and kube-aws-ingress-controller).

Skipper log this kind of message `....service__lb_group, status code 500: http: invalid Read on closed Body...` generally while pods are being created (and new requests are routed to this web app).

For each deployment we have specified `minReadySeconds: 45` and we expect requests to be routed to new pods after this amount of time, because these pods are not able to serve requests before 45 secs.

From docs we know that skipper discover routes using this endpoint api `/api/v1/namespaces/{namespace}/endpoints/{name}`.
We noticed that this api response inlcudes also the pods that are still being created and not only the ones for that `minReadySeconds` are elapsed.

Does skipper includes all these pods? 
If true, is there a solution to force skipper to wait `minReadySeconds` before routing requests to new pods?

thanx a lot for this great project.

Ciao

**Comment by szuecs** [comment]
Yes, skipper will read every 3s ingress and endpoints to update the routing table.

I think you have to fix it on your application and PodSpec level. Use readinessProbe to only be ready if your application is ready to serve traffic. This will ensure that your Pod is only put int the endpoints list, if it's ready to serve the traffic.

**Comment by vpistis** [comment]
wow!
I had not thought about it,

thanx a lot! :)

**Comment by szuecs** [comment]
@vpistis please reopen if it does not solve your problem. Thanks!
