### ISSUE TITLE
Route by X-Forwarded-Host

### ISSUE THREAD

**Issue by boogolli** [zalando/skipper#817]
I was wondering that is it possible to route by the X-Forwarded-Host header instead of Host?

**Comment by szuecs** [comment]
Not right now, but you can easily write a predicate for it.
If you can write a bit of Go, it's only an interface with one function to implement.
We are happy to help.

https://github.com/zalando/skipper/blob/master/predicates/source/source.go#L106 is the methid to implement, similar.

**Comment by szuecs** [comment]
I think I am wrong and the pointed `Source()` predicate is exactly what you search.
How `Source()` and `SourceFromLast()` work  is documented at https://opensource.zalando.com/skipper/reference/predicates/#source.

Please reopen, if something is not working as intended it you have another idea how the routing should work.
