### ISSUE TITLE
Ingress Path Matching - Default Backends and Catch-All Regex's Trump All Other Path Matches

### ISSUE THREAD

**Issue by kailam77** [zalando/skipper#819]
I'm trying to apply a 'blacklist' of paths that should 404.  My intent is to define path rules that send matching requests to a 404 service, and have all other requests route to the app.  I've tried a few approaches to accomplish this, documented in detail below.  What I'm finding is that if there is a default backend defined, all the path rules are ignored and everything gets routed to the default backend.  And, if a 'catch-all' path rule is define, e.g. '/.*', again the other path rules are ignored, and all requests route to the catch-all.

The only way to make the blacklist path rules work is to have specific 'whitelist' paths defined that route to the app (see cases below for details).  This is undesirable since we have a lot of different URL's and don't want to have to whitelist them all.

The behavior here is the opposite of what I'd expect.  I would think that if a path matches a path rule, that should take precedence over the default or the catch-all generic regex.  Instead, it seems like the broadest match is the one that wins.  This also seems contrary to the [documentation](http://opensource.zalando.com/skipper/reference/architecture/#route-processing).

We can get the blacklist logic to work using custom routes, specifying \<shunt\> for the blacklisted routes, but we'd rather avoid skipper-specific annotations if possible.  Is there a reason for the current path matching behavior, or is this a bug?

## Case 1: (Control case) Default backend, no blacklist
* *Result:* Works as expected
* *Expected:*
  * /heartbeat/ returns "OKOKOK"
  * /health/ returns "UP"
* *Actual:* Matches Expected

#### ingress.yml:
    ...
    spec:
      backend:
        serviceName: landers2
        servicePort: http

#### Output:
    $ curl https://site.com/heartbeat/
    {"status":"OKOKOK"}
    
    $ curl https://site.com/health/
    {"status":"UP"}

## Case 2: Path blacklist and default backend
* *Result:* Doesn't work - path match rule is ignored.
* *Expected:*
  * /heartbeat/ returns 404
  * /health/ returns "UP"
* *Actual:* /heartbeat/ returns "OKOKOK"

#### ingress.yml:
    ...
    spec:
      backend:
        serviceName: landers2
        servicePort: http
      rules:
      - host: site.com
        http:
          paths:
          - path: /heartbeat/
            backend:
              serviceName: default-404-service
              servicePort: web-port

#### Output:
    $ curl https://site.com/heartbeat/
    {"status":"OKOKOK"}
    
    $ curl https://site.com/health/
    {"status":"UP"}
    {code}

## Case 3: Path blacklist and whitelist
* *Result:* Works as expected, but requires whitelist
* *Expected:*
  * /heartbeat/ returns 404
  * /health/ returns "UP"
* *Actual:* Matches Expected

#### ingress.yml:
    ...
    spec:
      rules:
      - host: site.com
        http:
          paths:
          - path: /heartbeat/
            backend:
              serviceName: default-404-service
              servicePort: web-port
          - path: /health/
            backend:
              serviceName: landers2
              servicePort: http

#### Output:
    $ curl -I https://site.com/heartbeat/
    HTTP/2 404 
    date: Wed, 10 Oct 2018 17:23:16 GMT
    server: Skipper
    
    $ curl https://site.com/health/
    {"status":"UP"}

## Case 4: Path blacklist and catch-all whitelist
* *Result:* Does not work - path match rule is ignored
* *Expected:*
  * /heartbeat/ returns 404
  * /health/ returns "UP"
* *Actual:* /heartbeat/ returns "OKOKOK"

#### ingress.yml:
    ...
    spec:
      rules:
      - host: site.com
        http:
          paths:
          - path: /heartbeat/
            backend:
              serviceName: default-404-service
              servicePort: web-port
          - path: /.*
            backend:
              serviceName: landers2
              servicePort: http

#### Output:
    $ curl https://site.com/heartbeat/
    {"status":"OKOKOK"}
    
    $ curl https://site.com/health/
    {"status":"UP"}

**Comment by szuecs** [comment]
Thanks for your well written bugreport!

Can you dump and post the routes for the not as expected working cases, please?

In the other hand you could also use the custom-routes annotation with a Path(“heartbeat“) predicate and use status(404) -> <shunt> to blacklist the matching routes. https://opensource.zalando.com/skipper/kubernetes/ingress-usage/#custom-routes

**Comment by kailam77** [comment]
I don't have access to the logs in my system, I'll try to get dumps when possible.

Yeah, our solution for now is to use the custom routes.  It just ties us to Skipper annotations (seemingly) unnecessarily.

**Comment by szuecs** [comment]
Dump the routes:

Kubectl exec into skipper, then:
`wget -O/dev/stdout http://localhost:9911/routes`

Thanks for your great writing in this issue!

**Comment by szuecs** [comment]
The problem is that the route for the heartbeat backend is not created. I bet the problem is, that the service has no valid endpoints. 404 is the default and if it does not proxy to default-404-service to get a 404, than another route can match the request and respond OK.
 
Please show `kubectl get ep -o wide default-404-service` and `kubectl get svc -o yaml default-404-service`.

**Comment by szuecs** [comment]
We don't have loopback routes for load balanced backend anymore which could likely have caused this issue.
Because we got no response, I will close it. Please let us know if you hit one of these cases with a current version.
