### ISSUE TITLE
Investigate if function need pre and post route filters

### ISSUE THREAD

**Issue by danpersa** [zalando/skipper#82]
innkeeper/client.go:238

    func convertJsonToEskip(data []*routeData, preRouteFilters, postRouteFilters []*eskip.Filter) ([]*eskip.Route, []string, string)

**Comment by LappleApple** [comment]
@danpersa @aryszka What's the status of this issue? Still actively in progress?

**Comment by aryszka** [comment]
this was actually implemented in #127
