### ISSUE TITLE
Examples of how to use Skipper in a Docker container

### ISSUE THREAD

**Issue by thecodejunkie** [zalando/skipper#828]
Are there any examples of how to use the Docker version of Skipper and Eskip to use a .eskip file? I.e how would I use a local .eskip file with those commands? I would like to use the container version, for a bit of local testing, without having to setup and use Go. 

1. How would I use `docker run registry.opensource.zalan.do/pathfinder/skipper:latest eskip check` to check a local file?
2. How would I use `docker run registry.opensource.zalan.do/pathfinder/skipper:latest skipper` to run skipper using a local .eskip file and have it accept traffic? 

Are we expected to mount a volume? What ports would we need to expose to make it work on localhost?

PS. I know I can use `docker.for.windows.localhost` and `docker.for.mac.localhost` to access the host instead of `localhost` in my eskip file.

**Comment by szuecs** [comment]
If you like create a documentation pull request for the next people that can have the same issue or not know docker. 
What do you think?

**Comment by thecodejunkie** [comment]
@szuecs Yep! I'll knock one up over the weekend
