### ISSUE TITLE
Refactor RouteInfo

### ISSUE THREAD

**Issue by danpersa** [zalando/skipper#83]
Either remove RouteInfo from everything but etcd, either implement route parsing errors for innkeeper

'routeInfos' here is visible in the docs, due to LoadAndParseAll is public, info doesn't have plural form. Please, give it a better name.

**Comment by aryszka** [comment]
note: this issue belongs to the branch add-innkeeper-cmd

**Comment by LappleApple** [comment]
Still active? Any way for others to contribute via additional refactoring or code review?

**Comment by aryszka** [comment]
i would close this now, and have a discussion to the innkeeper crew to align on the plans. @danpersa , what do you think?
