### ISSUE TITLE
Kubernetes HTTPS redirect doesn't work in GCP

### ISSUE THREAD

**Issue by dlmiddlecote** [zalando/skipper#838]
The route produced when enabling Kubernetes HTTP redirect is:
```
PathRegexp(/.*/) && Header("X-Forwarded-Proto", "http") && HeaderRegexp("X-Forwarded-Port", /.*/)
  -> redirectTo(308, "https:")
  -> <shunt>;
```

This route requires the `X-Forwarded-Port` header to be specified, and unfortunately the GCP Loadbalancer does not add this header, only `X-Forwarded-Proto`.

I think that there should be a way to overcome this, but currently there isn't, appart from turning off the redirect and specifying our own redirect path.

**Comment by aryszka** [comment]
thanks for posting this issue. Looking into finding a quick fix. Since the always matching PathRegexp is already a workaround, we may be able to build on that somehow without a too big crime.

**Comment by szuecs** [comment]
@dlmiddlecote Could you test the following image, please and report if it work for your case?
`registry.opensource.zalan.do/pathfinder/skipper-test:pr-840-1`

**Comment by dlmiddlecote** [comment]
@szuecs Hi, I've tested the change and it does work well. Thanks! I wonder whether the solution of using more predicates to cause this route to be evaluated first is troubled? i.e. if I add a custom route, that happens to have 4 predicates (maybe matching on Method and Header) then that route will trump the redirect route. Do we want the redirect route to _always_ be triggered first? If so, the suggestion of Weight/Priority sounds good. (Just my 2 pence).

**Comment by szuecs** [comment]
@dlmiddlecote we consider this change as workaround and the real solution is the Weight() predicate, but we are not there, yet.
https://github.com/zalando/skipper/issues/689#issuecomment-425889841 is the issue we need to fix it.
Please watch this one if you are interested in getting notifications, but we will also state this in release notes.
