### ISSUE TITLE
Conflicting Dependencies

### ISSUE THREAD

**Issue by mo-gr** [zalando/skipper#852]
Currently, skipper can't be build as a library when the project uses Gopkg.toml/dep ensure.

Skipper depends on (via [go.mod](https://github.com/zalando/skipper/blob/master/go.mod#L35-L48)):
- github.com/uber/jaeger-lib v1.5.0
- github.com/prometheus/client_golang v0.9.0-pre1.0.20180907102542-7858729281ec

However, the jaeger-lib in v1.5.0 has a [Gopkg.toml](https://github.com/jaegertracing/jaeger-lib/blob/v1.5.0/Gopkg.toml#L11-L13) that contains:
```
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"
```

There are braking API changes in the prometheus client and this means I can neither use 0.8.0 (it won't compile, due to the braking changes and [skipper already being updated to 0.9.0](https://github.com/zalando/skipper/pull/783)) nor 0.9.0 (dep ensure will fail with an unresolvable constraint: skipper needs 0.9.0, jaeger needs 0.8.0).

Am I doing something wrong?

**Comment by szuecs** [comment]
You have to build with Go >= 1.11 and have the ENV set `GO111MODULE=on`

**Comment by mo-gr** [comment]
@szuecs That does the trick. Even though I don't fully understand why. Thank you 🙏
