### ISSUE TITLE
External DNS Collision causes 404

### ISSUE THREAD

**Issue by jruhland** [zalando/skipper#853]
Deployed via kubernetes with ingress controller, we use a ingress that maps two very similar DNS entries, which causes intermittent "Not Found" errors, removing either of the entries will result in fixing, or adding them as separate ingresses, but together, ~20% error rate with `Not Found`

Produced on both 0.10.0 and 0.10.121

Ingress Definition Used to Reproduce:
```
{
  "kind": "Ingress",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "svc",
    "namespace": "default",
    "labels": {
      "app": "svc",
      "chart": "svc-1.0.0",
      "heritage": "Tiller",
      "release": "prd-svc"
    },
    "annotations": {
      "kubernetes.io/ingress.class": "skipper-internet-facing"
    }
  },
  "spec": {
    "rules": [
      {
        "host": "svc.prd.myapp.com",
        "http": {
          "paths": [
            {
              "path": "/",
              "backend": {
                "serviceName": "svc",
                "servicePort": "http"
              }
            }
          ]
        }
      }
      {
        "host": "svc-prd.myapp.com",
        "http": {
          "paths": [
            {
              "path": "/",
              "backend": {
                "serviceName": "svc",
                "servicePort": "http"
              }
            }
          ]
        }
      }
    ]
  }
}
```

It appears to be related to `dataclients/kubernetes/kube.go:470` on master and the fact that all non-words are replaced with an underscore

**Comment by szuecs** [comment]
@jruhland would you mind testing to change the `host: value` to `host: ^value` in both of your cases?
I think it’s because we use regexp matching to host headers as the ingress spec tells and there are multiple use cases that compete.
I will check on Monday the code line you mentioned.

**Comment by greenboxal** [comment]
Pushed a fix here: https://github.com/zalando/skipper/pull/854

**Comment by szuecs** [comment]
I was wrong for the kubernetes dataclient we create Host header matches like this. that match the dot correctly:

    Host(/a[.]b[.]localhost/)
