### ISSUE TITLE
Refactor The Command Map

### ISSUE THREAD

**Issue by danpersa** [zalando/skipper#86]
For

    src/github.com/zalando/skipper/cmd/eskip/media.go:137

Refactor the map keeping in mind @mo-gr's comment

    To me, those two maps (commandToValidations and commands in eskip.go) smell a lot like some 
    weird inside-out data structures (call it OO if you insist). I think, command should not be a type alias for 
    a string anymore but instead be a proper struct containing a command-name (the current command), a 
    validation function pointer and a commandFunc function pointer. This way, the weird map lookups 
    would go away and we could do proper validations and command execution dispatched on the actual
    command.

**Comment by LappleApple** [comment]
Is this refactoring still a to-do? Might we get some help with it?

**Comment by aryszka** [comment]
some of these changes need to be handled together. let's close this now.
