### ISSUE TITLE
configurable IdleConnectionsPerHost

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#905]
proxy.Params.IdleConnectionsPerHost can not be changed by flag

**Comment by mbertschler** [comment]
This should already be implemented in the latest tag:
https://github.com/zalando/skipper/blob/v0.10.160/cmd/skipper/main.go#L438

**Comment by szuecs** [comment]
Agree it is also passed to https://github.com/zalando/skipper/blob/v0.10.160/skipper.go#L818
