### ISSUE TITLE
Support forwarding requests

### ISSUE THREAD

**Issue by jmcs** [zalando/skipper#908]
I have a MITM proxy that adds some credentials conditionally.

I need to have a catch all rule that modifies the request headers and then forwards the request to the requested location.

Currently the only way I found to implement this was set the backend for the catch all rule to a local nginx proxy that forwards the request.

This could be done fully in skipper if skipper had a `<forward>` backend for this purpose.

**Comment by jmcs** [comment]
I added a clarification of my use case to the description.

I want to have something like:
```
* -> setRequestHeader("X-Passed-Skipper", "true") -> <forward>;
```

So that if the user requests an arbitrary domain, it gets forwarded to that arbitrary domain.

**Comment by jmcs** [comment]
This seems to be a common use case as can be seen by stackoverflow questions on how to do this nginx, for example:

- https://stackoverflow.com/questions/46060028/how-to-use-nginx-as-forward-proxy-for-any-requested-location
- https://stackoverflow.com/questions/49459903/nginx-as-a-forward-proxy

**Comment by szuecs** [comment]
Forward proxy can't be done right now and would need to have a backend like you suggest. 
Normally this also means, that we need to implement the CONNECT Method.
https://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_method.
