### ISSUE TITLE
Access logging based on response code

### ISSUE THREAD

**Issue by avb1989** [zalando/skipper#909]
We love the disableAccessLog() filter. It would be nicer if we could choose to disable/enable logs based on response code. That way we can do away with logging all the `2xx`s, and only log the errors in access logs.

May look something like `Path("/api/frequently-requested-resource") -> disableAccessLog(200, 201) -> "https://related-backend.com`.

I've already gone through the code a bit and can work on it.

**Comment by szuecs** [comment]
I am happy to review the PR.
Please do it in a backwards compatible way so  `disableAccessLog()` means disable and optional a list of status codes can be defined.

Please make sure you run `make fmt` and `make lint` before creating the PR ( `make deps` to install staticcheck that is required for `make lint`), thanks.
