### ISSUE TITLE
Add ability to pass in entire tls.Config for both proxy and client isde

### ISSUE THREAD

**Issue by UltraNemesis** [zalando/skipper#911]
Rather than passing in just tls cert and key, it would be better to have entire tls.Config struct for both proxy and client sides to be passed in through skipper.Options structure so that user can have finer control over it. 

Specifically, It be helpful if someone say wants to setup two way SSL.

**Comment by szuecs** [comment]
Ah yes mTLS with client certificates, thanks for the clarification.
Makes of course sense!

**Comment by UltraNemesis** [comment]
I created a PR #917 for passing tls.Config for the Proxy Server part.

**Comment by UltraNemesis** [comment]
Now that PR #919 is merged in for addressing the ProxyTLS settings, the other part of this is the backend (client) TLS settings which would be a bit more complicated because each backend can theoretically have different settings. For example, few backends could be two way SSL and others one way.

**Comment by szuecs** [comment]
IMHO it makes more sense to have only one identity, so one client cert and not per backend.

**Comment by UltraNemesis** [comment]
The client certs are issued by the owner of the backend services to authorize access to them. If all the backend services share the same owner as the skipper instance, single client cert makes sense, but for example, like in our case, we have different group companies (part of the group, but still independent) and third party partners that interact through API servers. Each entity has its own self signed Certificate Authority from which they sign cert certificates. If I have to use skipper as a gateway for routing in such a scenario, I would need to have have multiple client certs issued to me from each of the back ends. 

Both the client cert scenario and the server cert selection based on SNI you pointed is possible by overriding the GetCertificate and GetClientCertificate methods in tls.Config. Its only a matter of deciding how to integrate this. For example, you can load all the certs put in file or directory and and write custom logic for these methods to decide which one to use. Alternatively, we can have a manifest file of sorts which will contain a domain to cert file mapping which can then be used to pick the right cert on demand.

**Comment by szuecs** [comment]
I think this can be closed and the follow up would be #924

**Comment by szuecs** [comment]
@UltraNemesis thanks again released at https://github.com/zalando/skipper/releases/tag/v0.10.159
