### ISSUE TITLE
Load balancing metrics

### ISSUE THREAD

**Issue by aermakov-zalando** [zalando/skipper#920]
When load balancing, metrics should be tracked over the "root" load balancing route, not over the individual ones. Right now, a Kubernetes setup with 100 pods for a given service will just explode the metrics because most of them will have 100 copies, one per each pod, and the users don't really care about those.

**Comment by aermakov-zalando** [comment]
Somewhat related to #556.

**Comment by szuecs** [comment]
As far as I understand this is already done via #556.
