### ISSUE TITLE
Set target backend for a request from a filter based on request headers/body?

### ISSUE THREAD

**Issue by UltraNemesis** [zalando/skipper#923]
Is it currently possible to select the target back end for a request based on a request header or some other condition based on the request body?

I did not find any existing filter of this sort, but I also didn't see any way in the filter context to set a target backend on the fly.

**Comment by szuecs** [comment]
No it's not possible right now, but https://github.com/zalando/skipper/pull/918 implements a <forward> backend which does the proxy call to the chosen target from the caller.

For example:
skipper listening on port 9090 and use route: `r: * -> <forward>` would forward the call from the client to `https://www.zalando.de/`.

client:
`curl -v --proxy http://localhost:9090 http://www.zalando.de/`

Note that the client call from skipper will be per default always https and is only able to change globally via `-forward-uri-scheme=http` with the mentioned PR.

Next step for this would be to implement CONNECT similar to upgrade headers as stated in https://github.com/zalando/skipper/pull/918#issuecomment-455614516

**Comment by szuecs** [comment]
Thanks @Traumeel
