### ISSUE TITLE
wrong log method

### ISSUE THREAD

**Issue by Shareed2k** [zalando/skipper#952]
https://github.com/zalando/skipper/blob/b810146fb00e7b247671aa5fd428dcd2c71b0082/proxy/proxy.go#L943

**Comment by Shareed2k** [comment]
> [skipper/proxy/proxy.go](https://github.com/zalando/skipper/blob/b810146fb00e7b247671aa5fd428dcd2c71b0082/proxy/proxy.go#L943)
> 
> Line 943 in [b810146](/zalando/skipper/commit/b810146fb00e7b247671aa5fd428dcd2c71b0082)
> 
>  p.log.Debug("deprecated shunting detected in route: %s", ctx.route.Id)

**Comment by aryszka** [comment]
Hi @Shareed2k , thanks for posting this issue. What behavior would you expect or what would be a better log method?

The reason for that it's Debug, is that this functionality still works the same way how earlier filter implementation called shunting.

**Comment by Shareed2k** [comment]
you should use Debugf

**Comment by aryszka** [comment]
oh, I see now, thanks a lot! :smile:
