### ISSUE TITLE
eskip pretty printing option

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#97]
consider if this should be done by eskip, or just provide an awk example

**Comment by pc-alves** [comment]
Working on this issue I came across a question: Should indentation be

1. a single space (`' '`)
2. a single tab (`\t`)
3. one of the above as default, and an option for the number of spaces (`-s4` to have 4 spaces)

Any thoughts? Comments?

**Comment by aryszka** [comment]
in our practice, two spaces became a de-facto standard. It could be the default for the tool, too. For overriding, I would prefer a single option, where one can specify just anything as the atomic indentation:

```
-indent "    "
```

the value of this parameter could be validated with "\s*", because we accept all \s when parsing eskip.

**Comment by lmineiro** [comment]
Wondering if we could consider the "existing" OFS, RS, ... environment variables that already control the output of some well known tools, line AWK

**Comment by LappleApple** [comment]
Hey @aryszka @pc-alves @lmineiro This issue started in Jan 2016. Anything we can do here--add a Help Wanted label, add something to the README, etc.? Would like to close.

**Comment by pc-alves** [comment]
PR #180 implemented pretty-print with a default option of two spaces for indentation.
@aryszka suggested the `-indent "    "` command line option, which was not implemented. I left the issue open for this reason. But I'm fine with closing it, and having the `indent` option as a separate issue.

**Comment by LappleApple** [comment]
Thanks, @pc-alves.
